import { createGameSimulatorCommandActionCommands } from "./command-action-commands.mjs";
import { createGameSimulatorCommandActionCompletions } from "./command-action-completions.mjs";
import { createGameSimulatorCommandBoundaryOutcomes } from "./command-boundary-outcomes.mjs";
import { createGameSimulatorCommandShotOutcomes } from "./command-shot-outcomes.mjs";
import { createGameSimulatorCommandTransitOutcomes } from "./command-transit-outcomes.mjs";
import { createGameSimulatorCommandAutoplay } from "./command-autoplay.mjs";
import { createGameSimulatorCommandSimulationStep } from "./command-simulation-step.mjs";
import { createGameSimulatorCommandStatusDescriptions } from "./command-status-descriptions.mjs";
import { createGameSimulatorCommandSequenceRecorder } from "./command-sequence-recorder.mjs";
import { createGameSimulatorCommandLooseBallRecovery } from "./command-loose-ball-recovery.mjs";

export function createGameSimulatorCommandEngine(deps = {}) {
  const {
    angleBetween,
    applyAutopilotsForCurrentAction,
    applyBallExecutionProfile,
    applyBestReceiveBodyAngle,
    applyCommittedSnapshot,
    applyCornerSetup,
    applyFreeKickSetup,
    applyGoalKickSetup,
    applyKickoffSetup,
    applyPenaltySetup,
    applyResolvedBallProfile,
    applySnapshot,
    applyThrowInSetup,
    ballRadiusMeters,
    buildMovementPath,
    canEditScenario,
    captureSnapshot,
    chooseAutoPilotNextAction,
    clamp,
    clampToPitch,
    clearAutoPilotReceiveMomentum,
    clearKeyboardActionGrace,
    clearSecurePossession,
    cloneAutoV2DecisionTriggers,
    cloneDefensiveAutopilotIntents,
    cloneGoalEvent,
    cloneOffensiveAutopilotIntents,
    cloneRestartPhase,
    cloneShotPlacement,
    cloneSnapshot,
    cloneVector,
    completeLiveActionPlayersBeforeCommit,
    computeReachDistance,
    computeTimeToCoverDistance,
    configureBallTravelProfile,
    connectBallToPlayerForNextAction,
    createCommittedSnapshotFromCurrentState,
    createLooseBallSpill,
    defaultKickoffTeamId,
    distance,
    executePlannedAction,
    finishSequencePlayback,
    formatSpeed,
    formatTime,
    getActionInitiator,
    getActionOrigin,
    getActionSpeed,
    getAttackDirectionSign,
    getAttackingDepth,
    getAutoPilotFlowContext,
    getAutoPilotReceiveMomentum,
    getBallOwner,
    getBallFlightControlFactor,
    getBallTravelPoint,
    getDefensiveAutoV2Intent,
    getDefensiveAutopilotFocusPoint,
    getDribbleCarryPathPoint,
    getFirstTouchModeLabel,
    getGoalDirectionSign,
    getGoalLineX,
    getGoalNetDisplayPoint,
    getLiveDefensiveDribblePressTarget,
    getLiveDribbleSpeed,
    getMovementPathPoint,
    getOffensiveAutoV2Intent,
    getOffensiveAutopilotFocusPoint,
    getOffensiveAutopilotProfile,
    getOffensiveRoleKey,
    getOffsideInfo,
    getOpponentGoalCenter,
    getOpponentGoalSide,
    getOpponentPenaltySpot,
    getOpponentPressureAtPoint,
    getOtherTeamId,
    getPitchThreatProfile,
    getPlannedPossessionTeamId,
    getPlayerById,
    getPlayerBallControlPoint,
    getPlayerDecisionContext,
    getPlayerMagnetLabel,
    getPlayerPositionForControlPoint,
    getPlayerPressureLoad,
    getPlayerRoleModel,
    getPlayerTendency,
    getRecordedStepEndSnapshot,
    getRequestedActionMode,
    getSelectedPlayer,
    getTeamAttackAngle,
    getTeamSupportCountAroundPoint,
    hasBallAction,
    isBetweenGoalPosts,
    isDefensiveAutopilotPlayer,
    isDefensiveDribblePresser,
    isGoalkeeper,
    isInsideOpponentBox,
    isInsideOwnBox,
    isWideChannel,
    isOffensiveAutopilotPlayer,
    keepSecurePossessionOnlyForOwner,
    lerp,
    logEvent,
    markSequenceDirty,
    moveDefensiveAutoV2Player,
    moveOffensiveAutoV2Player,
    moveTowards,
    normalize,
    pauseLiveSimulation,
    pitch,
    queueNextSequenceStep,
    randomBetween,
    render,
    resetPlayerMovementProgress,
    resolveBallActionProfile,
    resolveDribbleDefensiveChallenge,
    resolveLooseBallClaim,
    resolvePassTransitInterception,
    resolveShotBlockCommitment,
    resolveShotTarget,
    rotatePlayerBodyAlongMovement,
    rotatePlayerBodyToward,
    rotatePlayerBodyTowardAngle,
    setDribbleCarryPathForBall,
    setPiecePhaseProfiles,
    setSecurePossessionAfterControlledTouch,
    setSelectedPlayers,
    settleBallForNextAction,
    shouldTriggerLandingBounce,
    startLandingBounceSkid,
    startRecordedAction,
    teams,
    ui,
    updateBallFlightHeight,
    updateSequenceButtons,
    win,
    getState,
  } = deps;
  const state = new Proxy({}, {
    get(_target, property) {
      return getState?.()?.[property];
    },
    set(_target, property, value) {
      const currentState = getState?.();
      if (currentState) {
        currentState[property] = value;
      }
      return true;
    },
    has(_target, property) {
      return property in (getState?.() ?? {});
    },
    ownKeys() {
      return Reflect.ownKeys(getState?.() ?? {});
    },
    getOwnPropertyDescriptor(_target, property) {
      const currentState = getState?.() ?? {};
      if (!Object.prototype.hasOwnProperty.call(currentState, property)) {
        return undefined;
      }
      return {
        configurable: true,
        enumerable: true,
        writable: true,
        value: currentState[property],
      };
    },
  });

function getAutoPilotRoleStrength(player, strength) {
if (!player) {
return 0;
}
const context = getPlayerDecisionContext(player);
const roleKey = getOffensiveRoleKey(player, teams[player.team]?.formation);
const roleModel = getPlayerRoleModel(player, teams[player.team]?.formation);
const paceScore = clamp((context.maxSpeed - 6.5) / 2.8, 0, 1);
const roleBonuses = {
creator: {
gk: -0.08,
rest: 0.02,
wideBack: 0.08,
pivot: 0.14,
connector: 0.18,
wideForward: 0.1,
striker: 0.02,
secondStriker: 0.12,
},
receiver: {
gk: -0.18,
rest: -0.02,
wideBack: 0.06,
pivot: 0.08,
connector: 0.16,
wideForward: 0.14,
striker: 0.18,
secondStriker: 0.18,
},
runner: {
gk: -0.28,
rest: -0.12,
wideBack: 0.16,
pivot: -0.04,
connector: 0.08,
wideForward: 0.22,
striker: 0.2,
secondStriker: 0.14,
},
dribbler: {
gk: -0.24,
rest: -0.1,
wideBack: 0.1,
pivot: 0.02,
connector: 0.12,
wideForward: 0.24,
striker: 0.08,
secondStriker: 0.13,
},
finisher: {
gk: -0.42,
rest: -0.18,
wideBack: -0.08,
pivot: -0.06,
connector: 0.08,
wideForward: 0.16,
striker: 0.28,
secondStriker: 0.22,
},
crosser: {
gk: -0.3,
rest: -0.12,
wideBack: 0.24,
pivot: -0.02,
connector: 0.04,
wideForward: 0.18,
striker: -0.1,
secondStriker: -0.04,
},
switcher: {
gk: 0.02,
rest: 0.08,
wideBack: 0.1,
pivot: 0.2,
connector: 0.16,
wideForward: 0.02,
striker: -0.08,
secondStriker: 0.02,
},
};
const roleBonus = roleBonuses[strength]?.[roleKey] ?? 0;
const roleModelBoost = roleModel.strengths?.[strength] ?? 0;
const profile = context.profile;
const base =
strength === "runner"
? paceScore * 0.42 + profile.perception * 0.2 + profile.decisionSpeed * 0.18 + profile.tacticalDiscipline * 0.2
: strength === "dribbler"
? profile.technicalSecurity * 0.3 + profile.pressResistance * 0.26 + profile.composure * 0.18 + paceScore * 0.26
: strength === "finisher"
? profile.technicalSecurity * 0.28 + profile.composure * 0.22 + profile.decisionQuality * 0.26 + paceScore * 0.12 + profile.perception * 0.12
: strength === "crosser" || strength === "switcher"
? profile.technicalSecurity * 0.34 + profile.decisionQuality * 0.26 + profile.perception * 0.22 + profile.composure * 0.18
: strength === "receiver"
? profile.perception * 0.24 + profile.technicalSecurity * 0.26 + profile.decisionSpeed * 0.18 + profile.composure * 0.16 + paceScore * 0.16
: profile.perception * 0.28 + profile.decisionQuality * 0.3 + profile.technicalSecurity * 0.2 + profile.composure * 0.12 + profile.decisionSpeed * 0.1;
const tendencyBoost =
strength === "runner"
? Math.max(getPlayerTendency(player, "boxRun"), getPlayerTendency(player, "overlap")) - 0.5
: strength === "dribbler"
? getPlayerTendency(player, "dribble") - 0.5
: strength === "crosser"
? getPlayerTendency(player, "earlyCross") - 0.5
: strength === "switcher"
? getPlayerTendency(player, "switchPlay") - 0.5
: strength === "receiver"
? getPlayerTendency(player, "passAndMove") - 0.5
: strength === "creator"
? Math.max(getPlayerTendency(player, "lineBreakPass"), getPlayerTendency(player, "retain")) - 0.5
: 0;
return clamp(base + roleBonus + roleModelBoost + tendencyBoost * 0.18, 0, 1.18);
}
function getAutoPilotPossessionPlayer() {
const owner = getBallOwner();
if (owner) {
return owner;
}
const claim = resolveLooseBallClaim(
state.ball.position,
state.ball.claimRadius + 1.1,
null,
0,
{}
);
if (claim.player && claim.gap <= state.ball.claimRadius + 1.4) {
connectBallToPlayerForNextAction(claim.player, state.ball.position, 0.48);
return claim.player;
}
return null;
}
const commandLooseBallRecovery = createGameSimulatorCommandLooseBallRecovery({
  angleBetween,
  applyAutopilotsForCurrentAction,
  captureSnapshot,
  clamp,
  clampToPitch,
  clearAutoPilotReceiveMomentum,
  clearSecurePossession,
  cloneVector,
  computeTimeToCoverDistance,
  connectBallToPlayerForNextAction,
  distance,
  formatTime,
  getAttackDirectionSign,
  getAttackingDepth,
  getOffensiveAutopilotProfile,
  getOffensiveRoleKey,
  getOpponentGoalCenter,
  getOpponentPressureAtPoint,
  getPitchThreatProfile,
  getPlayerBallControlPoint,
  getPlayerDecisionContext,
  getPlayerMagnetLabel,
  getPlayerPositionForControlPoint,
  getTeamAttackAngle,
  getTeamSupportCountAroundPoint,
  isGoalkeeper,
  isInsideOpponentBox,
  isInsideOwnBox,
  isWideChannel,
  keepSecurePossessionOnlyForOwner,
  lerp,
  logEvent,
  normalize,
  pitch,
  setSecurePossessionAfterControlledTouch,
  setSelectedPlayers,
  state,
  teams,
});
const {
  getLooseBallRecoveryTarget,
  getSecondBallReactionAdjustment,
  getLooseBallRecoveryStructureAdjustment,
  getLooseBallNearestOpponent,
  getLooseBallCollectControlTouch,
  applyLooseBallCollectControlTouch,
  chooseAutoPilotLooseBallRecovery,
  issueLooseBallRecoveryCommand,
} = commandLooseBallRecovery;
const commandAutoplay = createGameSimulatorCommandAutoplay({
  applyAutopilotsForCurrentAction,
  chooseAutoPilotLooseBallRecovery,
  chooseAutoPilotNextAction,
  clamp,
  clearKeyboardActionGrace,
  cloneVector,
  defaultKickoffTeamId,
  executePlannedAction,
  getAttackingDepth,
  getAutoPilotFlowContext,
  getAutoPilotPossessionPlayer,
  getAutoPilotReceiveMomentum,
  getOffensiveAutopilotProfile,
  getPitchThreatProfile,
  getPlayerBallControlPoint,
  getPlayerById,
  getPlayerMagnetLabel,
  getPlayerPressureLoad,
  hasBallAction,
  issueDribbleCommand: (...args) => issueDribbleCommand(...args),
  issueLooseBallRecoveryCommand,
  issuePassCommand: (...args) => issuePassCommand(...args),
  issueShotCommand: (...args) => issueShotCommand(...args),
  logEvent,
  pauseLiveSimulation,
  randomBetween,
  render,
  state,
  teams,
  updateSequenceButtons,
  win,
});
const {
  describeAutoPilotChoice,
  planAutoPilotNextAction,
  cancelAutoPilotContinuation,
  pauseAutoPilotPlay,
  getAutoPilotContinuationContext,
  getAutoPilotContinuationDelay,
  scheduleAutoPilotContinuation,
} = commandAutoplay;
const commandActionCommands = createGameSimulatorCommandActionCommands({
  applyAutopilotsForCurrentAction,
  applyBallExecutionProfile,
  applyBestReceiveBodyAngle,
  applyResolvedBallProfile,
  canEditScenario,
  captureSnapshot,
  clampToPitch,
  clearAutoPilotReceiveMomentum,
  clearSecurePossession,
  cloneVector,
  configureBallTravelProfile,
  distance,
  formatSpeed,
  getActionSpeed,
  getBallOwner,
  getOffsideInfo,
  getPlayerBallControlPoint,
  getPlayerById,
  getRequestedActionMode,
  getSelectedPlayer,
  getTeamAttackAngle,
  hasBallAction,
  logEvent,
  render,
  resetPlayerMovementProgress,
  resolveBallActionProfile,
  resolveShotTarget,
  rotatePlayerBodyToward,
  setDribbleCarryPathForBall,
  state,
});
const {
  refreshPlannedBallActionProfile,
  clearBallAction,
  setBallOwner,
  issuePassLikeCommand,
  issuePassCommand,
  issueShotCommand,
  issueDribbleCommand,
  issueBallCommand,
} = commandActionCommands;
const commandStatusDescriptions = createGameSimulatorCommandStatusDescriptions({
  getFirstTouchModeLabel,
  getPlayerById,
  getRequestedActionMode,
  hasBallAction,
  setPiecePhaseProfiles,
  state,
  teams,
});
const {
  getBallStatus,
  getActionTypeLabel,
  describeStep,
} = commandStatusDescriptions;
const commandSequenceRecorder = createGameSimulatorCommandSequenceRecorder({
  applyCommittedSnapshot,
  applyCornerSetup,
  applyFreeKickSetup,
  applyGoalKickSetup,
  applyKickoffSetup,
  applyPenaltySetup,
  applyThrowInSetup,
  captureSnapshot,
  clearBallAction,
  cloneAutoV2DecisionTriggers,
  cloneDefensiveAutopilotIntents,
  cloneGoalEvent,
  cloneOffensiveAutopilotIntents,
  cloneRestartPhase,
  cloneShotPlacement,
  cloneSnapshot,
  cloneVector,
  createCommittedSnapshotFromCurrentState,
  describeStep,
  getRecordedStepEndSnapshot,
  logEvent,
  markSequenceDirty,
  state,
});
const {
  getSequenceStartSnapshot,
  getSequenceFrameSnapshot,
  persistCurrentFrameSnapshot,
  finalizeCurrentActionStep,
} = commandSequenceRecorder;
const commandBoundaryOutcomes = createGameSimulatorCommandBoundaryOutcomes({
  ballRadiusMeters,
  clamp,
  getActionInitiator,
  getGoalDirectionSign,
  getGoalLineX,
  getGoalNetDisplayPoint,
  getOpponentGoalSide,
  getOtherTeamId,
  getPlannedPossessionTeamId,
  getPlayerById,
  isBetweenGoalPosts,
  lerp,
  pitch,
  state,
});
const {
  detectShotGoal,
  detectShotOutOfPlay,
  detectTouchlineOutOfPlay,
} = commandBoundaryOutcomes;
const commandShotOutcomes = createGameSimulatorCommandShotOutcomes({
  applyCommittedSnapshot,
  captureSnapshot,
  clamp,
  clampToPitch,
  clearSecurePossession,
  cloneGoalEvent,
  cloneSnapshot,
  cloneVector,
  completeLiveActionPlayersBeforeCommit,
  computeTimeToCoverDistance,
  connectBallToPlayerForNextAction,
  createLooseBallSpill,
  distance,
  finalizeCurrentActionStep,
  formatTime,
  getGoalDirectionSign,
  getOpponentPenaltySpot,
  getPlayerDecisionContext,
  getPlayerMagnetLabel,
  isGoalkeeper,
  isInsideOwnBox,
  lerp,
  logEvent,
  pitch,
  queueNextSequenceStep,
  rotatePlayerBodyToward,
  scheduleAutoPilotContinuation,
  setPiecePhaseProfiles,
  state,
  teams,
  ui,
});
const {
  getGoalkeeperForTeam,
  getPreferredParrySafetyPlayer,
  getGoalkeeperParryProfile,
  resolveGoalkeeperSave,
  registerGoalFlash,
  completeGoalkeeperSave,
  completeShotGoal,
  completeShotOutOfPlay,
  completeTouchlineOutOfPlay,
} = commandShotOutcomes;
const commandTransitOutcomes = createGameSimulatorCommandTransitOutcomes({
  captureSnapshot,
  cloneSnapshot,
  completeLiveActionPlayersBeforeCommit,
  finalizeCurrentActionStep,
  logEvent,
  queueNextSequenceStep,
  scheduleAutoPilotContinuation,
  state,
  ui,
});
const {
  getTransitOutcomeEventLabel,
  completeTransitOutcome,
} = commandTransitOutcomes;
const commandActionCompletions = createGameSimulatorCommandActionCompletions({
  applyCommittedSnapshot,
  applyLooseBallCollectControlTouch,
  cloneVector,
  completeLiveActionPlayersBeforeCommit,
  finalizeCurrentActionStep,
  formatTime,
  getPlayerBallControlPoint,
  logEvent,
  queueNextSequenceStep,
  scheduleAutoPilotContinuation,
  settleBallForNextAction,
  shouldTriggerLandingBounce,
  startLandingBounceSkid,
  state,
  ui,
});
const {
  completeBallTravelArrival,
  completeDribbleCarry,
  completeLooseBallRecoveryAction,
} = commandActionCompletions;
const commandSimulationStep = createGameSimulatorCommandSimulationStep({
  angleBetween,
  applyBestReceiveBodyAngle,
  applySnapshot,
  ballRadiusMeters,
  buildMovementPath,
  clamp,
  clearBallAction,
  cloneVector,
  completeBallTravelArrival,
  completeDribbleCarry,
  completeGoalkeeperSave,
  completeLooseBallRecoveryAction,
  completeShotGoal,
  completeShotOutOfPlay,
  completeTouchlineOutOfPlay,
  completeTransitOutcome,
  computeReachDistance,
  describeStep,
  detectShotGoal,
  detectShotOutOfPlay,
  detectTouchlineOutOfPlay,
  distance,
  finishSequencePlayback,
  getActionOrigin,
  getActionSpeed,
  getBallFlightControlFactor,
  getBallTravelPoint,
  getDefensiveAutoV2Intent,
  getDefensiveAutopilotFocusPoint,
  getDribbleCarryPathPoint,
  getLiveDefensiveDribblePressTarget,
  getLiveDribbleSpeed,
  getMovementPathPoint,
  getOffensiveAutoV2Intent,
  getOffensiveAutopilotFocusPoint,
  getPlayerBallControlPoint,
  getPlayerById,
  isDefensiveAutopilotPlayer,
  isDefensiveDribblePresser,
  isOffensiveAutopilotPlayer,
  logEvent,
  moveDefensiveAutoV2Player,
  moveOffensiveAutoV2Player,
  moveTowards,
  resolveDribbleDefensiveChallenge,
  resolveGoalkeeperSave,
  resolvePassTransitInterception,
  resolveShotBlockCommitment,
  rotatePlayerBodyAlongMovement,
  rotatePlayerBodyToward,
  rotatePlayerBodyTowardAngle,
  setDribbleCarryPathForBall,
  startRecordedAction,
  state,
  ui,
  updateBallFlightHeight,
});
const {
  updateBall,
  updateDribble,
  updateLooseBallRecovery,
  updateActionPlayers,
  updateSequenceActionPlayers,
  updateLiveActionPlayers,
  updateSequenceTransition,
  stepSimulation,
} = commandSimulationStep;
  return {
    getAutoPilotRoleStrength,
    getAutoPilotPossessionPlayer,
    getLooseBallRecoveryTarget,
    getSecondBallReactionAdjustment,
    getLooseBallRecoveryStructureAdjustment,
    getLooseBallNearestOpponent,
    getLooseBallCollectControlTouch,
    applyLooseBallCollectControlTouch,
    chooseAutoPilotLooseBallRecovery,
    issueLooseBallRecoveryCommand,
    describeAutoPilotChoice,
    planAutoPilotNextAction,
    cancelAutoPilotContinuation,
    pauseAutoPilotPlay,
    getAutoPilotContinuationContext,
    getAutoPilotContinuationDelay,
    scheduleAutoPilotContinuation,
    refreshPlannedBallActionProfile,
    clearBallAction,
    setBallOwner,
    issuePassLikeCommand,
    issuePassCommand,
    issueShotCommand,
    issueDribbleCommand,
    issueBallCommand,
    detectShotGoal,
    detectShotOutOfPlay,
    detectTouchlineOutOfPlay,
    getGoalkeeperForTeam,
    getPreferredParrySafetyPlayer,
    getGoalkeeperParryProfile,
    resolveGoalkeeperSave,
    registerGoalFlash,
    completeGoalkeeperSave,
    completeShotGoal,
    completeShotOutOfPlay,
    completeTouchlineOutOfPlay,
    getTransitOutcomeEventLabel,
    completeTransitOutcome,
    completeBallTravelArrival,
    completeDribbleCarry,
    completeLooseBallRecoveryAction,
    updateBall,
    updateDribble,
    updateLooseBallRecovery,
    updateActionPlayers,
    updateSequenceActionPlayers,
    updateLiveActionPlayers,
    updateSequenceTransition,
    stepSimulation,
    getBallStatus,
    getActionTypeLabel,
    describeStep,
    getSequenceStartSnapshot,
    getSequenceFrameSnapshot,
    persistCurrentFrameSnapshot,
    finalizeCurrentActionStep,
  };
}
