import { createGameSimulatorActionSpaceMetrics } from "./action-space-metrics.mjs";
import { createGameSimulatorAutopilotCandidates } from "./autopilot-candidates.mjs";
import { createGameSimulatorAutopilotDecisionEngine } from "./autopilot-decision-engine.mjs";
import { createGameSimulatorAutopilotDefensiveTargets } from "./autopilot-defensive-targets.mjs";
import { createGameSimulatorAutopilotLiveEngine } from "./autopilot-live-engine.mjs";
import { createGameSimulatorAutopilotOffballTargets } from "./autopilot-offball-targets.mjs";
import { createGameSimulatorAutopilotTargets } from "./autopilot-targets.mjs";
import { createGameSimulatorBallResolutionEngine } from "./ball-resolution-engine.mjs";
import { createGameSimulatorCommandEngine } from "./command-engine.mjs";
import { createGameSimulatorGeometryHelpers } from "./geometry-helpers.mjs";
import { createGameSimulatorSetupEngine } from "./setup-engine.mjs";

export function createGameSimulatorEngineBundle(deps = {}) {
const {
  applyCommittedSnapshot, applySnapshot, autoBallProfiles,
  autoDribbleProfiles, ballRadiusMeters, canEditScenario,
  captureSnapshot, clearKeyboardActionGrace, cloneRestartPhase,
  cloneSnapshot, competitionPhysicalProfiles, createCommittedSnapshotFromCurrentState,
  defaultKickoffTeamId, defaultPhysicalProfileKey, defensiveAggressionPresets,
  defensiveAutopilotProfiles, defensivePhaseProfiles, executePlannedAction,
  finishSequencePlayback, firstTouchModes, formationLayouts,
  formationMagnetLabels, gameRoleProfiles, getAttackStyleRhythmProfile,
  getBallOwner, getNearestOpponentGap, getPlayerById,
  getPlayerDecisionContext, getPlayerPressureLoad, getSelectedPlayer,
  getState, getTeamAttackStyleKey, getTeamAttackStyleProfile,
  getTeamDefenseStyleKey, getTeamDefenseStyleProfile, intelligenceLabelBoosts,
  intelligenceRoleArchetypes, logEvent, markSequenceDirty,
  offensiveAutopilotProfiles, offensivePhaseProfiles, pauseLiveSimulation,
  pitch, pitchSurfacePresets, playerRadiusMeters,
  playerTendencyTemplates, possessionRhythmDefaults, queueNextSequenceStep,
  render, resolvePreferredFoot, resolveWeakFootQuality,
  setPiecePhaseProfiles, setSelectedPlayers, sprintRoleArchetypes,
  squadBlueprints, startRecordedAction, teamRosterOrder,
  teams, ui, updateSequenceButtons,
  weatherPresets, win
} = deps;
const {
  getPlayerMagnetLabel,
  vec,
  cloneVector,
  cloneSecurePossession,
  cloneGoalEvent,
  cloneShotPlacement,
  subtract,
  clamp,
  lerp,
  randomBetween,
  randomSign,
  addPointNoise,
  chooseWeightedOption,
  getNaturalDecisionDiversityWeight,
  getAutoPilotDecisionPersonalityWeight,
  chooseScoredCandidateWithVariation,
  clampToPitch,
  distance,
  normalize,
  moveTowards,
  normalizeAngle,
  angleBetween,
  angleDifference,
  getTeamAttackAngle,
  getPlayerFacingAngle,
  rotatePlayerBodyToward,
  rotatePlayerBodyTowardAngle,
  rotatePlayerBodyAlongMovement,
  getBallAwareBodyAngle,
  getPlayerBallControlPoint,
  getPreferredFootOffsetAngle,
  getFootUsageScore,
  blendAngles,
  projectPointOnSegment,
  projectPointOnSegmentWithRatio,
  formatTime,
  formatSpeed,
  formatMeters,
  getIntelligenceArchetype,
  getSprintArchetype,
} = createGameSimulatorGeometryHelpers({
  formationMagnetLabels,
  getActionSpaceValue: (...args) => getActionSpaceValue(...args),
  getAutoPilotCandidatePattern: (...args) => getAutoPilotCandidatePattern(...args),
  getAutoPilotRoleStrength: (...args) => getAutoPilotRoleStrength(...args),
  getBallControlOffsetMeters: (...args) => getBallControlOffsetMeters(...args),
  getPitchLaneIndex: (...args) => getPitchLaneIndex(...args),
  getPitchThreatProfile: (...args) => getPitchThreatProfile(...args),
  getPlayerDecisionContext: (...args) => getPlayerDecisionContext(...args),
  getPlayerTeamId: (...args) => getPlayerTeamId(...args),
  getPlayerTendency: (...args) => getPlayerTendency(...args),
  getRecentPossessionSteps: (...args) => getRecentPossessionSteps(...args),
  getRecordedStepPattern: (...args) => getRecordedStepPattern(...args),
  intelligenceRoleArchetypes,
  isTransitionAttackStyle: (...args) => isTransitionAttackStyle(...args),
  pitch,
  sprintRoleArchetypes,
  teamRosterOrder,
  teams,
});

const gameSimulatorSetupEngine = createGameSimulatorSetupEngine({
  angleBetween,
  ballRadiusMeters,
  chooseScoredCandidateWithVariation,
  chooseWeightedOption,
  clamp,
  clampToPitch,
  cloneVector,
  competitionPhysicalProfiles,
  defaultKickoffTeamId,
  defaultPhysicalProfileKey,
  defensiveAutopilotProfiles,
  defensivePhaseProfiles,
  distance,
  formationLayouts,
  getAttackDirectionSign: (...args) => getAttackDirectionSign(...args),
  getDefensiveAutopilotLineKey: (...args) => getDefensiveAutopilotLineKey(...args),
  getDefensiveCompactLineIntegritySettings: (...args) => getDefensiveCompactLineIntegritySettings(...args),
  getDefensiveGoalkeeperTarget: (...args) => getDefensiveGoalkeeperTarget(...args),
  getDefensiveLineCenterY: (...args) => getDefensiveLineCenterY(...args),
  getDefensiveLineX: (...args) => getDefensiveLineX(...args),
  getDefensiveUnitGap: (...args) => getDefensiveUnitGap(...args),
  getIntelligenceArchetype,
  getOffensiveAutopilotProfile: (...args) => getOffensiveAutopilotProfile(...args),
  getOffensiveRoleKey: (...args) => getOffensiveRoleKey(...args),
  getOpponentGoalCenter: (...args) => getOpponentGoalCenter(...args),
  getOpponentPenaltySpot: (...args) => getOpponentPenaltySpot(...args),
  getOtherTeamId: (...args) => getOtherTeamId(...args),
  getPlayerMagnetLabel,
  getSprintArchetype,
  getTeamAttackAngle,
  getTeamAttackStyleProfile,
  getTeamDefenseStyleKey,
  getTeamDefenseStyleProfile,
  intelligenceLabelBoosts,
  invalidateAutoPilotPossessionPlan: (...args) => invalidateAutoPilotPossessionPlan(...args),
  isFrontLineRole: (...args) => isFrontLineRole(...args),
  isGoalkeeper: (...args) => isGoalkeeper(...args),
  normalize,
  pitch,
  playerRadiusMeters,
  playerTendencyTemplates,
  randomBetween,
  randomSign,
  resolvePreferredFoot,
  resolveWeakFootQuality,
  setPiecePhaseProfiles,
  squadBlueprints,
  teamRosterOrder,
  teams,
  vec,
  getState,
});
const {
  applyCornerSetup,
  applyFreeKickSetup,
  applyGoalKickSetup,
  applyKickoffSetup,
  applyPenaltySetup,
  applyPhysicalProfileToPlayers,
  applyThrowInSetup,
  buildPlayerIntelligenceProfile,
  buildPlayerSprintProfile,
  buildPlayerTendencyProfile,
  createPlayer,
  getBallControlOffsetMeters,
  getCompetitionPhysicalLabel,
  getCompetitionPhysicalProfile,
  getCornerKickSpot,
  getFormationPositions,
  getKickoffDefensivePhaseKey,
  getKickoffSupportId,
  getKickoffTakerId,
  getKickoffSpot,
  getPlayerPositionForControlPoint,
  getPlayerTeamId,
  getPlayerTendency,
  kickoffOpeningProfiles,
  placePlayerWithControlPoint,
  resetPlayerMovementProgress,
  setTeamFormationOnPlayers,
} = gameSimulatorSetupEngine;
const {
  getRemainingBallDistance,
  hasBallAction,
  getActionOrigin,
  getProjectedActionDuration,
  getCurrentActionDuration,
  getActionInitiator,
  getOrientationTurnDelay,
  getOrientationMovementProfile,
  getCoverShadowInfluence,
  getReceiveOrientationScore,
  getBestReceiveBodyAngle,
  getReceiveFootUsageScore,
  applyBestReceiveBodyAngle,
  getFirstTouchModeLabel,
  resolveFirstTouchMode,
  getFirstTouchDirectionAngle,
  getFirstTouchDistance,
  clearAutoPilotReceiveMomentum,
  setAutoPilotReceiveMomentum,
  getAutoPilotReceiveMomentum,
  getAutoPilotReceiveMomentumAdjustment,
  getAutoPilotFirstActionAfterReceiveAdjustment,
  getAutoPilotReceiveFlowContext,
  getAutoPilotReceiveFlowAdjustment,
  getReceiveContinuationCarryTarget,
  buildAutoPilotReceiveContinuationCandidate,
  applyControlledFirstTouch,
  shouldUseAutoPilotActiveFirstTouch,
  getLiveBallFocusPoint,
  getSpacePassTargetPoint,
  getPlayerOrientationFocus,
  getActiveMovementTarget,
  isPlayerReservedForReceiveShape,
  applyNearbyBallOrientation,
  getPotentialPassReceiverAtTarget,
  getPassLaneRiskProfile,
  computePassLaneClarity,
  getGoalMouthTarget,
  getShotAngleQuality,
  getShotBlockRisk,
  getGoalkeeperTargetOpenness,
  computeShotLaneClarity,
  getShotWindowProfile,
  getDeterministicShotNoise,
  resolveExecutedShotTarget,
  getAttackDirectionSign,
  getAttackingDepth,
  getOpponentGoalCenter,
  getDepthZoneKey,
  getDepthZoneLabel,
  getLaneLabel,
  getGoldenZoneScore,
  isGoldenZone,
  getMedianNumber,
  getDepthQuantile,
  getOpponentLineDepthsForAttackingTeam,
  getAttackingGameSpaceProfile,
  getPitchSpaceProfile,
  getPitchThreatProfile,
  getOpponentPressureAtPoint,
  getNearestOpponentGapToPoint,
  getOpponentsBypassedByAction,
  getFootballSpacePriority,
  getActionSpaceValue,
  getTeamDensityAtPoint,
  getOpponentDensityAtPoint,
  getSpaceDominanceProfile,
  getAutoPilotSpaceDominanceAdjustment,
  getAutoPilotGameSpaceAdjustment,
  getAutoPilotSpatialDecisionAdjustment,
  getActionThreatGain,
  isPlayerFacingForward,
  getForwardFacingSpaceTwoContext,
  getAutoPilotSpaceTwoAdvantageAdjustment,
  getForwardProgressionWindow,
  getOpponentGoalSide,
  getGoalLineX,
  getGoalDirectionSign,
  isBetweenGoalPosts,
  getGoalNetDisplayPoint,
  resolveShotTarget,
  getOwnGoalCenter,
  getOpponentPenaltySpot,
  getSecondLastOpponentLineX,
  getOffsideInfo,
  isPassReceiverOffside,
  isWideChannel,
  isBylineZone,
  isInsideOpponentBox,
  isInsideOwnBox,
  isCutbackTarget,
  isGoalkeeper,
  getBallProfileDistanceRatio,
  getPitchSurfacePreset,
  getWeatherPreset,
  getDefensiveAggressionPreset,
  isAerialFlightStyle,
  getFlightStyleLabel,
  resolveBallCurveDirection,
  getBallTravelProgress,
  getBallTravelPoint,
  materializeBallProfile,
  getManualBallProfile,
  getDribbleRoleFamily,
  resolveAutoDribbleProfile,
  getNearestOpponentGapInCarryLane,
  getCarryLaneOpenSpaceScore,
  getCarryRunwayRoleCap,
  getCarryRunwayProfile,
  getRunwayCarryTarget,
  getBreakawayCarryTarget,
  getOpenGrassCarryContext,
  getQuadraticPoint,
  buildSampledCurvePath,
  getSampledPathPoint,
  buildDribbleCarryPath,
  getDribbleCarryPathPoint,
  setDribbleCarryPathForBall,
  getLiveDribbleSpeed,
  resolveAutoBallProfile,
  resolveBallActionProfile,
  resolveRecordedStepProfile,
  applyResolvedBallProfile,
  getBallProfileLabel,
  getDisplayedBallSpeed,
  getRemainingBallTravelTime,
  updateBallFlightHeight,
  getBallFlightControlFactor,
} = createGameSimulatorActionSpaceMetrics({
  angleBetween: angleBetween,
  angleDifference: angleDifference,
  autoBallProfiles: autoBallProfiles,
  autoDribbleProfiles: autoDribbleProfiles,
  ballRadiusMeters: ballRadiusMeters,
  blendAngles: blendAngles,
  buildPlayerIntelligenceProfile: buildPlayerIntelligenceProfile,
  clamp: clamp,
  clampToPitch: clampToPitch,
  cloneVector: cloneVector,
  computeTimeToCoverDistance: (...args) => computeTimeToCoverDistance(...args),
  defensiveAggressionPresets: defensiveAggressionPresets,
  distance: distance,
  firstTouchModes: firstTouchModes,
  getActionSpeed: (...args) => getActionSpeed(...args),
  getAutoPilotFlowContext: (...args) => getAutoPilotFlowContext(...args),
  getAutoPilotRoleStrength: (...args) => getAutoPilotRoleStrength(...args),
  getBallAwareBodyAngle: getBallAwareBodyAngle,
  getBallControlOffsetMeters: getBallControlOffsetMeters,
  getBallOwner: getBallOwner,
  getCompetitionPhysicalProfile: getCompetitionPhysicalProfile,
  getDefensiveAutopilotLineKey: (...args) => getDefensiveAutopilotLineKey(...args),
  getDefensivePhaseKey: (...args) => getDefensivePhaseKey(...args),
  getFootUsageScore: getFootUsageScore,
  getGoalkeeperForTeam: (...args) => getGoalkeeperForTeam(...args),
  getNearestOpponentGap: getNearestOpponentGap,
  getOffensiveAutopilotProfile: (...args) => getOffensiveAutopilotProfile(...args),
  getOffensiveRoleKey: (...args) => getOffensiveRoleKey(...args),
  getOtherTeamId: (...args) => getOtherTeamId(...args),
  getPitchLaneIndex: (...args) => getPitchLaneIndex(...args),
  getPitchLaneKey: (...args) => getPitchLaneKey(...args),
  getPlannedPossessionTeamId: (...args) => getPlannedPossessionTeamId(...args),
  getPlayerBallControlPoint: getPlayerBallControlPoint,
  getPlayerById: getPlayerById,
  getPlayerDecisionContext: getPlayerDecisionContext,
  getPlayerFacingAngle: getPlayerFacingAngle,
  getPlayerMagnetLabel: getPlayerMagnetLabel,
  getPlayerPressureLoad: getPlayerPressureLoad,
  getPlayerTendency: getPlayerTendency,
  getTeamAttackAngle: getTeamAttackAngle,
  getTeamSupportCountAroundPoint: (...args) => getTeamSupportCountAroundPoint(...args),
  getWideSideSign: (...args) => getWideSideSign(...args),
  isFrontLineRole: (...args) => isFrontLineRole(...args),
  isSupportRole: (...args) => isSupportRole(...args),
  keepSecurePossessionOnlyForOwner: (...args) => keepSecurePossessionOnlyForOwner(...args),
  lerp: lerp,
  moveTowards: moveTowards,
  normalize: normalize,
  normalizeAngle: normalizeAngle,
  pitch: pitch,
  pitchSurfacePresets: pitchSurfacePresets,
  playerRadiusMeters: playerRadiusMeters,
  projectPointOnSegmentWithRatio: projectPointOnSegmentWithRatio,
  rotatePlayerBodyTowardAngle: rotatePlayerBodyTowardAngle,
  setSecurePossessionAfterControlledTouch: (...args) => setSecurePossessionAfterControlledTouch(...args),
  subtract: subtract,
  teams: teams,
  uniquePrincipleLabels: (...args) => uniquePrincipleLabels(...args),
  vec: vec,
  weatherPresets: weatherPresets,
  getState,
});

const {
  applyBallExecutionProfile,
  getLooseBallClaimScore,
  getShotReboundClaimContext,
  getShotReboundClaimAdjustment,
  getBallContestControlScore,
  getAerialPresence,
  getAerialContestScore,
  getAerialFirstContactContext,
  getAerialFirstContactScore,
  getAerialDefensiveClearanceAngle,
  getAerialAttackingKnockdownAngle,
  getAerialControlScore,
  getBallDuelScore,
  clearSecurePossession,
  getBallWinEscapeTouch,
  applyBallWinEscapeTouch,
  setSecurePossessionAfterBallWin,
  getPossessionShieldOpponents,
  setSecurePossessionAfterControlledTouch,
  keepSecurePossessionOnlyForOwner,
  getSecurePossessionContext,
  getDribbleTackleCandidate,
  getDribbleFoulCandidate,
  completeDribbleFoulRestart,
  resolveDribbleDefensiveChallenge,
  resolveLooseBallClaim,
  connectBallToPlayerForNextAction,
  applyShotReboundControlTouch,
  keepBallPlayableForNextAction,
  createLooseBallSpill,
  resolveShotBlockCommitment,
  resolvePassTransitInterception,
  resolveAerialArrivalContest,
  shouldTriggerLandingBounce,
  startLandingBounceSkid,
  settleBallForNextAction,
} = createGameSimulatorBallResolutionEngine({
  angleBetween: angleBetween,
  angleDifference: angleDifference,
  applyCommittedSnapshot: applyCommittedSnapshot,
  applyControlledFirstTouch: applyControlledFirstTouch,
  blendAngles: blendAngles,
  captureSnapshot: captureSnapshot,
  clamp: clamp,
  clampToPitch: clampToPitch,
  clearAutoPilotReceiveMomentum: (...args) => clearAutoPilotReceiveMomentum(...args),
  cloneSnapshot: cloneSnapshot,
  cloneVector: cloneVector,
  completeLiveActionPlayersBeforeCommit: (...args) => completeLiveActionPlayersBeforeCommit(...args),
  computePassLaneClarity: computePassLaneClarity,
  computeShotLaneClarity: computeShotLaneClarity,
  computeTimeToCoverDistance: (...args) => computeTimeToCoverDistance(...args),
  configureBallTravelProfile: (...args) => configureBallTravelProfile(...args),
  distance: distance,
  finalizeCurrentActionStep: (...args) => finalizeCurrentActionStep(...args),
  getActionInitiator: getActionInitiator,
  getAttackDirectionSign: getAttackDirectionSign,
  getAutoPilotRoleStrength: (...args) => getAutoPilotRoleStrength(...args),
  getBallFlightControlFactor: getBallFlightControlFactor,
  getBallTravelProgress: getBallTravelProgress,
  getCoverShadowInfluence: getCoverShadowInfluence,
  getDefensiveAggressionPreset: getDefensiveAggressionPreset,
  getDistanceFromOwnGoal: (...args) => getDistanceFromOwnGoal(...args),
  getFirstTouchModeLabel: getFirstTouchModeLabel,
  getFootUsageScore: getFootUsageScore,
  getLiveDribbleSpeed: getLiveDribbleSpeed,
  getNearestOpponentGap: getNearestOpponentGap,
  getOffensiveRoleKey: (...args) => getOffensiveRoleKey(...args),
  getOpponentGoalCenter: getOpponentGoalCenter,
  getOpponentPenaltySpot: getOpponentPenaltySpot,
  getOrientationMovementProfile: getOrientationMovementProfile,
  getOtherTeamId: (...args) => getOtherTeamId(...args),
  getOwnGoalCenter: getOwnGoalCenter,
  getPitchSurfacePreset: getPitchSurfacePreset,
  getPitchThreatProfile: getPitchThreatProfile,
  getPlannedPossessionTeamId: (...args) => getPlannedPossessionTeamId(...args),
  getPlayerBallControlPoint: getPlayerBallControlPoint,
  getPlayerById: getPlayerById,
  getPlayerDecisionContext: getPlayerDecisionContext,
  getPlayerFacingAngle: getPlayerFacingAngle,
  getPlayerMagnetLabel: getPlayerMagnetLabel,
  getPlayerPositionForControlPoint: getPlayerPositionForControlPoint,
  getPlayerPressureLoad: getPlayerPressureLoad,
  getReceiveFootUsageScore: getReceiveFootUsageScore,
  getReceiveOrientationScore: getReceiveOrientationScore,
  getShotWindowProfile: getShotWindowProfile,
  getTeamAttackAngle: getTeamAttackAngle,
  getTeamAttackStyleKey: getTeamAttackStyleKey,
  getWeatherPreset: getWeatherPreset,
  isAerialFlightStyle: isAerialFlightStyle,
  isGoalkeeper: isGoalkeeper,
  isInsideOpponentBox: isInsideOpponentBox,
  isInsideOwnBox: isInsideOwnBox,
  isTransitionAttackStyle: (...args) => isTransitionAttackStyle(...args),
  lerp: lerp,
  logEvent: logEvent,
  normalize: normalize,
  normalizeAngle: normalizeAngle,
  pitch: pitch,
  placePlayerWithControlPoint: placePlayerWithControlPoint,
  playerRadiusMeters: playerRadiusMeters,
  projectPointOnSegment: projectPointOnSegment,
  projectPointOnSegmentWithRatio: projectPointOnSegmentWithRatio,
  queueNextSequenceStep: (...args) => queueNextSequenceStep(...args),
  rotatePlayerBodyToward: rotatePlayerBodyToward,
  scheduleAutoPilotContinuation: (...args) => scheduleAutoPilotContinuation(...args),
  setPiecePhaseProfiles: setPiecePhaseProfiles,
  shouldUseAutoPilotActiveFirstTouch: shouldUseAutoPilotActiveFirstTouch,
  teams: teams,
  ui: ui,
  getState,
});

const {
  getDefensiveAutopilotFocusPoint,
  getOffensiveAutopilotFocusPoint,
  isDefensiveAutopilotPlayer,
  isOffensiveAutopilotPlayer,
  isDefensiveDribblePresser,
  getLiveDefensiveDribblePressTarget,
  cloneDefensiveAutopilotIntents,
  getDefensiveAutoV2Intent,
  buildDefensiveAutoV2Intents,
  setReachableDefensiveAutoV2Target,
  applyDefensiveAutoV2BackLineRelationship,
  applyDefensiveAutoV2MidfieldPressCover,
  applyDefensiveAutoV2PressTether,
  applyDefensiveAutoV2AntiMagnetRelationships,
  applyDefensiveAutoV2RelationshipLayer,
  getDefensiveAutoV2FrameDt,
  moveDefensiveAutoV2Player,
  alignArrivedDefensiveAutopilotPlayers,
  completeLiveActionPlayersBeforeCommit,
  getActionSpeed,
  configureBallTravelProfile,
  getActionDistance,
  getRequestedActionMode,
  computeReachDistance,
  computeTimeToCoverDistance,
  shouldUseCurvedRecoveryRun,
  getCurvedRecoveryWaypoint,
  shouldUseOffBallCounterMovementRun,
  getOffBallCounterMovementWaypoint,
  buildMovementPath,
  getMovementPathPoint,
  getSnapshotPlayerMap,
  getRecordedStepEndSnapshot,
  getRecordedStepDuration,
  snapshotsMatch,
  createTransitionPlan,
  clampToCircle,
  getEditableRadius,
  getOtherTeamId,
  getPlannedPossessionTeamId,
  getDefendingDirectionSign,
  getDepthX,
  getDistanceFromOwnGoal,
  getOffensivePhaseKey,
  getOffensiveAutopilotProfile,
  getOffensiveRoleKey,
  getPitchLaneKey,
  getPitchLaneIndex,
  getAttackingThirdKey,
  getLaneCenterY,
  getSideLaneKeys,
  getRecentPossessionSteps,
  getRecordedStepPossessionTeamId,
  getPossessionRhythmContext,
  getLaneForSideSign,
  getWideOverlapPrincipleFit,
  getWideOverlapRunTarget,
  cloneOffensiveAutopilotIntents,
  cloneAutoV2DecisionTriggers,
  scanAutoV2DecisionTriggers,
  weightOffensiveAutoV2Intent,
  getOffensiveAutoV2Intent,
  setReachableOffensiveAutoV2Target,
  pickOffensiveAutoV2Player,
  applyOffensiveAutoV2RelationshipLayer,
  buildOffensiveAutoV2Intents,
  moveOffensiveAutoV2Player,
  getDefensivePhaseKey,
  getDefensiveAutopilotLineKey,
  getDefensiveAutopilotProfile,
  getDefensiveLineActionAdjustment,
  getDefensiveLineDistanceFromOwnGoal,
  getDefensiveLineX,
  getDefensiveLineWidth,
  getDefensiveLineCenterY,
  enforceDefensiveUnitCompactness,
  getDefensiveUnitGap,
  enforceDefensiveBlockGeometryLock,
  enforceDefensiveLineStaggering,
  enforceDefensiveLineChainSpacing,
  enforceDefensiveVerticalBlockConnections,
  enforceDefensiveMeasuredBlockEnvelope,
  enforceDefensiveCollectiveShiftCohesion,
  getDefensiveCompactLineIntegritySettings,
  enforceDefensiveCompactLineIntegrity,
  getDefensiveOffsideLineControlContext,
  enforceDefensiveOffsideLineControl,
  applyOffensiveAutopilotForCurrentAction,
  getDefensiveAutopilotGroupsForTeam,
  applyReachableDefensiveLineCohesion,
  applyDefensiveAutopilotForCurrentAction,
  applyAutopilotsForCurrentAction,
} = createGameSimulatorAutopilotLiveEngine({
  angleBetween: angleBetween,
  angleDifference: angleDifference,
  buildDefensiveAutopilotTargets: (...args) => buildDefensiveAutopilotTargets(...args),
  buildOffensiveAutopilotTargets: (...args) => buildOffensiveAutopilotTargets(...args),
  clamp: clamp,
  clampToPitch: clampToPitch,
  cloneVector: cloneVector,
  computePassLaneClarity: computePassLaneClarity,
  defensiveAutopilotProfiles: defensiveAutopilotProfiles,
  defensivePhaseProfiles: defensivePhaseProfiles,
  distance: distance,
  getActionInitiator: getActionInitiator,
  getActionOrigin: getActionOrigin,
  getActionSpaceValue: getActionSpaceValue,
  getAttackDirectionSign: getAttackDirectionSign,
  getAttackStyleRhythmProfile: getAttackStyleRhythmProfile,
  getAttackingGameSpaceProfile: getAttackingGameSpaceProfile,
  getAutoPilotRoleStrength: (...args) => getAutoPilotRoleStrength(...args),
  getBallNearSupportTriangleTarget: (...args) => getBallNearSupportTriangleTarget(...args),
  getCurrentActionDuration: getCurrentActionDuration,
  getDefensiveDribblePressTarget: (...args) => getDefensiveDribblePressTarget(...args),
  getDefensiveThreatResponse: (...args) => getDefensiveThreatResponse(...args),
  getDribblePressureReference: (...args) => getDribblePressureReference(...args),
  getFormationPositions: getFormationPositions,
  getKickoffDefensivePhaseKey: getKickoffDefensivePhaseKey,
  getOpponentPressureAtPoint: getOpponentPressureAtPoint,
  getOrientationTurnDelay: getOrientationTurnDelay,
  getOrientationMovementProfile: getOrientationMovementProfile,
  getPitchSurfacePreset: getPitchSurfacePreset,
  getPitchThreatProfile: getPitchThreatProfile,
  getPlayerBallControlPoint: getPlayerBallControlPoint,
  getPlayerById: getPlayerById,
  getPlayerDecisionContext: getPlayerDecisionContext,
  getPlayerFacingAngle: getPlayerFacingAngle,
  getPlayerMagnetLabel: getPlayerMagnetLabel,
  getPlayerPressureLoad: getPlayerPressureLoad,
  getProjectedActionDuration: getProjectedActionDuration,
  getSecondLastOpponentLineX: getSecondLastOpponentLineX,
  getTeamAttackAngle: getTeamAttackAngle,
  getTeamAttackStyleKey: getTeamAttackStyleKey,
  getTeamAttackStyleProfile: getTeamAttackStyleProfile,
  getTeamDefenseStyleKey: getTeamDefenseStyleKey,
  getTeamDefenseStyleProfile: getTeamDefenseStyleProfile,
  getWeatherPreset: getWeatherPreset,
  getWideSideSign: (...args) => getWideSideSign(...args),
  hasBallAction: hasBallAction,
  isAerialFlightStyle: isAerialFlightStyle,
  isGoalkeeper: isGoalkeeper,
  lerp: lerp,
  logEvent: logEvent,
  materializeBallProfile: materializeBallProfile,
  moveTowards: moveTowards,
  normalize: normalize,
  normalizeAngle: normalizeAngle,
  offensiveAutopilotProfiles: offensiveAutopilotProfiles,
  offensivePhaseProfiles: offensivePhaseProfiles,
  pitch: pitch,
  resolveBallCurveDirection: resolveBallCurveDirection,
  rotatePlayerBodyAlongMovement: rotatePlayerBodyAlongMovement,
  rotatePlayerBodyToward: rotatePlayerBodyToward,
  teamRosterOrder: teamRosterOrder,
  teams: teams,
  uniquePrincipleLabels: (...args) => uniquePrincipleLabels(...args),
  updateActionPlayers: (...args) => updateActionPlayers(...args),
  getState,
});

const {
  getAutoPilotPossessionStartIndex,
  getAutoPilotStyleIntentSequence,
  resolvePossessionRouteLanes,
  resolveOpeningVariationLanes,
  getRecentAutoPilotPlanMemory,
  getAutoPilotPlanRepeatPenalty,
  rememberAutoPilotPossessionPlan,
  invalidateAutoPilotPossessionPlan,
  createAutoPilotPossessionRoute,
  createAutoPilotOpeningVariation,
  getAutoPilotPossessionRouteStage,
  createAutoPilotPossessionPlan,
  getAutoPilotPossessionPlan,
  getAutoPilotPossessionIntentContext,
  getAutoPilotPossessionIntentFit,
  getAutoPilotPossessionIntentAdjustment,
  getAutoPilotTempoPhaseContext,
  getAutoPilotTempoPhaseAdjustment,
  getAutoPilotRhythmGovernorAdjustment,
  getAutoPilotOpeningVariationAdjustment,
  getOpponentBlockReadProfile,
  getAutoPilotOpponentBlockReadAdjustment,
  isLastStepKickoffResetForTeam,
  getRecentLaneRepeatCount,
  isFrontLineRole,
  isSupportRole,
  getStepReceiverRoleKey,
  getAutoPilotFlowContext,
  getLastAutoPrincipleSet,
  principleSetIncludes,
  isTransitionAttackStyle,
  getSecurePossessionSnapshotForTeam,
  getAutoPilotRegainContext,
  getAutoPilotCandidatePattern,
  getRecordedStepPattern,
  getRecordedStepActorIds,
  getAutoPilotPossessionLoopAdjustment,
  getAutoPilotCorridorTempoReleaseAdjustment,
  getAutoPilotCombinationChainContext,
  getAutoPilotCombinationChainAdjustment,
  getAutoPilotPassLaneDenialAdjustment,
  getAutoPilotCounterPressEscapeAdjustment,
  getAutoPilotRecoveryFirstActionContext,
  getAutoPilotRecoveryFirstActionAdjustment,
  getAutoPilotPostRecoveryPhaseContext,
  getAutoPilotPostRecoveryPhaseAdjustment,
  getAutoPilotTransitionNumbersContext,
  getAutoPilotTransitionNumbersAdjustment,
  getAutoPilotPressureEscapeContext,
  buildAutoPilotPressureTrapEscapeCandidate,
  getAutoPilotPressureEscapeAdjustment,
  getAutoPilotPatternDiversityAdjustment,
  getAutoPilotRepetitionPenalty,
  getAutoPilotFlowAdjustment,
  getAutoPilotCarryEndProductContext,
  getAutoPilotCarryEndProductAdjustment,
  getAutoPilotSpacingBonus,
  mergeIntentionWeights,
  getAutoPilotIntentionModel,
  getAutoPilotCandidatePrincipleMetrics,
  getUniversalFootballDecisionAdjustment,
  getAutoPilotVisionScanAdjustment,
  scoreAutoPilotCandidateByIntentions,
  getAutoPilotStylePrincipleWeights,
  uniquePrincipleLabels,
  getAutoPilotPrincipleAdjustment,
  getAutoPilotLaneRealityAdjustment,
  getAutoPilotCandidateReceiver,
  getAutoPilotRoleResponsibilityAdjustment,
  getAutoPilotLocalSuperiorityProfile,
  getAutoPilotLocalSuperiorityAdjustment,
  getReceiverAvailabilityProfile,
  getAutoPilotReceiverAvailabilityAdjustment,
  getAutoPilotReceivePressureTrapAdjustment,
  estimateAutoPilotCandidateDuration,
  getNextSupportSlotRoleFit,
  getAutoPilotNextSupportNetworkProfile,
  getAutoPilotNextSupportNetworkAdjustment,
  getAutoPilotSpaceLadderContext,
  getAutoPilotSpaceLadderAdjustment,
  getAutoPilotAdvantageRetentionContext,
  getAutoPilotAdvantageRetentionAdjustment,
  getAutoPilotEndProductUrgencyContext,
  getAutoPilotEndProductUrgencyAdjustment,
  getAutoPilotChanceHierarchyContext,
  getAutoPilotChanceHierarchyAdjustment,
  getAutoPilotLineBreakAdvantageAdjustment,
  getAutoPilotAdvantageLifecycleContext,
  getAutoPilotAdvantageLifecycleAdjustment,
  getWideSideSign,
  isWidePrincipleZone,
} = createGameSimulatorAutopilotDecisionEngine({
  angleBetween: angleBetween,
  angleDifference: angleDifference,
  ballRadiusMeters: ballRadiusMeters,
  buildPlayerIntelligenceProfile: buildPlayerIntelligenceProfile,
  chooseScoredCandidateWithVariation: chooseScoredCandidateWithVariation,
  chooseWeightedOption: chooseWeightedOption,
  clamp: clamp,
  clampToPitch: clampToPitch,
  cloneVector: cloneVector,
  computePassLaneClarity: computePassLaneClarity,
  computeTimeToCoverDistance: (...args) => computeTimeToCoverDistance(...args),
  distance: distance,
  getActionSpaceValue: getActionSpaceValue,
  getActionThreatGain: getActionThreatGain,
  getAttackDirectionSign: getAttackDirectionSign,
  getAttackStyleRhythmProfile: getAttackStyleRhythmProfile,
  getAttackingDepth: getAttackingDepth,
  getAttackingGameSpaceProfile: getAttackingGameSpaceProfile,
  getAttackingThirdKey: getAttackingThirdKey,
  getAutoPilotRoleStrength: (...args) => getAutoPilotRoleStrength(...args),
  getAutoPilotShotTarget: getAutoPilotShotTarget,
  getCarryLaneOpenSpaceScore: getCarryLaneOpenSpaceScore,
  getCoverShadowInfluence: getCoverShadowInfluence,
  getForwardFacingSpaceTwoContext: getForwardFacingSpaceTwoContext,
  getForwardProgressionWindow: getForwardProgressionWindow,
  getLaneForSideSign: getLaneForSideSign,
  getNearestOpponentGap: getNearestOpponentGap,
  getNearestOpponentGapInCarryLane: getNearestOpponentGapInCarryLane,
  getNearestOpponentGapToPoint: getNearestOpponentGapToPoint,
  getOffensiveRoleKey: (...args) => getOffensiveRoleKey(...args),
  getOpponentDensityAtPoint: getOpponentDensityAtPoint,
  getOpponentGoalCenter: getOpponentGoalCenter,
  getOpponentLineDepthsForAttackingTeam: getOpponentLineDepthsForAttackingTeam,
  getOpponentPressureAtPoint: getOpponentPressureAtPoint,
  getOtherTeamId: (...args) => getOtherTeamId(...args),
  getPassLaneRiskProfile: getPassLaneRiskProfile,
  getPitchLaneIndex: (...args) => getPitchLaneIndex(...args),
  getPitchLaneKey: (...args) => getPitchLaneKey(...args),
  getPitchThreatProfile: getPitchThreatProfile,
  getPlayerBallControlPoint: getPlayerBallControlPoint,
  getPlayerById: getPlayerById,
  getPlayerDecisionContext: getPlayerDecisionContext,
  getPlayerFacingAngle: getPlayerFacingAngle,
  getPlayerMagnetLabel: getPlayerMagnetLabel,
  getPlayerPressureLoad: getPlayerPressureLoad,
  getPlayerTendency: getPlayerTendency,
  getPossessionRhythmContext: (...args) => getPossessionRhythmContext(...args),
  getPotentialPassReceiverAtTarget: getPotentialPassReceiverAtTarget,
  getReceiveFootUsageScore: getReceiveFootUsageScore,
  getReceiveOrientationScore: getReceiveOrientationScore,
  getRecentPossessionSteps: (...args) => getRecentPossessionSteps(...args),
  getReceptionSupportTarget: (...args) => getReceptionSupportTarget(...args),
  getRecordedStepDuration: (...args) => getRecordedStepDuration(...args),
  getRecordedStepPossessionTeamId: (...args) => getRecordedStepPossessionTeamId(...args),
  getShotWindowProfile: getShotWindowProfile,
  getState,
  getTeamDensityAtPoint: getTeamDensityAtPoint,
  isGoalkeeper: isGoalkeeper,
  isPassReceiverOffside: isPassReceiverOffside,
  isPlayerFacingForward: isPlayerFacingForward,
  isWideChannel: isWideChannel,
  lerp: lerp,
  pitch: pitch,
  playerRadiusMeters: playerRadiusMeters,
  possessionRhythmDefaults: possessionRhythmDefaults,
  projectPointOnSegmentWithRatio: projectPointOnSegmentWithRatio,
  randomBetween: randomBetween,
  randomSign: randomSign,
  resolveBallActionProfile: resolveBallActionProfile,
  teams: teams,
});
const {
  getSameSideWideBacks,
  chooseWideOverlapRunner,
  getWideEntryPrincipleContext,
  getOffensiveActionPrinciple,
  getPlayerRoleModel,
  getOffensiveLaneY,
  shouldSkipOffensiveAutopilotPlayer,
  getOffensiveAutopilotTarget,
  chooseOffensiveAutopilotRunner,
  enforceOffensiveTargetSpacing,
  getOffensiveOnsideLineContext,
  enforceOffensiveOnsideLineAwareness,
  enforceOffensiveOccupationZones,
  getOffensiveStructureBalanceTarget,
  getStructureBalanceCandidates,
  enforceOffensiveStructureBalance,
  getFiveLaneOccupationSlotTarget,
  getFiveLaneOccupationCandidates,
  enforceOffensiveFiveLaneOccupation,
  getAutopilotTargetVariationRadius,
  applyAutopilotTargetVariation,
  getMovableAutopilotPlayerByRoles,
  getMovableAutopilotPlayerByRolesOnSide,
  setAutopilotPrincipleTarget,
  getSupportUnderBallTarget,
  getThirdManRunnerTarget,
  getBoxOccupationTarget,
  getShotReboundGeometryContext,
  getShotReboundTarget,
  applyShotReboundPrincipleTargets,
  getSecondBallAnticipationContext,
  getOffensiveSecondBallAnticipationTarget,
  applyOffensiveSecondBallAnticipationTargets,
  applyCornerDeliveryPrincipleTargets,
  getGoalkeeperBuildOutSupportTarget,
  applyGoalkeeperBuildOutPrincipleTargets,
  applyBoxOccupationPrincipleTargets,
  getTimedBoxArrivalContext,
  getTimedBoxArrivalTarget,
  chooseTimedBoxArrivalPlayer,
  applyTimedFinalThirdBoxArrivals,
  getAttackingBoxOccupationChainContext,
  getAttackingBoxOccupationChainTarget,
  applyAttackingBoxOccupationChainTargets,
  getTransitionAttackTarget,
  applyTransitionAttackPrincipleTargets,
  applyBetweenLinesPrincipleTargets,
  getReceptionSupportTarget,
  applyReceptionSupportPrincipleTargets,
  getOpenGrassCarrySupportTarget,
  applyOpenGrassCarrySupportTargets,
  getBallNearSupportTriangleTarget,
  applyBallNearSupportTriangleTargets,
  getTargetLocalSuperiorityProfile,
  getLocalSuperioritySupportTarget,
  applyLocalSuperioritySupportTargets,
  getOffensivePassingGeometryContext,
  getOffensivePassingGeometryTarget,
  applyOffensivePassingGeometryTargets,
  getLooseBallRecoverySupportTarget,
  applyLooseBallRecoverySupportTargets,
  getPostRecoveryAttackSupportContext,
  getPostRecoveryAttackSupportTarget,
  applyPostRecoveryAttackSupportTargets,
  getOffensiveRestDefenceNetContext,
  getOffensiveRestDefenceNetTarget,
  applyOffensiveRestDefenceNetTargets,
  getPressResistanceEscapeTarget,
  applyPressResistanceEscapeSupportTargets,
  getPressEscapeContinuationTarget,
  applyPressEscapeContinuationTargets,
  getSwitchLandingAttackContext,
  getSwitchLandingAttackTarget,
  applySwitchLandingAttackTargets,
  getBlindsideChannelRunContext,
  getBlindsideChannelRunTarget,
  chooseBlindsideChannelRunner,
  applyBlindsideChannelRunTargets,
  getPasserContinuationTarget,
  applyPasserContinuationTargets,
  applyThirdManChainSupportTargets,
  getSpaceTwoForwardFacingTarget,
  applySpaceTwoForwardFacingTargets,
  getSpaceTwoContinuationContext,
  getSpaceTwoContinuationTarget,
  applySpaceTwoContinuationTargets,
  getDepthPoint,
  applyGenerativePrincipleSupportTargets,
  getHighValueAttackTarget,
  applyHighValueSpacePrincipleTargets,
  getFormationIdentityTarget,
  applyFormationIdentityPrincipleTargets,
  getPossessionRouteOccupationTarget,
  applyPossessionRoutePrincipleTargets,
  getPositionalPlayOccupationTarget,
  applyPositionalPlayOccupationTargets,
  getOpponentBlockOccupationTarget,
  applyOpponentBlockResponsiveTargets,
  getGameSpaceOffBallTarget,
  applyGameSpaceOffBallPrincipleTargets,
} = createGameSimulatorAutopilotOffballTargets({
  addPointNoise: addPointNoise,
  clamp: clamp,
  clampToPitch: clampToPitch,
  cloneVector: cloneVector,
  computeTimeToCoverDistance: (...args) => computeTimeToCoverDistance(...args),
  distance: distance,
  gameRoleProfiles: gameRoleProfiles,
  getActionSpaceValue: getActionSpaceValue,
  getAttackDirectionSign: getAttackDirectionSign,
  getAttackingDepth: getAttackingDepth,
  getAttackingGameSpaceProfile: getAttackingGameSpaceProfile,
  getAutoPilotPossessionPlan: getAutoPilotPossessionPlan,
  getAutoPilotPossessionRouteStage: getAutoPilotPossessionRouteStage,
  getAutoPilotRoleStrength: (...args) => getAutoPilotRoleStrength(...args),
  getCarryLaneOpenSpaceScore: getCarryLaneOpenSpaceScore,
  getDefensiveAutopilotLineKey: (...args) => getDefensiveAutopilotLineKey(...args),
  getDepthX: getDepthX,
  getFormationPositions: getFormationPositions,
  getLaneCenterY: getLaneCenterY,
  getNearestOpponentGapInCarryLane: getNearestOpponentGapInCarryLane,
  getNearestOpponentGapToPoint: getNearestOpponentGapToPoint,
  getOffensiveAutopilotProfile: (...args) => getOffensiveAutopilotProfile(...args),
  getOffensivePhaseKey: getOffensivePhaseKey,
  getOffensiveRoleKey: (...args) => getOffensiveRoleKey(...args),
  getOpponentBlockReadProfile: getOpponentBlockReadProfile,
  getOpponentGoalCenter: getOpponentGoalCenter,
  getOpponentLineDepthsForAttackingTeam: getOpponentLineDepthsForAttackingTeam,
  getOpponentPenaltySpot: getOpponentPenaltySpot,
  getOpponentPressureAtPoint: getOpponentPressureAtPoint,
  getPitchLaneIndex: (...args) => getPitchLaneIndex(...args),
  getPitchLaneKey: (...args) => getPitchLaneKey(...args),
  getPitchSpaceProfile: getPitchSpaceProfile,
  getPitchThreatProfile: getPitchThreatProfile,
  getPlayerBallControlPoint: getPlayerBallControlPoint,
  getPlayerById: getPlayerById,
  getPlayerMagnetLabel: getPlayerMagnetLabel,
  getPlayerPressureLoad: getPlayerPressureLoad,
  getPlayerTendency: getPlayerTendency,
  getPossessionRhythmContext: (...args) => getPossessionRhythmContext(...args),
  getRecordedStepDuration: (...args) => getRecordedStepDuration(...args),
  getRecordedStepPattern: getRecordedStepPattern,
  getRecordedStepPossessionTeamId: (...args) => getRecordedStepPossessionTeamId(...args),
  getSecondLastOpponentLineX: getSecondLastOpponentLineX,
  getSecurePossessionSnapshotForTeam: getSecurePossessionSnapshotForTeam,
  getShotWindowProfile: getShotWindowProfile,
  getSideLaneKeys: (...args) => getSideLaneKeys(...args),
  getState,
  getWideOverlapPrincipleFit: (...args) => getWideOverlapPrincipleFit(...args),
  getWideOverlapRunTarget: (...args) => getWideOverlapRunTarget(...args),
  getWideSideSign: getWideSideSign,
  isAerialFlightStyle: isAerialFlightStyle,
  isFrontLineRole: isFrontLineRole,
  isGoalkeeper: isGoalkeeper,
  isTransitionAttackStyle: isTransitionAttackStyle,
  isWideChannel: isWideChannel,
  isWidePrincipleZone: isWidePrincipleZone,
  lerp: lerp,
  pitch: pitch,
  resolveBallActionProfile: resolveBallActionProfile,
  teamRosterOrder: teamRosterOrder,
  teams: teams,
  uniquePrincipleLabels: uniquePrincipleLabels,
});
const {
  getAutoPilotShotTarget,
  getAutoPilotBoxTarget,
  getCornerDeliveryTarget,
  chooseCornerDeliveryRunner,
  getFreeKickDeliveryTarget,
  chooseFreeKickShortReceiver,
  getAutoPilotDribbleTarget,
  getTeamSupportCountAroundPoint,
  getGoalkeeperDistributionPressure,
  getGoalkeeperDirectReleaseTarget,
  buildAutoPilotGoalkeeperDistributionCandidate,
  buildAutoPilotShotCandidate,
  buildAutoPilotKickoffCandidate,
  getLastKickoffOpeningProfile,
  getKickoffOpeningCandidateFit,
  buildAutoPilotPostKickoffResetCandidate,
  buildAutoPilotCornerCandidate,
  buildAutoPilotThrowInCandidate,
  buildAutoPilotPenaltyCandidate,
  buildAutoPilotFreeKickCandidate,
  buildAutoPilotRegainReleaseCandidate,
  getPressedRegainExitVector,
  buildAutoPilotPressedRegainExitCandidate,
  buildAutoPilotDangerZoneEscapeCandidate,
  buildAutoPilotBoxDeliveryCandidate,
  getFinalThirdCombinationVariants,
  buildAutoPilotFinalThirdCombinationCandidate,
  buildAutoPilotWideOverlapCandidate,
  getLastSwitchLandingActionContext,
  buildAutoPilotSwitchLandingContinuationCandidate,
  buildAutoPilotThroughBallCandidate,
  buildAutoPilotBetweenLinesCandidate,
  buildAutoPilotPassCandidates,
  buildAutoPilotDribbleCandidate,
} = createGameSimulatorAutopilotCandidates({
  angleBetween: angleBetween,
  chooseScoredCandidateWithVariation: chooseScoredCandidateWithVariation,
  chooseWideOverlapRunner: chooseWideOverlapRunner,
  clamp: clamp,
  clampToPitch: clampToPitch,
  computePassLaneClarity: computePassLaneClarity,
  computeTimeToCoverDistance: (...args) => computeTimeToCoverDistance(...args),
  distance: distance,
  getActionSpaceValue: getActionSpaceValue,
  getActionThreatGain: getActionThreatGain,
  getAttackDirectionSign: getAttackDirectionSign,
  getAttackingDepth: getAttackingDepth,
  getAutoPilotCarryEndProductContext: getAutoPilotCarryEndProductContext,
  getAutoPilotFlowContext: getAutoPilotFlowContext,
  getAutoPilotRegainContext: getAutoPilotRegainContext,
  getAutoPilotRoleStrength: (...args) => getAutoPilotRoleStrength(...args),
  getBreakawayCarryTarget: getBreakawayCarryTarget,
  getCarryLaneOpenSpaceScore: getCarryLaneOpenSpaceScore,
  getCarryRunwayProfile: getCarryRunwayProfile,
  getDepthPoint: getDepthPoint,
  getDepthX: getDepthX,
  getDistanceFromOwnGoal: (...args) => getDistanceFromOwnGoal(...args),
  getFootUsageScore: getFootUsageScore,
  getForwardFacingSpaceTwoContext: getForwardFacingSpaceTwoContext,
  getForwardProgressionWindow: getForwardProgressionWindow,
  getGoalMouthTarget: getGoalMouthTarget,
  getGoalkeeperTargetOpenness: getGoalkeeperTargetOpenness,
  getHighValueAttackTarget: getHighValueAttackTarget,
  getKickoffSupportId: getKickoffSupportId,
  getNearestOpponentGapInCarryLane: getNearestOpponentGapInCarryLane,
  getOffensiveAutopilotProfile: (...args) => getOffensiveAutopilotProfile(...args),
  getOffensiveRoleKey: (...args) => getOffensiveRoleKey(...args),
  getOpenGrassCarryContext: getOpenGrassCarryContext,
  getOpponentGoalCenter: getOpponentGoalCenter,
  getOpponentPenaltySpot: getOpponentPenaltySpot,
  getOpponentPressureAtPoint: getOpponentPressureAtPoint,
  getPitchLaneIndex: (...args) => getPitchLaneIndex(...args),
  getPitchLaneKey: (...args) => getPitchLaneKey(...args),
  getPitchThreatProfile: getPitchThreatProfile,
  getPlayerBallControlPoint: getPlayerBallControlPoint,
  getPlayerById: getPlayerById,
  getPlayerMagnetLabel: getPlayerMagnetLabel,
  getPlayerPressureLoad: getPlayerPressureLoad,
  getPlayerTendency: getPlayerTendency,
  getPossessionRhythmContext: (...args) => getPossessionRhythmContext(...args),
  getRecentPossessionSteps: (...args) => getRecentPossessionSteps(...args),
  getRecordedStepDuration: (...args) => getRecordedStepDuration(...args),
  getRunwayCarryTarget: getRunwayCarryTarget,
  getShotAngleQuality: getShotAngleQuality,
  getShotWindowProfile: getShotWindowProfile,
  getState,
  getSwitchLandingAttackTarget: getSwitchLandingAttackTarget,
  getWideEntryPrincipleContext: getWideEntryPrincipleContext,
  getWideSideSign: getWideSideSign,
  isBylineZone: isBylineZone,
  isGoalkeeper: isGoalkeeper,
  isInsideOpponentBox: isInsideOpponentBox,
  isInsideOwnBox: isInsideOwnBox,
  isLastStepKickoffResetForTeam: isLastStepKickoffResetForTeam,
  isPassReceiverOffside: isPassReceiverOffside,
  isTransitionAttackStyle: isTransitionAttackStyle,
  isWideChannel: isWideChannel,
  isWidePrincipleZone: isWidePrincipleZone,
  kickoffOpeningProfiles: kickoffOpeningProfiles,
  lerp: lerp,
  normalize: normalize,
  pitch: pitch,
  resolveBallActionProfile: resolveBallActionProfile,
  resolveShotTarget: resolveShotTarget,
  teams: teams,
  uniquePrincipleLabels: uniquePrincipleLabels,
  win: win,
});
const {
  getDefensiveBackLineHandoverContext,
  applyDefensiveBackLineHandoverTargets,
  getDefensiveLineActionLabels,
  getDefensiveGoalkeeperTarget,
  getDefensiveGoalkeeperSweeperContext,
  applyDefensiveGoalkeeperSweeperTarget,
  getDefensiveGoalkeeperShotSetContext,
  getDefensiveGoalkeeperShotSetTarget,
  applyDefensiveGoalkeeperShotSetTarget,
  chooseDefensiveAutopilotPresser,
  getDefensivePressTarget,
  getDefensiveAngledPressTarget,
  applyDefensivePresserAngleTarget,
  getGoalkeeperBuildOutPressContext,
  pickDefensiveAutopilotPlayer,
  getGoalkeeperBuildOutPressTarget,
  applyGoalkeeperBuildOutPressTargets,
  getDefensiveThreatResponse,
  getDefensivePrioritySpacePoint,
  pickDefensiveProtectionPlayer,
  applyDefensivePrioritySpaceProtectionTargets,
  getDefensiveCornerContext,
  getDefensiveCornerTarget,
  applyDefensiveCornerSetPieceTargets,
  getRestartActionMeta,
  getDefensiveFreeKickContext,
  getFreeKickWallTarget,
  getDefensiveFreeKickTarget,
  applyDefensiveFreeKickSetPieceTargets,
  getDefensivePenaltyContext,
  getDefensivePenaltyTarget,
  applyDefensivePenaltySetPieceTargets,
  getDefensiveThrowInContext,
  getDefensiveThrowInTarget,
  applyDefensiveThrowInSetPieceTargets,
  getNegativeTransitionContext,
  getNegativeTransitionTarget,
  getNegativeTransitionOutletOptions,
  applyNegativeTransitionDefensiveTargets,
  getDefensiveLooseBallRecoveryTrapContext,
  getDefensiveLooseBallRecoveryTrapTarget,
  applyDefensiveLooseBallRecoveryTrapTargets,
  getDefensiveOpenPlayTriggerContext,
  getDefensiveOpenPlayTriggerTarget,
  applyDefensiveOpenPlayTriggerTargets,
  getDefensiveReceptionTrapContext,
  getDefensiveReceptionTrapTarget,
  applyDefensiveReceptionTrapTargets,
  getDefensiveReceiveContinuationNextPoint,
  getDefensiveReceiveContinuationContext,
  getDefensiveReceiveContinuationTarget,
  applyDefensiveReceiveContinuationTargets,
  getDefensiveRouteAnticipationContext,
  getDefensiveRouteAnticipationTarget,
  applyDefensiveRouteAnticipationTargets,
  getDefensiveSwitchRecoveryContext,
  getDefensiveSwitchRecoveryTarget,
  applyDefensiveSwitchRecoveryTargets,
  getDefensiveSwitchLandingLockContext,
  getDefensiveSwitchLandingLockTarget,
  applyDefensiveSwitchLandingLockTargets,
  getDefensiveGameSpaceResponseContext,
  getDefensiveGameSpaceResponseTarget,
  applyDefensiveGameSpaceResponseTargets,
  getDefensiveRunnerThreats,
  getDefensiveRunnerTrackingTarget,
  applyDefensiveRunnerTrackingTargets,
  getDribblePressureReference,
  chooseDefensiveDribblePresser,
  getDefensiveDribblePressTarget,
  getDefensiveCarryContainmentContext,
  getDefensiveCarryContainmentTarget,
  applyDefensiveCarryContainmentTargets,
  getDefensivePressureCoverContext,
  getDefensivePressureCoverTarget,
  applyDefensivePressureCoverBalanceTargets,
  getDefensivePressChainSupportContext,
  getDefensivePressChainSupportTarget,
  applyDefensivePressChainSupportTargets,
  getActualLocalSuperiorityProfile,
  getDefensiveLocalOverloadContext,
  getDefensiveLocalOverloadTarget,
  applyDefensiveLocalOverloadResponseTargets,
  getDefensivePostRecoveryResponseContext,
  getDefensivePostRecoveryResponseTarget,
  getDefensivePostRecoveryOutletOptions,
  applyDefensivePostRecoveryResponseTargets,
  getDefensivePassLaneDenialContext,
  getDefensivePassLaneDenialTarget,
  applyDefensivePassLaneDenialTargets,
  getDefensiveCentralAccessGateContext,
  getDefensiveCentralAccessGateTarget,
  applyDefensiveCentralAccessGateTargets,
  getDefensiveChanceDenialContext,
  getDefensiveChanceDenialTarget,
  applyDefensiveChanceDenialTargets,
  getDefensiveBoxDeliveryChainContext,
  getDefensiveBoxDeliveryChainTarget,
  applyDefensiveBoxDeliveryChainTargets,
  getDefensiveLineBreakAdvantageContext,
  getDefensiveLineBreakAdvantageTarget,
  applyDefensiveLineBreakAdvantageCollapseTargets,
  getDefensiveEmergencyCoverContext,
  getDefensiveEmergencyCoverTarget,
  applyDefensiveEmergencyCoverTargets,
  getDefensiveSecondBallAnticipationTarget,
  applyDefensiveSecondBallAnticipationTargets,
} = createGameSimulatorAutopilotDefensiveTargets({
  clamp: clamp,
  clampToPitch: clampToPitch,
  cloneRestartPhase: cloneRestartPhase,
  cloneVector: cloneVector,
  computePassLaneClarity: computePassLaneClarity,
  computeTimeToCoverDistance: (...args) => computeTimeToCoverDistance(...args),
  distance: distance,
  getActionSpaceValue: getActionSpaceValue,
  getAttackDirectionSign: getAttackDirectionSign,
  getAttackingDepth: getAttackingDepth,
  getAttackingGameSpaceProfile: getAttackingGameSpaceProfile,
  getAutoPilotPossessionRouteStage: getAutoPilotPossessionRouteStage,
  getAutoPilotShotTarget: getAutoPilotShotTarget,
  getBallTravelProgress: getBallTravelProgress,
  getCornerKickSpot: getCornerKickSpot,
  getDefendingDirectionSign: getDefendingDirectionSign,
  getDefensiveAutopilotLineKey: (...args) => getDefensiveAutopilotLineKey(...args),
  getDefensiveAutopilotProfile: getDefensiveAutopilotProfile,
  getDefensiveLineDistanceFromOwnGoal: (...args) => getDefensiveLineDistanceFromOwnGoal(...args),
  getDefensiveUnitGap: (...args) => getDefensiveUnitGap(...args),
  getDepthX: getDepthX,
  getDistanceFromOwnGoal: (...args) => getDistanceFromOwnGoal(...args),
  getLaneCenterY: getLaneCenterY,
  getOffensiveAutopilotProfile: (...args) => getOffensiveAutopilotProfile(...args),
  getOffensiveRoleKey: (...args) => getOffensiveRoleKey(...args),
  getOpponentGoalCenter: getOpponentGoalCenter,
  getOpponentPenaltySpot: getOpponentPenaltySpot,
  getOpponentPressureAtPoint: getOpponentPressureAtPoint,
  getOtherTeamId: (...args) => getOtherTeamId(...args),
  getOwnGoalCenter: getOwnGoalCenter,
  getPitchLaneIndex: (...args) => getPitchLaneIndex(...args),
  getPitchLaneKey: (...args) => getPitchLaneKey(...args),
  getPitchThreatProfile: getPitchThreatProfile,
  getPlannedPossessionTeamId: (...args) => getPlannedPossessionTeamId(...args),
  getPlayerById: getPlayerById,
  getPlayerDecisionContext: getPlayerDecisionContext,
  getPlayerMagnetLabel: getPlayerMagnetLabel,
  getPlayerPressureLoad: getPlayerPressureLoad,
  getPossessionRhythmContext: (...args) => getPossessionRhythmContext(...args),
  getRecentPossessionSteps: (...args) => getRecentPossessionSteps(...args),
  getRecordedStepDuration: (...args) => getRecordedStepDuration(...args),
  getRecordedStepPattern: getRecordedStepPattern,
  getRecordedStepPossessionTeamId: (...args) => getRecordedStepPossessionTeamId(...args),
  getSecondBallAnticipationContext: getSecondBallAnticipationContext,
  getShotAngleQuality: getShotAngleQuality,
  getShotWindowProfile: getShotWindowProfile,
  getSnapshotPlayerMap: getSnapshotPlayerMap,
  getTeamDefenseStyleKey: getTeamDefenseStyleKey,
  getTeamDefenseStyleProfile: getTeamDefenseStyleProfile,
  getTeamSupportCountAroundPoint: getTeamSupportCountAroundPoint,
  getWideSideSign: getWideSideSign,
  isAerialFlightStyle: isAerialFlightStyle,
  isGoalkeeper: isGoalkeeper,
  isTransitionAttackStyle: isTransitionAttackStyle,
  isWideChannel: isWideChannel,
  isWidePrincipleZone: isWidePrincipleZone,
  lerp: lerp,
  moveTowards: moveTowards,
  normalize: normalize,
  pitch: pitch,
  playerRadiusMeters: playerRadiusMeters,
  projectPointOnSegmentWithRatio: projectPointOnSegmentWithRatio,
  teams: teams,
  uniquePrincipleLabels: uniquePrincipleLabels,
  vec: vec,
  getState,
});

const {
  buildOffensiveAutopilotTargets,
  buildDefensiveAutopilotTargets,
  chooseAutoPilotNextAction,
} = createGameSimulatorAutopilotTargets({
  applyAttackingBoxOccupationChainTargets: applyAttackingBoxOccupationChainTargets,
  applyAutopilotTargetVariation: applyAutopilotTargetVariation,
  applyBallNearSupportTriangleTargets: applyBallNearSupportTriangleTargets,
  applyBlindsideChannelRunTargets: applyBlindsideChannelRunTargets,
  applyDefensiveBackLineHandoverTargets: applyDefensiveBackLineHandoverTargets,
  applyDefensiveBoxDeliveryChainTargets: applyDefensiveBoxDeliveryChainTargets,
  applyDefensiveCarryContainmentTargets: applyDefensiveCarryContainmentTargets,
  applyDefensiveCentralAccessGateTargets: applyDefensiveCentralAccessGateTargets,
  applyDefensiveChanceDenialTargets: applyDefensiveChanceDenialTargets,
  applyDefensiveCornerSetPieceTargets: applyDefensiveCornerSetPieceTargets,
  applyDefensiveEmergencyCoverTargets: applyDefensiveEmergencyCoverTargets,
  applyDefensiveFreeKickSetPieceTargets: applyDefensiveFreeKickSetPieceTargets,
  applyDefensiveGameSpaceResponseTargets: applyDefensiveGameSpaceResponseTargets,
  applyDefensiveGoalkeeperShotSetTarget: applyDefensiveGoalkeeperShotSetTarget,
  applyDefensiveGoalkeeperSweeperTarget: applyDefensiveGoalkeeperSweeperTarget,
  applyDefensiveLineBreakAdvantageCollapseTargets: applyDefensiveLineBreakAdvantageCollapseTargets,
  applyDefensiveLocalOverloadResponseTargets: applyDefensiveLocalOverloadResponseTargets,
  applyDefensiveLooseBallRecoveryTrapTargets: applyDefensiveLooseBallRecoveryTrapTargets,
  applyDefensiveOpenPlayTriggerTargets: applyDefensiveOpenPlayTriggerTargets,
  applyDefensivePassLaneDenialTargets: applyDefensivePassLaneDenialTargets,
  applyDefensivePenaltySetPieceTargets: applyDefensivePenaltySetPieceTargets,
  applyDefensivePostRecoveryResponseTargets: applyDefensivePostRecoveryResponseTargets,
  applyDefensivePressChainSupportTargets: applyDefensivePressChainSupportTargets,
  applyDefensivePresserAngleTarget: applyDefensivePresserAngleTarget,
  applyDefensivePressureCoverBalanceTargets: applyDefensivePressureCoverBalanceTargets,
  applyDefensivePrioritySpaceProtectionTargets: applyDefensivePrioritySpaceProtectionTargets,
  applyDefensiveReceiveContinuationTargets: applyDefensiveReceiveContinuationTargets,
  applyDefensiveReceptionTrapTargets: applyDefensiveReceptionTrapTargets,
  applyDefensiveRouteAnticipationTargets: applyDefensiveRouteAnticipationTargets,
  applyDefensiveRunnerTrackingTargets: applyDefensiveRunnerTrackingTargets,
  applyDefensiveSecondBallAnticipationTargets: applyDefensiveSecondBallAnticipationTargets,
  applyDefensiveSwitchLandingLockTargets: applyDefensiveSwitchLandingLockTargets,
  applyDefensiveSwitchRecoveryTargets: applyDefensiveSwitchRecoveryTargets,
  applyDefensiveThrowInSetPieceTargets: applyDefensiveThrowInSetPieceTargets,
  applyGenerativePrincipleSupportTargets: applyGenerativePrincipleSupportTargets,
  applyGoalkeeperBuildOutPressTargets: applyGoalkeeperBuildOutPressTargets,
  applyLocalSuperioritySupportTargets: applyLocalSuperioritySupportTargets,
  applyLooseBallRecoverySupportTargets: applyLooseBallRecoverySupportTargets,
  applyNegativeTransitionDefensiveTargets: applyNegativeTransitionDefensiveTargets,
  applyOffensivePassingGeometryTargets: applyOffensivePassingGeometryTargets,
  applyOffensiveRestDefenceNetTargets: applyOffensiveRestDefenceNetTargets,
  applyOffensiveSecondBallAnticipationTargets: applyOffensiveSecondBallAnticipationTargets,
  applyPasserContinuationTargets: applyPasserContinuationTargets,
  applyPostRecoveryAttackSupportTargets: applyPostRecoveryAttackSupportTargets,
  applyPressEscapeContinuationTargets: applyPressEscapeContinuationTargets,
  applyPressResistanceEscapeSupportTargets: applyPressResistanceEscapeSupportTargets,
  applySpaceTwoContinuationTargets: applySpaceTwoContinuationTargets,
  applySpaceTwoForwardFacingTargets: applySpaceTwoForwardFacingTargets,
  applySwitchLandingAttackTargets: applySwitchLandingAttackTargets,
  applyThirdManChainSupportTargets: applyThirdManChainSupportTargets,
  applyTimedFinalThirdBoxArrivals: applyTimedFinalThirdBoxArrivals,
  buildAutoPilotBetweenLinesCandidate: buildAutoPilotBetweenLinesCandidate,
  buildAutoPilotBoxDeliveryCandidate: buildAutoPilotBoxDeliveryCandidate,
  buildAutoPilotCornerCandidate: buildAutoPilotCornerCandidate,
  buildAutoPilotDangerZoneEscapeCandidate: buildAutoPilotDangerZoneEscapeCandidate,
  buildAutoPilotDribbleCandidate: buildAutoPilotDribbleCandidate,
  buildAutoPilotFinalThirdCombinationCandidate: buildAutoPilotFinalThirdCombinationCandidate,
  buildAutoPilotFreeKickCandidate: buildAutoPilotFreeKickCandidate,
  buildAutoPilotGoalkeeperDistributionCandidate: buildAutoPilotGoalkeeperDistributionCandidate,
  buildAutoPilotKickoffCandidate: buildAutoPilotKickoffCandidate,
  buildAutoPilotPassCandidates: buildAutoPilotPassCandidates,
  buildAutoPilotPenaltyCandidate: buildAutoPilotPenaltyCandidate,
  buildAutoPilotPostKickoffResetCandidate: buildAutoPilotPostKickoffResetCandidate,
  buildAutoPilotPressedRegainExitCandidate: buildAutoPilotPressedRegainExitCandidate,
  buildAutoPilotPressureTrapEscapeCandidate: buildAutoPilotPressureTrapEscapeCandidate,
  buildAutoPilotReceiveContinuationCandidate: buildAutoPilotReceiveContinuationCandidate,
  buildAutoPilotRegainReleaseCandidate: buildAutoPilotRegainReleaseCandidate,
  buildAutoPilotShotCandidate: buildAutoPilotShotCandidate,
  buildAutoPilotSwitchLandingContinuationCandidate: buildAutoPilotSwitchLandingContinuationCandidate,
  buildAutoPilotThroughBallCandidate: buildAutoPilotThroughBallCandidate,
  buildAutoPilotThrowInCandidate: buildAutoPilotThrowInCandidate,
  buildAutoPilotWideOverlapCandidate: buildAutoPilotWideOverlapCandidate,
  chooseDefensiveAutopilotPresser: chooseDefensiveAutopilotPresser,
  chooseDefensiveDribblePresser: chooseDefensiveDribblePresser,
  chooseOffensiveAutopilotRunner: chooseOffensiveAutopilotRunner,
  chooseScoredCandidateWithVariation: chooseScoredCandidateWithVariation,
  clamp: clamp,
  clampToPitch: clampToPitch,
  cloneVector: cloneVector,
  enforceDefensiveBlockGeometryLock: (...args) => enforceDefensiveBlockGeometryLock(...args),
  enforceDefensiveCollectiveShiftCohesion: (...args) => enforceDefensiveCollectiveShiftCohesion(...args),
  enforceDefensiveCompactLineIntegrity: (...args) => enforceDefensiveCompactLineIntegrity(...args),
  enforceDefensiveLineChainSpacing: (...args) => enforceDefensiveLineChainSpacing(...args),
  enforceDefensiveLineStaggering: (...args) => enforceDefensiveLineStaggering(...args),
  enforceDefensiveMeasuredBlockEnvelope: (...args) => enforceDefensiveMeasuredBlockEnvelope(...args),
  enforceDefensiveOffsideLineControl: (...args) => enforceDefensiveOffsideLineControl(...args),
  enforceDefensiveUnitCompactness: enforceDefensiveUnitCompactness,
  enforceDefensiveVerticalBlockConnections: (...args) => enforceDefensiveVerticalBlockConnections(...args),
  enforceOffensiveFiveLaneOccupation: enforceOffensiveFiveLaneOccupation,
  enforceOffensiveOccupationZones: enforceOffensiveOccupationZones,
  enforceOffensiveOnsideLineAwareness: enforceOffensiveOnsideLineAwareness,
  enforceOffensiveStructureBalance: enforceOffensiveStructureBalance,
  enforceOffensiveTargetSpacing: enforceOffensiveTargetSpacing,
  getAutoPilotAdvantageLifecycleAdjustment: getAutoPilotAdvantageLifecycleAdjustment,
  getAutoPilotAdvantageRetentionAdjustment: getAutoPilotAdvantageRetentionAdjustment,
  getAutoPilotCarryEndProductAdjustment: getAutoPilotCarryEndProductAdjustment,
  getAutoPilotChanceHierarchyAdjustment: getAutoPilotChanceHierarchyAdjustment,
  getAutoPilotCombinationChainAdjustment: getAutoPilotCombinationChainAdjustment,
  getAutoPilotCorridorTempoReleaseAdjustment: getAutoPilotCorridorTempoReleaseAdjustment,
  getAutoPilotCounterPressEscapeAdjustment: getAutoPilotCounterPressEscapeAdjustment,
  getAutoPilotEndProductUrgencyAdjustment: getAutoPilotEndProductUrgencyAdjustment,
  getAutoPilotFirstActionAfterReceiveAdjustment: getAutoPilotFirstActionAfterReceiveAdjustment,
  getAutoPilotFlowAdjustment: getAutoPilotFlowAdjustment,
  getAutoPilotGameSpaceAdjustment: getAutoPilotGameSpaceAdjustment,
  getAutoPilotLaneRealityAdjustment: getAutoPilotLaneRealityAdjustment,
  getAutoPilotLineBreakAdvantageAdjustment: getAutoPilotLineBreakAdvantageAdjustment,
  getAutoPilotLocalSuperiorityAdjustment: getAutoPilotLocalSuperiorityAdjustment,
  getAutoPilotNextSupportNetworkAdjustment: getAutoPilotNextSupportNetworkAdjustment,
  getAutoPilotOpeningVariationAdjustment: getAutoPilotOpeningVariationAdjustment,
  getAutoPilotOpponentBlockReadAdjustment: getAutoPilotOpponentBlockReadAdjustment,
  getAutoPilotPassLaneDenialAdjustment: getAutoPilotPassLaneDenialAdjustment,
  getAutoPilotPatternDiversityAdjustment: getAutoPilotPatternDiversityAdjustment,
  getAutoPilotPossessionIntentAdjustment: getAutoPilotPossessionIntentAdjustment,
  getAutoPilotPossessionLoopAdjustment: getAutoPilotPossessionLoopAdjustment,
  getAutoPilotPossessionPlayer: (...args) => getAutoPilotPossessionPlayer(...args),
  getAutoPilotPostRecoveryPhaseAdjustment: getAutoPilotPostRecoveryPhaseAdjustment,
  getAutoPilotPressureEscapeAdjustment: getAutoPilotPressureEscapeAdjustment,
  getAutoPilotPrincipleAdjustment: getAutoPilotPrincipleAdjustment,
  getAutoPilotReceiveFlowAdjustment: getAutoPilotReceiveFlowAdjustment,
  getAutoPilotReceiveMomentumAdjustment: getAutoPilotReceiveMomentumAdjustment,
  getAutoPilotReceivePressureTrapAdjustment: getAutoPilotReceivePressureTrapAdjustment,
  getAutoPilotReceiverAvailabilityAdjustment: getAutoPilotReceiverAvailabilityAdjustment,
  getAutoPilotRecoveryFirstActionAdjustment: getAutoPilotRecoveryFirstActionAdjustment,
  getAutoPilotRepetitionPenalty: getAutoPilotRepetitionPenalty,
  getAutoPilotRhythmGovernorAdjustment: getAutoPilotRhythmGovernorAdjustment,
  getAutoPilotRoleResponsibilityAdjustment: getAutoPilotRoleResponsibilityAdjustment,
  getAutoPilotSpaceDominanceAdjustment: getAutoPilotSpaceDominanceAdjustment,
  getAutoPilotSpaceLadderAdjustment: getAutoPilotSpaceLadderAdjustment,
  getAutoPilotSpaceTwoAdvantageAdjustment: getAutoPilotSpaceTwoAdvantageAdjustment,
  getAutoPilotSpacingBonus: getAutoPilotSpacingBonus,
  getAutoPilotSpatialDecisionAdjustment: getAutoPilotSpatialDecisionAdjustment,
  getAutoPilotTempoPhaseAdjustment: getAutoPilotTempoPhaseAdjustment,
  getAutoPilotTransitionNumbersAdjustment: getAutoPilotTransitionNumbersAdjustment,
  getAutoPilotVisionScanAdjustment: getAutoPilotVisionScanAdjustment,
  getDefensiveAutopilotLineKey: (...args) => getDefensiveAutopilotLineKey(...args),
  getDefensiveAutopilotProfile: getDefensiveAutopilotProfile,
  getDefensiveDribblePressTarget: getDefensiveDribblePressTarget,
  getDefensiveGoalkeeperTarget: getDefensiveGoalkeeperTarget,
  getDefensiveLineActionLabels: getDefensiveLineActionLabels,
  getDefensiveLineCenterY: (...args) => getDefensiveLineCenterY(...args),
  getDefensiveLineWidth: (...args) => getDefensiveLineWidth(...args),
  getDefensiveLineX: getDefensiveLineX,
  getDefensivePhaseKey: (...args) => getDefensivePhaseKey(...args),
  getDefensivePressTarget: getDefensivePressTarget,
  getDribblePressureReference: getDribblePressureReference,
  getFormationPositions: getFormationPositions,
  getOffensiveActionPrinciple: getOffensiveActionPrinciple,
  getOffensiveAutopilotProfile: (...args) => getOffensiveAutopilotProfile(...args),
  getOffensiveAutopilotTarget: getOffensiveAutopilotTarget,
  getOffensivePhaseKey: getOffensivePhaseKey,
  getPlayerBallControlPoint: getPlayerBallControlPoint,
  getState,
  lerp: lerp,
  pitch: pitch,
  shouldSkipOffensiveAutopilotPlayer: shouldSkipOffensiveAutopilotPlayer,
  teamRosterOrder: teamRosterOrder,
  teams: teams,
  uniquePrincipleLabels: uniquePrincipleLabels,
});

const {
  getAutoPilotRoleStrength,
  getAutoPilotPossessionPlayer,
  getLooseBallRecoveryTarget,
  getSecondBallReactionAdjustment,
  getLooseBallRecoveryStructureAdjustment,
  getLooseBallNearestOpponent,
  getLooseBallCollectControlTouch,
  applyLooseBallCollectControlTouch,
  chooseAutoPilotLooseBallRecovery,
  issueLooseBallRecoveryCommand,
  describeAutoPilotChoice,
  planAutoPilotNextAction,
  cancelAutoPilotContinuation,
  pauseAutoPilotPlay,
  getAutoPilotContinuationContext,
  getAutoPilotContinuationDelay,
  scheduleAutoPilotContinuation,
  refreshPlannedBallActionProfile,
  clearBallAction,
  setBallOwner,
  issuePassLikeCommand,
  issuePassCommand,
  issueShotCommand,
  issueDribbleCommand,
  issueBallCommand,
  detectShotGoal,
  detectShotOutOfPlay,
  detectTouchlineOutOfPlay,
  getGoalkeeperForTeam,
  getPreferredParrySafetyPlayer,
  getGoalkeeperParryProfile,
  resolveGoalkeeperSave,
  registerGoalFlash,
  completeGoalkeeperSave,
  completeShotGoal,
  completeShotOutOfPlay,
  completeTouchlineOutOfPlay,
  updateBall,
  updateDribble,
  updateLooseBallRecovery,
  updateActionPlayers,
  updateSequenceActionPlayers,
  updateLiveActionPlayers,
  updateSequenceTransition,
  stepSimulation,
  getBallStatus,
  getActionTypeLabel,
  describeStep,
  getSequenceStartSnapshot,
  getSequenceFrameSnapshot,
  persistCurrentFrameSnapshot,
  finalizeCurrentActionStep,
} = createGameSimulatorCommandEngine({
  angleBetween: angleBetween,
  applyAutopilotsForCurrentAction: applyAutopilotsForCurrentAction,
  applyBallExecutionProfile: applyBallExecutionProfile,
  applyBestReceiveBodyAngle: applyBestReceiveBodyAngle,
  applyCommittedSnapshot: (...args) => applyCommittedSnapshot(...args),
  applyCornerSetup: applyCornerSetup,
  applyFreeKickSetup: applyFreeKickSetup,
  applyGoalKickSetup: applyGoalKickSetup,
  applyKickoffSetup: applyKickoffSetup,
  applyPenaltySetup: applyPenaltySetup,
  applyResolvedBallProfile: applyResolvedBallProfile,
  applySnapshot: applySnapshot,
  applyThrowInSetup: applyThrowInSetup,
  ballRadiusMeters: ballRadiusMeters,
  buildMovementPath: buildMovementPath,
  canEditScenario: canEditScenario,
  captureSnapshot: captureSnapshot,
  chooseAutoPilotNextAction: chooseAutoPilotNextAction,
  clamp: clamp,
  clampToPitch: clampToPitch,
  clearAutoPilotReceiveMomentum: clearAutoPilotReceiveMomentum,
  clearKeyboardActionGrace: clearKeyboardActionGrace,
  clearSecurePossession: clearSecurePossession,
  cloneAutoV2DecisionTriggers: cloneAutoV2DecisionTriggers,
  cloneDefensiveAutopilotIntents: cloneDefensiveAutopilotIntents,
  cloneGoalEvent: cloneGoalEvent,
  cloneOffensiveAutopilotIntents: cloneOffensiveAutopilotIntents,
  cloneRestartPhase: cloneRestartPhase,
  cloneShotPlacement: cloneShotPlacement,
  cloneSnapshot: cloneSnapshot,
  cloneVector: cloneVector,
  completeLiveActionPlayersBeforeCommit: completeLiveActionPlayersBeforeCommit,
  computeTimeToCoverDistance: computeTimeToCoverDistance,
  configureBallTravelProfile: configureBallTravelProfile,
  connectBallToPlayerForNextAction: connectBallToPlayerForNextAction,
  createCommittedSnapshotFromCurrentState: (...args) => createCommittedSnapshotFromCurrentState(...args),
  createLooseBallSpill: createLooseBallSpill,
  defaultKickoffTeamId: defaultKickoffTeamId,
  distance: distance,
  executePlannedAction: (...args) => executePlannedAction(...args),
  finishSequencePlayback: (...args) => finishSequencePlayback(...args),
  formatSpeed: formatSpeed,
  getActionInitiator: getActionInitiator,
  getActionOrigin: getActionOrigin,
  getActionSpeed: getActionSpeed,
  getAttackDirectionSign: getAttackDirectionSign,
  getAttackingDepth: getAttackingDepth,
  getAutoPilotFlowContext: getAutoPilotFlowContext,
  getAutoPilotReceiveMomentum: getAutoPilotReceiveMomentum,
  getBallOwner: getBallOwner,
  getBallTravelPoint: getBallTravelPoint,
  getDefensiveAutoV2Intent: getDefensiveAutoV2Intent,
  getDefensiveAutopilotFocusPoint: getDefensiveAutopilotFocusPoint,
  getDribbleCarryPathPoint: getDribbleCarryPathPoint,
  getGoalDirectionSign: getGoalDirectionSign,
  getGoalLineX: getGoalLineX,
  getGoalNetDisplayPoint: getGoalNetDisplayPoint,
  getLiveDefensiveDribblePressTarget: getLiveDefensiveDribblePressTarget,
  getLiveDribbleSpeed: getLiveDribbleSpeed,
  getMovementPathPoint: getMovementPathPoint,
  getOffensiveAutoV2Intent: getOffensiveAutoV2Intent,
  getOffensiveAutopilotFocusPoint: getOffensiveAutopilotFocusPoint,
  getOffensiveAutopilotProfile: getOffensiveAutopilotProfile,
  getOffensiveRoleKey: getOffensiveRoleKey,
  getOffsideInfo: getOffsideInfo,
  getOpponentGoalSide: getOpponentGoalSide,
  getOpponentPenaltySpot: getOpponentPenaltySpot,
  getOpponentPressureAtPoint: getOpponentPressureAtPoint,
  getOtherTeamId: getOtherTeamId,
  getPitchThreatProfile: getPitchThreatProfile,
  getPlannedPossessionTeamId: getPlannedPossessionTeamId,
  getPlayerById: getPlayerById,
  getPlayerBallControlPoint: getPlayerBallControlPoint,
  getPlayerDecisionContext: getPlayerDecisionContext,
  getPlayerMagnetLabel: getPlayerMagnetLabel,
  getPlayerPositionForControlPoint: getPlayerPositionForControlPoint,
  getPlayerPressureLoad: getPlayerPressureLoad,
  getPlayerRoleModel: getPlayerRoleModel,
  getRecordedStepEndSnapshot: getRecordedStepEndSnapshot,
  getRequestedActionMode: getRequestedActionMode,
  getSelectedPlayer: getSelectedPlayer,
  getTeamAttackAngle: getTeamAttackAngle,
  getTeamSupportCountAroundPoint: getTeamSupportCountAroundPoint,
  hasBallAction: hasBallAction,
  isBetweenGoalPosts: isBetweenGoalPosts,
  isDefensiveAutopilotPlayer: isDefensiveAutopilotPlayer,
  isDefensiveDribblePresser: isDefensiveDribblePresser,
  isGoalkeeper: isGoalkeeper,
  isInsideOpponentBox: isInsideOpponentBox,
  isInsideOwnBox: isInsideOwnBox,
  isOffensiveAutopilotPlayer: isOffensiveAutopilotPlayer,
  keepSecurePossessionOnlyForOwner: keepSecurePossessionOnlyForOwner,
  lerp: lerp,
  logEvent: logEvent,
  markSequenceDirty: markSequenceDirty,
  moveDefensiveAutoV2Player: moveDefensiveAutoV2Player,
  moveOffensiveAutoV2Player: moveOffensiveAutoV2Player,
  moveTowards: moveTowards,
  normalize: normalize,
  pauseLiveSimulation: (...args) => pauseLiveSimulation(...args),
  pitch: pitch,
  queueNextSequenceStep: (...args) => queueNextSequenceStep(...args),
  randomBetween: randomBetween,
  render: (...args) => render(...args),
  resetPlayerMovementProgress: resetPlayerMovementProgress,
  resolveBallActionProfile: resolveBallActionProfile,
  resolveDribbleDefensiveChallenge: resolveDribbleDefensiveChallenge,
  resolveLooseBallClaim: resolveLooseBallClaim,
  resolvePassTransitInterception: resolvePassTransitInterception,
  resolveShotBlockCommitment: resolveShotBlockCommitment,
  resolveShotTarget: resolveShotTarget,
  rotatePlayerBodyAlongMovement: rotatePlayerBodyAlongMovement,
  rotatePlayerBodyToward: rotatePlayerBodyToward,
  rotatePlayerBodyTowardAngle: rotatePlayerBodyTowardAngle,
  setDribbleCarryPathForBall: setDribbleCarryPathForBall,
  setPiecePhaseProfiles: setPiecePhaseProfiles,
  setSecurePossessionAfterControlledTouch: setSecurePossessionAfterControlledTouch,
  setSelectedPlayers: setSelectedPlayers,
  settleBallForNextAction: settleBallForNextAction,
  shouldTriggerLandingBounce: shouldTriggerLandingBounce,
  startLandingBounceSkid: startLandingBounceSkid,
  startRecordedAction: (...args) => startRecordedAction(...args),
  teams: teams,
  ui: ui,
  updateBallFlightHeight: updateBallFlightHeight,
  updateSequenceButtons: (...args) => updateSequenceButtons(...args),
  win: win,
  getState,
});
return {
  addPointNoise, alignArrivedDefensiveAutopilotPlayers, angleBetween,
  angleDifference, applyAttackingBoxOccupationChainTargets, applyAutopilotTargetVariation,
  applyAutopilotsForCurrentAction, applyBallExecutionProfile, applyBallNearSupportTriangleTargets,
  applyBallWinEscapeTouch, applyBestReceiveBodyAngle, applyBetweenLinesPrincipleTargets,
  applyBlindsideChannelRunTargets, applyBoxOccupationPrincipleTargets, applyControlledFirstTouch,
  applyCornerDeliveryPrincipleTargets, applyCornerSetup, applyDefensiveAutoV2AntiMagnetRelationships,
  applyDefensiveAutoV2BackLineRelationship, applyDefensiveAutoV2MidfieldPressCover, applyDefensiveAutoV2PressTether,
  applyDefensiveAutoV2RelationshipLayer, applyDefensiveAutopilotForCurrentAction, applyDefensiveBackLineHandoverTargets,
  applyDefensiveBoxDeliveryChainTargets, applyDefensiveCarryContainmentTargets, applyDefensiveCentralAccessGateTargets,
  applyDefensiveChanceDenialTargets, applyDefensiveCornerSetPieceTargets, applyDefensiveEmergencyCoverTargets,
  applyDefensiveFreeKickSetPieceTargets, applyDefensiveGameSpaceResponseTargets, applyDefensiveGoalkeeperShotSetTarget,
  applyDefensiveGoalkeeperSweeperTarget, applyDefensiveLineBreakAdvantageCollapseTargets, applyDefensiveLocalOverloadResponseTargets,
  applyDefensiveLooseBallRecoveryTrapTargets, applyDefensiveOpenPlayTriggerTargets, applyDefensivePassLaneDenialTargets,
  applyDefensivePenaltySetPieceTargets, applyDefensivePostRecoveryResponseTargets, applyDefensivePressChainSupportTargets,
  applyDefensivePresserAngleTarget, applyDefensivePressureCoverBalanceTargets, applyDefensivePrioritySpaceProtectionTargets,
  applyDefensiveReceiveContinuationTargets, applyDefensiveReceptionTrapTargets, applyDefensiveRouteAnticipationTargets,
  applyDefensiveRunnerTrackingTargets, applyDefensiveSecondBallAnticipationTargets, applyDefensiveSwitchLandingLockTargets,
  applyDefensiveSwitchRecoveryTargets, applyDefensiveThrowInSetPieceTargets, applyFormationIdentityPrincipleTargets,
  applyFreeKickSetup, applyGameSpaceOffBallPrincipleTargets, applyGenerativePrincipleSupportTargets,
  applyGoalKickSetup, applyGoalkeeperBuildOutPressTargets, applyGoalkeeperBuildOutPrincipleTargets,
  applyHighValueSpacePrincipleTargets, applyKickoffSetup, applyLocalSuperioritySupportTargets,
  applyLooseBallCollectControlTouch, applyLooseBallRecoverySupportTargets, applyNearbyBallOrientation,
  applyNegativeTransitionDefensiveTargets, applyOffensiveAutoV2RelationshipLayer, applyOffensiveAutopilotForCurrentAction,
  applyOffensivePassingGeometryTargets, applyOffensiveRestDefenceNetTargets, applyOffensiveSecondBallAnticipationTargets,
  applyOpenGrassCarrySupportTargets, applyOpponentBlockResponsiveTargets, applyPasserContinuationTargets,
  applyPenaltySetup, applyPhysicalProfileToPlayers, applyPositionalPlayOccupationTargets,
  applyPossessionRoutePrincipleTargets, applyPostRecoveryAttackSupportTargets, applyPressEscapeContinuationTargets,
  applyPressResistanceEscapeSupportTargets, applyReachableDefensiveLineCohesion, applyReceptionSupportPrincipleTargets,
  applyResolvedBallProfile, applyShotReboundControlTouch, applyShotReboundPrincipleTargets,
  applySpaceTwoContinuationTargets, applySpaceTwoForwardFacingTargets, applySwitchLandingAttackTargets,
  applyThirdManChainSupportTargets, applyThrowInSetup, applyTimedFinalThirdBoxArrivals,
  applyTransitionAttackPrincipleTargets, blendAngles, buildAutoPilotBetweenLinesCandidate,
  buildAutoPilotBoxDeliveryCandidate, buildAutoPilotCornerCandidate, buildAutoPilotDangerZoneEscapeCandidate,
  buildAutoPilotDribbleCandidate, buildAutoPilotFinalThirdCombinationCandidate, buildAutoPilotFreeKickCandidate,
  buildAutoPilotGoalkeeperDistributionCandidate, buildAutoPilotKickoffCandidate, buildAutoPilotPassCandidates,
  buildAutoPilotPenaltyCandidate, buildAutoPilotPostKickoffResetCandidate, buildAutoPilotPressedRegainExitCandidate,
  buildAutoPilotPressureTrapEscapeCandidate, buildAutoPilotReceiveContinuationCandidate, buildAutoPilotRegainReleaseCandidate,
  buildAutoPilotShotCandidate, buildAutoPilotSwitchLandingContinuationCandidate, buildAutoPilotThroughBallCandidate,
  buildAutoPilotThrowInCandidate, buildAutoPilotWideOverlapCandidate, buildDefensiveAutoV2Intents,
  buildDefensiveAutopilotTargets, buildDribbleCarryPath, buildMovementPath,
  buildOffensiveAutoV2Intents, buildOffensiveAutopilotTargets, buildPlayerIntelligenceProfile,
  buildPlayerSprintProfile, buildPlayerTendencyProfile, buildSampledCurvePath,
  cancelAutoPilotContinuation, chooseAutoPilotLooseBallRecovery, chooseAutoPilotNextAction,
  chooseBlindsideChannelRunner, chooseCornerDeliveryRunner, chooseDefensiveAutopilotPresser,
  chooseDefensiveDribblePresser, chooseFreeKickShortReceiver, chooseOffensiveAutopilotRunner,
  chooseScoredCandidateWithVariation, chooseTimedBoxArrivalPlayer, chooseWeightedOption,
  chooseWideOverlapRunner, clamp, clampToCircle,
  clampToPitch, clearAutoPilotReceiveMomentum, clearBallAction,
  clearSecurePossession, cloneAutoV2DecisionTriggers, cloneDefensiveAutopilotIntents,
  cloneGoalEvent, cloneOffensiveAutopilotIntents, cloneSecurePossession,
  cloneShotPlacement, cloneVector, completeDribbleFoulRestart,
  completeGoalkeeperSave, completeLiveActionPlayersBeforeCommit, completeShotGoal,
  completeShotOutOfPlay, completeTouchlineOutOfPlay, computePassLaneClarity,
  computeReachDistance, computeShotLaneClarity, computeTimeToCoverDistance,
  configureBallTravelProfile, connectBallToPlayerForNextAction, createAutoPilotOpeningVariation,
  createAutoPilotPossessionPlan, createAutoPilotPossessionRoute, createLooseBallSpill,
  createPlayer, createTransitionPlan, describeAutoPilotChoice,
  describeStep, detectShotGoal, detectShotOutOfPlay,
  detectTouchlineOutOfPlay, distance, enforceDefensiveBlockGeometryLock,
  enforceDefensiveCollectiveShiftCohesion, enforceDefensiveCompactLineIntegrity, enforceDefensiveLineChainSpacing,
  enforceDefensiveLineStaggering, enforceDefensiveMeasuredBlockEnvelope, enforceDefensiveOffsideLineControl,
  enforceDefensiveUnitCompactness, enforceDefensiveVerticalBlockConnections, enforceOffensiveFiveLaneOccupation,
  enforceOffensiveOccupationZones, enforceOffensiveOnsideLineAwareness, enforceOffensiveStructureBalance,
  enforceOffensiveTargetSpacing, estimateAutoPilotCandidateDuration, finalizeCurrentActionStep,
  formatMeters, formatSpeed, formatTime,
  getActionDistance, getActionInitiator, getActionOrigin,
  getActionSpaceValue, getActionSpeed, getActionThreatGain,
  getActionTypeLabel, getActiveMovementTarget, getActualLocalSuperiorityProfile,
  getAerialAttackingKnockdownAngle, getAerialContestScore, getAerialControlScore,
  getAerialDefensiveClearanceAngle, getAerialFirstContactContext, getAerialFirstContactScore,
  getAerialPresence, getAttackDirectionSign, getAttackingBoxOccupationChainContext,
  getAttackingBoxOccupationChainTarget, getAttackingDepth, getAttackingGameSpaceProfile,
  getAttackingThirdKey, getAutoPilotAdvantageLifecycleAdjustment, getAutoPilotAdvantageLifecycleContext,
  getAutoPilotAdvantageRetentionAdjustment, getAutoPilotAdvantageRetentionContext, getAutoPilotBoxTarget,
  getAutoPilotCandidatePattern, getAutoPilotCandidatePrincipleMetrics, getAutoPilotCandidateReceiver,
  getAutoPilotCarryEndProductAdjustment, getAutoPilotCarryEndProductContext, getAutoPilotChanceHierarchyAdjustment,
  getAutoPilotChanceHierarchyContext, getAutoPilotCombinationChainAdjustment, getAutoPilotCombinationChainContext,
  getAutoPilotContinuationContext, getAutoPilotContinuationDelay, getAutoPilotCorridorTempoReleaseAdjustment,
  getAutoPilotCounterPressEscapeAdjustment, getAutoPilotDecisionPersonalityWeight, getAutoPilotDribbleTarget,
  getAutoPilotEndProductUrgencyAdjustment, getAutoPilotEndProductUrgencyContext, getAutoPilotFirstActionAfterReceiveAdjustment,
  getAutoPilotFlowAdjustment, getAutoPilotFlowContext, getAutoPilotGameSpaceAdjustment,
  getAutoPilotIntentionModel, getAutoPilotLaneRealityAdjustment, getAutoPilotLineBreakAdvantageAdjustment,
  getAutoPilotLocalSuperiorityAdjustment, getAutoPilotLocalSuperiorityProfile, getAutoPilotNextSupportNetworkAdjustment,
  getAutoPilotNextSupportNetworkProfile, getAutoPilotOpeningVariationAdjustment, getAutoPilotOpponentBlockReadAdjustment,
  getAutoPilotPassLaneDenialAdjustment, getAutoPilotPatternDiversityAdjustment, getAutoPilotPlanRepeatPenalty,
  getAutoPilotPossessionIntentAdjustment, getAutoPilotPossessionIntentContext, getAutoPilotPossessionIntentFit,
  getAutoPilotPossessionLoopAdjustment, getAutoPilotPossessionPlan, getAutoPilotPossessionPlayer,
  getAutoPilotPossessionRouteStage, getAutoPilotPossessionStartIndex, getAutoPilotPostRecoveryPhaseAdjustment,
  getAutoPilotPostRecoveryPhaseContext, getAutoPilotPressureEscapeAdjustment, getAutoPilotPressureEscapeContext,
  getAutoPilotPrincipleAdjustment, getAutoPilotReceiveFlowAdjustment, getAutoPilotReceiveFlowContext,
  getAutoPilotReceiveMomentum, getAutoPilotReceiveMomentumAdjustment, getAutoPilotReceivePressureTrapAdjustment,
  getAutoPilotReceiverAvailabilityAdjustment, getAutoPilotRecoveryFirstActionAdjustment, getAutoPilotRecoveryFirstActionContext,
  getAutoPilotRegainContext, getAutoPilotRepetitionPenalty, getAutoPilotRhythmGovernorAdjustment,
  getAutoPilotRoleResponsibilityAdjustment, getAutoPilotRoleStrength, getAutoPilotShotTarget,
  getAutoPilotSpaceDominanceAdjustment, getAutoPilotSpaceLadderAdjustment, getAutoPilotSpaceLadderContext,
  getAutoPilotSpaceTwoAdvantageAdjustment, getAutoPilotSpacingBonus, getAutoPilotSpatialDecisionAdjustment,
  getAutoPilotStyleIntentSequence, getAutoPilotStylePrincipleWeights, getAutoPilotTempoPhaseAdjustment,
  getAutoPilotTempoPhaseContext, getAutoPilotTransitionNumbersAdjustment, getAutoPilotTransitionNumbersContext,
  getAutoPilotVisionScanAdjustment, getAutopilotTargetVariationRadius, getBallAwareBodyAngle,
  getBallContestControlScore, getBallControlOffsetMeters, getBallDuelScore,
  getBallFlightControlFactor, getBallNearSupportTriangleTarget, getBallProfileDistanceRatio,
  getBallProfileLabel, getBallStatus, getBallTravelPoint,
  getBallTravelProgress, getBallWinEscapeTouch, getBestReceiveBodyAngle,
  getBlindsideChannelRunContext, getBlindsideChannelRunTarget, getBoxOccupationTarget,
  getBreakawayCarryTarget, getCarryLaneOpenSpaceScore, getCarryRunwayProfile,
  getCarryRunwayRoleCap, getCompetitionPhysicalLabel, getCompetitionPhysicalProfile,
  getCornerDeliveryTarget, getCornerKickSpot, getCoverShadowInfluence,
  getCurrentActionDuration, getCurvedRecoveryWaypoint, getDefendingDirectionSign,
  getDefensiveAggressionPreset, getDefensiveAngledPressTarget, getDefensiveAutoV2FrameDt,
  getDefensiveAutoV2Intent, getDefensiveAutopilotFocusPoint, getDefensiveAutopilotGroupsForTeam,
  getDefensiveAutopilotLineKey, getDefensiveAutopilotProfile, getDefensiveBackLineHandoverContext,
  getDefensiveBoxDeliveryChainContext, getDefensiveBoxDeliveryChainTarget, getDefensiveCarryContainmentContext,
  getDefensiveCarryContainmentTarget, getDefensiveCentralAccessGateContext, getDefensiveCentralAccessGateTarget,
  getDefensiveChanceDenialContext, getDefensiveChanceDenialTarget, getDefensiveCompactLineIntegritySettings,
  getDefensiveCornerContext, getDefensiveCornerTarget, getDefensiveDribblePressTarget,
  getDefensiveEmergencyCoverContext, getDefensiveEmergencyCoverTarget, getDefensiveFreeKickContext,
  getDefensiveFreeKickTarget, getDefensiveGameSpaceResponseContext, getDefensiveGameSpaceResponseTarget,
  getDefensiveGoalkeeperShotSetContext, getDefensiveGoalkeeperShotSetTarget, getDefensiveGoalkeeperSweeperContext,
  getDefensiveGoalkeeperTarget, getDefensiveLineActionAdjustment, getDefensiveLineActionLabels,
  getDefensiveLineBreakAdvantageContext, getDefensiveLineBreakAdvantageTarget, getDefensiveLineCenterY,
  getDefensiveLineDistanceFromOwnGoal, getDefensiveLineWidth, getDefensiveLineX,
  getDefensiveLocalOverloadContext, getDefensiveLocalOverloadTarget, getDefensiveLooseBallRecoveryTrapContext,
  getDefensiveLooseBallRecoveryTrapTarget, getDefensiveOffsideLineControlContext, getDefensiveOpenPlayTriggerContext,
  getDefensiveOpenPlayTriggerTarget, getDefensivePassLaneDenialContext, getDefensivePassLaneDenialTarget,
  getDefensivePenaltyContext, getDefensivePenaltyTarget, getDefensivePhaseKey,
  getDefensivePostRecoveryOutletOptions, getDefensivePostRecoveryResponseContext, getDefensivePostRecoveryResponseTarget,
  getDefensivePressChainSupportContext, getDefensivePressChainSupportTarget, getDefensivePressTarget,
  getDefensivePressureCoverContext, getDefensivePressureCoverTarget, getDefensivePrioritySpacePoint,
  getDefensiveReceiveContinuationContext, getDefensiveReceiveContinuationNextPoint, getDefensiveReceiveContinuationTarget,
  getDefensiveReceptionTrapContext, getDefensiveReceptionTrapTarget, getDefensiveRouteAnticipationContext,
  getDefensiveRouteAnticipationTarget, getDefensiveRunnerThreats, getDefensiveRunnerTrackingTarget,
  getDefensiveSecondBallAnticipationTarget, getDefensiveSwitchLandingLockContext, getDefensiveSwitchLandingLockTarget,
  getDefensiveSwitchRecoveryContext, getDefensiveSwitchRecoveryTarget, getDefensiveThreatResponse,
  getDefensiveThrowInContext, getDefensiveThrowInTarget, getDefensiveUnitGap,
  getDepthPoint, getDepthQuantile, getDepthX,
  getDepthZoneKey, getDepthZoneLabel, getDeterministicShotNoise,
  getDisplayedBallSpeed, getDistanceFromOwnGoal, getDribbleCarryPathPoint,
  getDribbleFoulCandidate, getDribblePressureReference, getDribbleRoleFamily,
  getDribbleTackleCandidate, getEditableRadius, getFinalThirdCombinationVariants,
  getFirstTouchDirectionAngle, getFirstTouchDistance, getFirstTouchModeLabel,
  getFiveLaneOccupationCandidates, getFiveLaneOccupationSlotTarget, getFlightStyleLabel,
  getFootUsageScore, getFootballSpacePriority, getFormationIdentityTarget,
  getFormationPositions, getForwardFacingSpaceTwoContext, getForwardProgressionWindow,
  getFreeKickDeliveryTarget, getFreeKickWallTarget, getGameSpaceOffBallTarget,
  getGoalDirectionSign, getGoalLineX, getGoalMouthTarget,
  getGoalNetDisplayPoint, getGoalkeeperBuildOutPressContext, getGoalkeeperBuildOutPressTarget,
  getGoalkeeperBuildOutSupportTarget, getGoalkeeperDirectReleaseTarget, getGoalkeeperDistributionPressure,
  getGoalkeeperForTeam, getGoalkeeperParryProfile, getGoalkeeperTargetOpenness,
  getGoldenZoneScore, getHighValueAttackTarget, getIntelligenceArchetype,
  getKickoffDefensivePhaseKey, getKickoffOpeningCandidateFit, getKickoffSpot,
  getKickoffSupportId, getKickoffTakerId, getLaneCenterY,
  getLaneForSideSign, getLaneLabel, getLastAutoPrincipleSet,
  getLastKickoffOpeningProfile, getLastSwitchLandingActionContext, getLiveBallFocusPoint,
  getLiveDefensiveDribblePressTarget, getLiveDribbleSpeed, getLocalSuperioritySupportTarget,
  getLooseBallClaimScore, getLooseBallCollectControlTouch, getLooseBallNearestOpponent,
  getLooseBallRecoveryStructureAdjustment, getLooseBallRecoverySupportTarget, getLooseBallRecoveryTarget,
  getManualBallProfile, getMedianNumber, getMovableAutopilotPlayerByRoles,
  getMovableAutopilotPlayerByRolesOnSide, getMovementPathPoint, getNaturalDecisionDiversityWeight,
  getNearestOpponentGapInCarryLane, getNearestOpponentGapToPoint, getNegativeTransitionContext,
  getNegativeTransitionOutletOptions, getNegativeTransitionTarget, getNextSupportSlotRoleFit,
  getOffBallCounterMovementWaypoint, getOffensiveActionPrinciple, getOffensiveAutoV2Intent,
  getOffensiveAutopilotFocusPoint, getOffensiveAutopilotProfile, getOffensiveAutopilotTarget,
  getOffensiveLaneY, getOffensiveOnsideLineContext, getOffensivePassingGeometryContext,
  getOffensivePassingGeometryTarget, getOffensivePhaseKey, getOffensiveRestDefenceNetContext,
  getOffensiveRestDefenceNetTarget, getOffensiveRoleKey, getOffensiveSecondBallAnticipationTarget,
  getOffensiveStructureBalanceTarget, getOffsideInfo, getOpenGrassCarryContext,
  getOpenGrassCarrySupportTarget, getOpponentBlockOccupationTarget, getOpponentBlockReadProfile,
  getOpponentDensityAtPoint, getOpponentGoalCenter, getOpponentGoalSide,
  getOpponentLineDepthsForAttackingTeam, getOpponentPenaltySpot, getOpponentPressureAtPoint,
  getOpponentsBypassedByAction, getOrientationMovementProfile, getOrientationTurnDelay,
  getOtherTeamId, getOwnGoalCenter, getPassLaneRiskProfile,
  getPasserContinuationTarget, getPitchLaneIndex, getPitchLaneKey,
  getPitchSpaceProfile, getPitchSurfacePreset, getPitchThreatProfile,
  getPlannedPossessionTeamId, getPlayerBallControlPoint, getPlayerFacingAngle,
  getPlayerMagnetLabel, getPlayerOrientationFocus, getPlayerPositionForControlPoint,
  getPlayerRoleModel, getPlayerTeamId, getPlayerTendency,
  getPositionalPlayOccupationTarget, getPossessionRhythmContext, getPossessionRouteOccupationTarget,
  getPossessionShieldOpponents, getPostRecoveryAttackSupportContext, getPostRecoveryAttackSupportTarget,
  getPotentialPassReceiverAtTarget, getPreferredFootOffsetAngle, getPreferredParrySafetyPlayer,
  getPressEscapeContinuationTarget, getPressResistanceEscapeTarget, getPressedRegainExitVector,
  getProjectedActionDuration, getQuadraticPoint, getReceiveContinuationCarryTarget,
  getReceiveFootUsageScore, getReceiveOrientationScore, getReceiverAvailabilityProfile,
  getRecentAutoPilotPlanMemory, getRecentLaneRepeatCount, getRecentPossessionSteps,
  getReceptionSupportTarget, getRecordedStepActorIds, getRecordedStepDuration,
  getRecordedStepEndSnapshot, getRecordedStepPattern, getRecordedStepPossessionTeamId,
  getRemainingBallDistance, getRemainingBallTravelTime, getRequestedActionMode,
  getRestartActionMeta, getRunwayCarryTarget, getSameSideWideBacks,
  getSampledPathPoint, getSecondBallAnticipationContext, getSecondBallReactionAdjustment,
  getSecondLastOpponentLineX, getSecurePossessionContext, getSecurePossessionSnapshotForTeam,
  getSequenceFrameSnapshot, getSequenceStartSnapshot, getShotAngleQuality,
  getShotBlockRisk, getShotReboundClaimAdjustment, getShotReboundClaimContext,
  getShotReboundGeometryContext, getShotReboundTarget, getShotWindowProfile,
  getSideLaneKeys, getSnapshotPlayerMap, getSpaceDominanceProfile,
  getSpacePassTargetPoint, getSpaceTwoContinuationContext, getSpaceTwoContinuationTarget,
  getSpaceTwoForwardFacingTarget, getSprintArchetype, getStepReceiverRoleKey,
  getStructureBalanceCandidates, getSupportUnderBallTarget, getSwitchLandingAttackContext,
  getSwitchLandingAttackTarget, getTargetLocalSuperiorityProfile, getTeamAttackAngle,
  getTeamDensityAtPoint, getTeamSupportCountAroundPoint, getThirdManRunnerTarget,
  getTimedBoxArrivalContext, getTimedBoxArrivalTarget, getTransitionAttackTarget,
  getUniversalFootballDecisionAdjustment, getWeatherPreset, getWideEntryPrincipleContext,
  getWideOverlapPrincipleFit, getWideOverlapRunTarget, getWideSideSign,
  hasBallAction, invalidateAutoPilotPossessionPlan, isAerialFlightStyle,
  isBetweenGoalPosts, isBylineZone, isCutbackTarget,
  isDefensiveAutopilotPlayer, isDefensiveDribblePresser, isFrontLineRole,
  isGoalkeeper, isGoldenZone, isInsideOpponentBox,
  isInsideOwnBox, isLastStepKickoffResetForTeam, isOffensiveAutopilotPlayer,
  isPassReceiverOffside, isPlayerFacingForward, isPlayerReservedForReceiveShape,
  isSupportRole, isTransitionAttackStyle, isWideChannel,
  isWidePrincipleZone, issueBallCommand, issueDribbleCommand,
  issueLooseBallRecoveryCommand, issuePassCommand, issuePassLikeCommand,
  issueShotCommand, keepBallPlayableForNextAction, keepSecurePossessionOnlyForOwner,
  kickoffOpeningProfiles, lerp, materializeBallProfile,
  mergeIntentionWeights, moveDefensiveAutoV2Player, moveOffensiveAutoV2Player,
  moveTowards, normalize, normalizeAngle,
  pauseAutoPilotPlay, persistCurrentFrameSnapshot, pickDefensiveAutopilotPlayer,
  pickDefensiveProtectionPlayer, pickOffensiveAutoV2Player, placePlayerWithControlPoint,
  planAutoPilotNextAction, principleSetIncludes, projectPointOnSegment,
  projectPointOnSegmentWithRatio, randomBetween, randomSign,
  refreshPlannedBallActionProfile, registerGoalFlash, rememberAutoPilotPossessionPlan,
  resetPlayerMovementProgress, resolveAerialArrivalContest, resolveAutoBallProfile,
  resolveAutoDribbleProfile, resolveBallActionProfile, resolveBallCurveDirection,
  resolveDribbleDefensiveChallenge, resolveExecutedShotTarget, resolveFirstTouchMode,
  resolveGoalkeeperSave, resolveLooseBallClaim, resolveOpeningVariationLanes,
  resolvePassTransitInterception, resolvePossessionRouteLanes, resolveRecordedStepProfile,
  resolveShotBlockCommitment, resolveShotTarget, rotatePlayerBodyAlongMovement,
  rotatePlayerBodyToward, rotatePlayerBodyTowardAngle, scanAutoV2DecisionTriggers,
  scheduleAutoPilotContinuation, scoreAutoPilotCandidateByIntentions, setAutoPilotReceiveMomentum,
  setAutopilotPrincipleTarget, setBallOwner, setDribbleCarryPathForBall,
  setReachableDefensiveAutoV2Target, setReachableOffensiveAutoV2Target, setSecurePossessionAfterBallWin,
  setSecurePossessionAfterControlledTouch, setTeamFormationOnPlayers, settleBallForNextAction,
  shouldSkipOffensiveAutopilotPlayer, shouldTriggerLandingBounce, shouldUseAutoPilotActiveFirstTouch,
  shouldUseCurvedRecoveryRun, shouldUseOffBallCounterMovementRun, snapshotsMatch,
  startLandingBounceSkid, stepSimulation, subtract,
  uniquePrincipleLabels, updateActionPlayers, updateBall,
  updateBallFlightHeight, updateDribble, updateLiveActionPlayers,
  updateLooseBallRecovery, updateSequenceActionPlayers, updateSequenceTransition,
  vec, weightOffensiveAutoV2Intent
};
}
