import { createGameSimulatorActionSpaceRuntime } from "./engine-action-space-wiring.mjs";
import { createGameSimulatorAutopilotRuntime } from "./engine-autopilot-wiring.mjs";
import { createGameSimulatorBallResolutionRuntime } from "./engine-ball-resolution-wiring.mjs";
import { createGameSimulatorCommandRuntime } from "./engine-command-wiring.mjs";
import { createGameSimulatorGeometryHelpers } from "./geometry-helpers.mjs";
import { createGameSimulatorSetupEngine } from "./setup-engine.mjs";

export function createGameSimulatorEngineBundle(deps = {}) {
const {
  applyCommittedSnapshot, applySnapshot, autoBallProfiles,
  autoDribbleProfiles, ballRadiusMeters, canEditScenario,
  captureSnapshot, clearKeyboardActionGrace, cloneRestartPhase,
  cloneSnapshot, competitionPhysicalProfiles, createCommittedSnapshotFromCurrentState,
  defaultKickoffTeamId, defaultPhysicalProfileKey, defensiveAggressionPresets,
  defensiveAutopilotProfiles, defensivePhaseProfiles, executePlannedAction,
  finishSequencePlayback, firstTouchModes, formationLayouts,
  formationMagnetLabels, gameRoleProfiles, getAttackStyleRhythmProfile,
  getBallOwner, getNearestOpponentGap, getPlayerById,
  getPlayerDecisionContext, getPlayerPressureLoad, getSelectedPlayer,
  getState, getTeamAttackStyleKey, getTeamAttackStyleProfile,
  getTeamDefenseStyleKey, getTeamDefenseStyleProfile, intelligenceLabelBoosts,
  intelligenceRoleArchetypes, logEvent, markSequenceDirty,
  offensiveAutopilotProfiles, offensivePhaseProfiles, pauseLiveSimulation,
  pitch, pitchSurfacePresets, playerRadiusMeters,
  playerTendencyTemplates, possessionRhythmDefaults, queueNextSequenceStep,
  render, resolvePreferredFoot, resolveWeakFootQuality,
  setPiecePhaseProfiles, setSelectedPlayers, sprintRoleArchetypes,
  squadBlueprints, startRecordedAction, teamRosterOrder,
  teams, ui, updateSequenceButtons,
  weatherPresets, win
} = deps;
const {
  getPlayerMagnetLabel,
  vec,
  cloneVector,
  cloneSecurePossession,
  cloneGoalEvent,
  cloneShotPlacement,
  subtract,
  clamp,
  lerp,
  randomBetween,
  randomSign,
  addPointNoise,
  chooseWeightedOption,
  getNaturalDecisionDiversityWeight,
  getAutoPilotDecisionPersonalityWeight,
  chooseScoredCandidateWithVariation,
  clampToPitch,
  distance,
  normalize,
  moveTowards,
  normalizeAngle,
  angleBetween,
  angleDifference,
  getTeamAttackAngle,
  getPlayerFacingAngle,
  rotatePlayerBodyToward,
  rotatePlayerBodyTowardAngle,
  rotatePlayerBodyAlongMovement,
  getBallAwareBodyAngle,
  getPlayerBallControlPoint,
  getPreferredFootOffsetAngle,
  getFootUsageScore,
  blendAngles,
  projectPointOnSegment,
  projectPointOnSegmentWithRatio,
  formatTime,
  formatSpeed,
  formatMeters,
  getIntelligenceArchetype,
  getSprintArchetype,
} = createGameSimulatorGeometryHelpers({
  formationMagnetLabels,
  getActionSpaceValue: (...args) => getActionSpaceValue(...args),
  getAutoPilotCandidatePattern: (...args) => getAutoPilotCandidatePattern(...args),
  getAutoPilotRoleStrength: (...args) => getAutoPilotRoleStrength(...args),
  getBallControlOffsetMeters: (...args) => getBallControlOffsetMeters(...args),
  getPitchLaneIndex: (...args) => getPitchLaneIndex(...args),
  getPitchThreatProfile: (...args) => getPitchThreatProfile(...args),
  getPlayerDecisionContext: (...args) => getPlayerDecisionContext(...args),
  getPlayerTeamId: (...args) => getPlayerTeamId(...args),
  getPlayerTendency: (...args) => getPlayerTendency(...args),
  getRecentPossessionSteps: (...args) => getRecentPossessionSteps(...args),
  getRecordedStepPattern: (...args) => getRecordedStepPattern(...args),
  intelligenceRoleArchetypes,
  isTransitionAttackStyle: (...args) => isTransitionAttackStyle(...args),
  pitch,
  sprintRoleArchetypes,
  teamRosterOrder,
  teams,
});

const gameSimulatorSetupEngine = createGameSimulatorSetupEngine({
  angleBetween,
  ballRadiusMeters,
  chooseScoredCandidateWithVariation,
  chooseWeightedOption,
  clamp,
  clampToPitch,
  cloneVector,
  competitionPhysicalProfiles,
  defaultKickoffTeamId,
  defaultPhysicalProfileKey,
  defensiveAutopilotProfiles,
  defensivePhaseProfiles,
  distance,
  formationLayouts,
  getAttackDirectionSign: (...args) => getAttackDirectionSign(...args),
  getDefensiveAutopilotLineKey: (...args) => getDefensiveAutopilotLineKey(...args),
  getDefensiveCompactLineIntegritySettings: (...args) => getDefensiveCompactLineIntegritySettings(...args),
  getDefensiveGoalkeeperTarget: (...args) => getDefensiveGoalkeeperTarget(...args),
  getDefensiveLineCenterY: (...args) => getDefensiveLineCenterY(...args),
  getDefensiveLineX: (...args) => getDefensiveLineX(...args),
  getDefensiveUnitGap: (...args) => getDefensiveUnitGap(...args),
  getIntelligenceArchetype,
  getOffensiveAutopilotProfile: (...args) => getOffensiveAutopilotProfile(...args),
  getOffensiveRoleKey: (...args) => getOffensiveRoleKey(...args),
  getOpponentGoalCenter: (...args) => getOpponentGoalCenter(...args),
  getOpponentPenaltySpot: (...args) => getOpponentPenaltySpot(...args),
  getOtherTeamId: (...args) => getOtherTeamId(...args),
  getPlayerMagnetLabel,
  getSprintArchetype,
  getTeamAttackAngle,
  getTeamAttackStyleProfile,
  getTeamDefenseStyleKey,
  getTeamDefenseStyleProfile,
  intelligenceLabelBoosts,
  invalidateAutoPilotPossessionPlan: (...args) => invalidateAutoPilotPossessionPlan(...args),
  isFrontLineRole: (...args) => isFrontLineRole(...args),
  isGoalkeeper: (...args) => isGoalkeeper(...args),
  normalize,
  pitch,
  playerRadiusMeters,
  playerTendencyTemplates,
  randomBetween,
  randomSign,
  resolvePreferredFoot,
  resolveWeakFootQuality,
  setPiecePhaseProfiles,
  squadBlueprints,
  teamRosterOrder,
  teams,
  vec,
  getState,
});
const {
  applyCornerSetup,
  applyFreeKickSetup,
  applyGoalKickSetup,
  applyKickoffSetup,
  applyPenaltySetup,
  applyPhysicalProfileToPlayers,
  applyThrowInSetup,
  buildPlayerIntelligenceProfile,
  buildPlayerSprintProfile,
  buildPlayerTendencyProfile,
  createPlayer,
  getBallControlOffsetMeters,
  getCompetitionPhysicalLabel,
  getCompetitionPhysicalProfile,
  getCornerKickSpot,
  getFormationPositions,
  getKickoffDefensivePhaseKey,
  getKickoffSupportId,
  getKickoffTakerId,
  getKickoffSpot,
  getPlayerPositionForControlPoint,
  getPlayerTeamId,
  getPlayerTendency,
  kickoffOpeningProfiles,
  placePlayerWithControlPoint,
  resetPlayerMovementProgress,
  setTeamFormationOnPlayers,
} = gameSimulatorSetupEngine;
const {
  getRemainingBallDistance,
  hasBallAction,
  getActionOrigin,
  getProjectedActionDuration,
  getCurrentActionDuration,
  getActionInitiator,
  getOrientationTurnDelay,
  getOrientationMovementProfile,
  getCoverShadowInfluence,
  getReceiveOrientationScore,
  getBestReceiveBodyAngle,
  getReceiveFootUsageScore,
  applyBestReceiveBodyAngle,
  getFirstTouchModeLabel,
  resolveFirstTouchMode,
  getFirstTouchDirectionAngle,
  getFirstTouchDistance,
  clearAutoPilotReceiveMomentum,
  setAutoPilotReceiveMomentum,
  getAutoPilotReceiveMomentum,
  getAutoPilotReceiveMomentumAdjustment,
  getAutoPilotFirstActionAfterReceiveAdjustment,
  getAutoPilotReceiveFlowContext,
  getAutoPilotReceiveFlowAdjustment,
  getReceiveContinuationCarryTarget,
  buildAutoPilotReceiveContinuationCandidate,
  applyControlledFirstTouch,
  shouldUseAutoPilotActiveFirstTouch,
  getLiveBallFocusPoint,
  getSpacePassTargetPoint,
  getPlayerOrientationFocus,
  getActiveMovementTarget,
  isPlayerReservedForReceiveShape,
  applyNearbyBallOrientation,
  getPotentialPassReceiverAtTarget,
  getPassLaneRiskProfile,
  computePassLaneClarity,
  getGoalMouthTarget,
  getShotAngleQuality,
  getShotBlockRisk,
  getGoalkeeperTargetOpenness,
  computeShotLaneClarity,
  getShotWindowProfile,
  getDeterministicShotNoise,
  resolveExecutedShotTarget,
  getAttackDirectionSign,
  getAttackingDepth,
  getOpponentGoalCenter,
  getDepthZoneKey,
  getDepthZoneLabel,
  getLaneLabel,
  getGoldenZoneScore,
  isGoldenZone,
  getMedianNumber,
  getDepthQuantile,
  getOpponentLineDepthsForAttackingTeam,
  getAttackingGameSpaceProfile,
  getPitchSpaceProfile,
  getPitchThreatProfile,
  getOpponentPressureAtPoint,
  getNearestOpponentGapToPoint,
  getOpponentsBypassedByAction,
  getFootballSpacePriority,
  getActionSpaceValue,
  getTeamDensityAtPoint,
  getOpponentDensityAtPoint,
  getSpaceDominanceProfile,
  getAutoPilotSpaceDominanceAdjustment,
  getAutoPilotGameSpaceAdjustment,
  getAutoPilotSpatialDecisionAdjustment,
  getActionThreatGain,
  isPlayerFacingForward,
  getForwardFacingSpaceTwoContext,
  getAutoPilotSpaceTwoAdvantageAdjustment,
  getForwardProgressionWindow,
  getOpponentGoalSide,
  getGoalLineX,
  getGoalDirectionSign,
  isBetweenGoalPosts,
  getGoalNetDisplayPoint,
  resolveShotTarget,
  getOwnGoalCenter,
  getOpponentPenaltySpot,
  getSecondLastOpponentLineX,
  getOffsideInfo,
  isPassReceiverOffside,
  isWideChannel,
  isBylineZone,
  isInsideOpponentBox,
  isInsideOwnBox,
  isCutbackTarget,
  isGoalkeeper,
  getBallProfileDistanceRatio,
  getPitchSurfacePreset,
  getWeatherPreset,
  getDefensiveAggressionPreset,
  isAerialFlightStyle,
  getFlightStyleLabel,
  resolveBallCurveDirection,
  getBallTravelProgress,
  getBallTravelPoint,
  materializeBallProfile,
  getManualBallProfile,
  getDribbleRoleFamily,
  resolveAutoDribbleProfile,
  getNearestOpponentGapInCarryLane,
  getCarryLaneOpenSpaceScore,
  getCarryRunwayRoleCap,
  getCarryRunwayProfile,
  getRunwayCarryTarget,
  getBreakawayCarryTarget,
  getOpenGrassCarryContext,
  getQuadraticPoint,
  buildSampledCurvePath,
  getSampledPathPoint,
  buildDribbleCarryPath,
  getDribbleCarryPathPoint,
  setDribbleCarryPathForBall,
  getLiveDribbleSpeed,
  resolveAutoBallProfile,
  resolveBallActionProfile,
  resolveRecordedStepProfile,
  applyResolvedBallProfile,
  getBallProfileLabel,
  getDisplayedBallSpeed,
  getRemainingBallTravelTime,
  updateBallFlightHeight,
  getBallFlightControlFactor,
} = createGameSimulatorActionSpaceRuntime({
  angleBetween, angleDifference, autoBallProfiles,
  autoDribbleProfiles, ballRadiusMeters, blendAngles,
  buildPlayerIntelligenceProfile, clamp, clampToPitch,
  cloneVector,
  computeTimeToCoverDistance: (...args) => computeTimeToCoverDistance(...args),
  defensiveAggressionPresets, distance, firstTouchModes,
  getActionSpeed: (...args) => getActionSpeed(...args),
  getAutoPilotFlowContext: (...args) => getAutoPilotFlowContext(...args),
  getAutoPilotRoleStrength: (...args) => getAutoPilotRoleStrength(...args),
  getBallAwareBodyAngle, getBallControlOffsetMeters, getBallOwner,
  getCompetitionPhysicalProfile,
  getDefensiveAutopilotLineKey: (...args) => getDefensiveAutopilotLineKey(...args),
  getDefensivePhaseKey: (...args) => getDefensivePhaseKey(...args),
  getFootUsageScore,
  getGoalkeeperForTeam: (...args) => getGoalkeeperForTeam(...args),
  getNearestOpponentGap,
  getOffensiveAutopilotProfile: (...args) => getOffensiveAutopilotProfile(...args),
  getOffensiveRoleKey: (...args) => getOffensiveRoleKey(...args),
  getOtherTeamId: (...args) => getOtherTeamId(...args),
  getPitchLaneIndex: (...args) => getPitchLaneIndex(...args),
  getPitchLaneKey: (...args) => getPitchLaneKey(...args),
  getPlannedPossessionTeamId: (...args) => getPlannedPossessionTeamId(...args),
  getPlayerBallControlPoint, getPlayerById, getPlayerDecisionContext,
  getPlayerFacingAngle, getPlayerMagnetLabel, getPlayerPressureLoad,
  getPlayerTendency, getTeamAttackAngle,
  getTeamSupportCountAroundPoint: (...args) => getTeamSupportCountAroundPoint(...args),
  getWideSideSign: (...args) => getWideSideSign(...args),
  isFrontLineRole: (...args) => isFrontLineRole(...args),
  isSupportRole: (...args) => isSupportRole(...args),
  keepSecurePossessionOnlyForOwner: (...args) => keepSecurePossessionOnlyForOwner(...args),
  lerp, moveTowards, normalize,
  normalizeAngle, pitch, pitchSurfacePresets,
  playerRadiusMeters, projectPointOnSegmentWithRatio, rotatePlayerBodyTowardAngle,
  setSecurePossessionAfterControlledTouch: (...args) => setSecurePossessionAfterControlledTouch(...args),
  subtract, teams,
  uniquePrincipleLabels: (...args) => uniquePrincipleLabels(...args),
  vec, weatherPresets, getState,
});

const {
  applyBallExecutionProfile,
  getLooseBallClaimScore,
  getShotReboundClaimContext,
  getShotReboundClaimAdjustment,
  getBallContestControlScore,
  getAerialPresence,
  getAerialContestScore,
  getAerialFirstContactContext,
  getAerialFirstContactScore,
  getAerialDefensiveClearanceAngle,
  getAerialAttackingKnockdownAngle,
  getAerialControlScore,
  getBallDuelScore,
  clearSecurePossession,
  getBallWinEscapeTouch,
  applyBallWinEscapeTouch,
  setSecurePossessionAfterBallWin,
  getPossessionShieldOpponents,
  setSecurePossessionAfterControlledTouch,
  keepSecurePossessionOnlyForOwner,
  getSecurePossessionContext,
  getDribbleTackleCandidate,
  getDribbleFoulCandidate,
  completeDribbleFoulRestart,
  resolveDribbleDefensiveChallenge,
  resolveLooseBallClaim,
  connectBallToPlayerForNextAction,
  applyShotReboundControlTouch,
  keepBallPlayableForNextAction,
  createLooseBallSpill,
  resolveShotBlockCommitment,
  resolvePassTransitInterception,
  resolveAerialArrivalContest,
  shouldTriggerLandingBounce,
  startLandingBounceSkid,
  settleBallForNextAction,
} = createGameSimulatorBallResolutionRuntime({
  angleBetween, angleDifference, applyCommittedSnapshot,
  applyControlledFirstTouch, blendAngles, captureSnapshot,
  clamp, clampToPitch,
  clearAutoPilotReceiveMomentum: (...args) => clearAutoPilotReceiveMomentum(...args),
  cloneSnapshot, cloneVector,
  completeLiveActionPlayersBeforeCommit: (...args) => completeLiveActionPlayersBeforeCommit(...args),
  computePassLaneClarity, computeShotLaneClarity,
  computeTimeToCoverDistance: (...args) => computeTimeToCoverDistance(...args),
  configureBallTravelProfile: (...args) => configureBallTravelProfile(...args),
  distance,
  finalizeCurrentActionStep: (...args) => finalizeCurrentActionStep(...args),
  formatTime, getActionInitiator, getAttackDirectionSign,
  getAutoPilotRoleStrength: (...args) => getAutoPilotRoleStrength(...args),
  getBallFlightControlFactor, getBallTravelProgress, getCoverShadowInfluence,
  getDefensiveAggressionPreset,
  getDistanceFromOwnGoal: (...args) => getDistanceFromOwnGoal(...args),
  getFirstTouchModeLabel, getFootUsageScore, getLiveDribbleSpeed,
  getNearestOpponentGap,
  getOffensiveRoleKey: (...args) => getOffensiveRoleKey(...args),
  getOpponentGoalCenter, getOpponentPenaltySpot, getOrientationMovementProfile,
  getOtherTeamId: (...args) => getOtherTeamId(...args),
  getOwnGoalCenter, getPitchSurfacePreset, getPitchThreatProfile,
  getPlannedPossessionTeamId: (...args) => getPlannedPossessionTeamId(...args),
  getPlayerBallControlPoint, getPlayerById, getPlayerDecisionContext,
  getPlayerFacingAngle, getPlayerMagnetLabel, getPlayerPositionForControlPoint,
  getPlayerPressureLoad, getReceiveFootUsageScore, getReceiveOrientationScore,
  getShotWindowProfile, getTeamAttackAngle, getTeamAttackStyleKey,
  getWeatherPreset, isAerialFlightStyle, isGoalkeeper,
  isInsideOpponentBox, isInsideOwnBox,
  isTransitionAttackStyle: (...args) => isTransitionAttackStyle(...args),
  lerp, logEvent, normalize,
  normalizeAngle, pitch, placePlayerWithControlPoint,
  playerRadiusMeters, projectPointOnSegment, projectPointOnSegmentWithRatio,
  queueNextSequenceStep: (...args) => queueNextSequenceStep(...args),
  rotatePlayerBodyToward,
  scheduleAutoPilotContinuation: (...args) => scheduleAutoPilotContinuation(...args),
  setPiecePhaseProfiles, shouldUseAutoPilotActiveFirstTouch, teams,
  ui, getState,
});

const {
  alignArrivedDefensiveAutopilotPlayers, applyAttackingBoxOccupationChainTargets, applyAutopilotTargetVariation,
  applyAutopilotsForCurrentAction, applyBallNearSupportTriangleTargets, applyBetweenLinesPrincipleTargets,
  applyBlindsideChannelRunTargets, applyBoxOccupationPrincipleTargets, applyCornerDeliveryPrincipleTargets,
  applyDefensiveAutoV2AntiMagnetRelationships, applyDefensiveAutoV2BackLineRelationship, applyDefensiveAutoV2MidfieldPressCover,
  applyDefensiveAutoV2PressTether, applyDefensiveAutoV2RelationshipLayer, applyDefensiveAutopilotForCurrentAction,
  applyDefensiveBackLineHandoverTargets, applyDefensiveBoxDeliveryChainTargets, applyDefensiveCarryContainmentTargets,
  applyDefensiveCentralAccessGateTargets, applyDefensiveChanceDenialTargets, applyDefensiveCornerSetPieceTargets,
  applyDefensiveEmergencyCoverTargets, applyDefensiveFreeKickSetPieceTargets, applyDefensiveGameSpaceResponseTargets,
  applyDefensiveGoalkeeperShotSetTarget, applyDefensiveGoalkeeperSweeperTarget, applyDefensiveLineBreakAdvantageCollapseTargets,
  applyDefensiveLocalOverloadResponseTargets, applyDefensiveLooseBallRecoveryTrapTargets, applyDefensiveOpenPlayTriggerTargets,
  applyDefensivePassLaneDenialTargets, applyDefensivePenaltySetPieceTargets, applyDefensivePostRecoveryResponseTargets,
  applyDefensivePressChainSupportTargets, applyDefensivePresserAngleTarget, applyDefensivePressureCoverBalanceTargets,
  applyDefensivePrioritySpaceProtectionTargets, applyDefensiveReceiveContinuationTargets, applyDefensiveReceptionTrapTargets,
  applyDefensiveRouteAnticipationTargets, applyDefensiveRunnerTrackingTargets, applyDefensiveSecondBallAnticipationTargets,
  applyDefensiveSwitchLandingLockTargets, applyDefensiveSwitchRecoveryTargets, applyDefensiveThrowInSetPieceTargets,
  applyFormationIdentityPrincipleTargets, applyGameSpaceOffBallPrincipleTargets, applyGenerativePrincipleSupportTargets,
  applyGoalkeeperBuildOutPressTargets, applyGoalkeeperBuildOutPrincipleTargets, applyHighValueSpacePrincipleTargets,
  applyLocalSuperioritySupportTargets, applyLooseBallRecoverySupportTargets, applyNegativeTransitionDefensiveTargets,
  applyOffensiveAutoV2RelationshipLayer, applyOffensiveAutopilotForCurrentAction, applyOffensivePassingGeometryTargets,
  applyOffensiveRestDefenceNetTargets, applyOffensiveSecondBallAnticipationTargets, applyOpenGrassCarrySupportTargets,
  applyOpponentBlockResponsiveTargets, applyPasserContinuationTargets, applyPositionalPlayOccupationTargets,
  applyPossessionRoutePrincipleTargets, applyPostRecoveryAttackSupportTargets, applyPressEscapeContinuationTargets,
  applyPressResistanceEscapeSupportTargets, applyReachableDefensiveLineCohesion, applyReceptionSupportPrincipleTargets,
  applyShotReboundPrincipleTargets, applySpaceTwoContinuationTargets, applySpaceTwoForwardFacingTargets,
  applySwitchLandingAttackTargets, applyThirdManChainSupportTargets, applyTimedFinalThirdBoxArrivals,
  applyTransitionAttackPrincipleTargets, buildAutoPilotBetweenLinesCandidate, buildAutoPilotBoxDeliveryCandidate,
  buildAutoPilotCornerCandidate, buildAutoPilotDangerZoneEscapeCandidate, buildAutoPilotDribbleCandidate,
  buildAutoPilotFinalThirdCombinationCandidate, buildAutoPilotFreeKickCandidate, buildAutoPilotGoalkeeperDistributionCandidate,
  buildAutoPilotKickoffCandidate, buildAutoPilotPassCandidates, buildAutoPilotPenaltyCandidate,
  buildAutoPilotPostKickoffResetCandidate, buildAutoPilotPressedRegainExitCandidate, buildAutoPilotPressureTrapEscapeCandidate,
  buildAutoPilotRegainReleaseCandidate, buildAutoPilotShotCandidate, buildAutoPilotSwitchLandingContinuationCandidate,
  buildAutoPilotThroughBallCandidate, buildAutoPilotThrowInCandidate, buildAutoPilotWideOverlapCandidate,
  buildDefensiveAutoV2Intents, buildDefensiveAutopilotTargets, buildMovementPath,
  buildOffensiveAutoV2Intents, buildOffensiveAutopilotTargets, chooseAutoPilotNextAction,
  chooseBlindsideChannelRunner, chooseCornerDeliveryRunner, chooseDefensiveAutopilotPresser,
  chooseDefensiveDribblePresser, chooseFreeKickShortReceiver, chooseOffensiveAutopilotRunner,
  chooseTimedBoxArrivalPlayer, chooseWideOverlapRunner, clampToCircle,
  cloneAutoV2DecisionTriggers, cloneDefensiveAutopilotIntents, cloneOffensiveAutopilotIntents,
  completeLiveActionPlayersBeforeCommit, computeReachDistance, computeTimeToCoverDistance,
  configureBallTravelProfile, createAutoPilotOpeningVariation, createAutoPilotPossessionPlan,
  createAutoPilotPossessionRoute, createTransitionPlan, enforceDefensiveBlockGeometryLock,
  enforceDefensiveCollectiveShiftCohesion, enforceDefensiveCompactLineIntegrity, enforceDefensiveLineChainSpacing,
  enforceDefensiveLineStaggering, enforceDefensiveMeasuredBlockEnvelope, enforceDefensiveOffsideLineControl,
  enforceDefensiveUnitCompactness, enforceDefensiveVerticalBlockConnections, enforceOffensiveFiveLaneOccupation,
  enforceOffensiveOccupationZones, enforceOffensiveOnsideLineAwareness, enforceOffensiveStructureBalance,
  enforceOffensiveTargetSpacing, estimateAutoPilotCandidateDuration, getActionDistance,
  getActionSpeed, getActualLocalSuperiorityProfile, getAttackingBoxOccupationChainContext,
  getAttackingBoxOccupationChainTarget, getAttackingThirdKey, getAutoPilotAdvantageLifecycleAdjustment,
  getAutoPilotAdvantageLifecycleContext, getAutoPilotAdvantageRetentionAdjustment, getAutoPilotAdvantageRetentionContext,
  getAutoPilotBoxTarget, getAutoPilotCandidatePattern, getAutoPilotCandidatePrincipleMetrics,
  getAutoPilotCandidateReceiver, getAutoPilotCarryEndProductAdjustment, getAutoPilotCarryEndProductContext,
  getAutoPilotChanceHierarchyAdjustment, getAutoPilotChanceHierarchyContext, getAutoPilotCombinationChainAdjustment,
  getAutoPilotCombinationChainContext, getAutoPilotCorridorTempoReleaseAdjustment, getAutoPilotCounterPressEscapeAdjustment,
  getAutoPilotDribbleTarget, getAutoPilotEndProductUrgencyAdjustment, getAutoPilotEndProductUrgencyContext,
  getAutoPilotFlowAdjustment, getAutoPilotFlowContext, getAutoPilotIntentionModel,
  getAutoPilotLaneRealityAdjustment, getAutoPilotLineBreakAdvantageAdjustment, getAutoPilotLocalSuperiorityAdjustment,
  getAutoPilotLocalSuperiorityProfile, getAutoPilotNextSupportNetworkAdjustment, getAutoPilotNextSupportNetworkProfile,
  getAutoPilotOpeningVariationAdjustment, getAutoPilotOpponentBlockReadAdjustment, getAutoPilotPassLaneDenialAdjustment,
  getAutoPilotPatternDiversityAdjustment, getAutoPilotPlanRepeatPenalty, getAutoPilotPossessionIntentAdjustment,
  getAutoPilotPossessionIntentContext, getAutoPilotPossessionIntentFit, getAutoPilotPossessionLoopAdjustment,
  getAutoPilotPossessionPlan, getAutoPilotPossessionRouteStage, getAutoPilotPossessionStartIndex,
  getAutoPilotPostRecoveryPhaseAdjustment, getAutoPilotPostRecoveryPhaseContext, getAutoPilotPressureEscapeAdjustment,
  getAutoPilotPressureEscapeContext, getAutoPilotPrincipleAdjustment, getAutoPilotReceivePressureTrapAdjustment,
  getAutoPilotReceiverAvailabilityAdjustment, getAutoPilotRecoveryFirstActionAdjustment, getAutoPilotRecoveryFirstActionContext,
  getAutoPilotRegainContext, getAutoPilotRepetitionPenalty, getAutoPilotRhythmGovernorAdjustment,
  getAutoPilotRoleResponsibilityAdjustment, getAutoPilotShotTarget, getAutoPilotSpaceLadderAdjustment,
  getAutoPilotSpaceLadderContext, getAutoPilotSpacingBonus, getAutoPilotStyleIntentSequence,
  getAutoPilotStylePrincipleWeights, getAutoPilotTempoPhaseAdjustment, getAutoPilotTempoPhaseContext,
  getAutoPilotTransitionNumbersAdjustment, getAutoPilotTransitionNumbersContext, getAutoPilotVisionScanAdjustment,
  getAutopilotTargetVariationRadius, getBallNearSupportTriangleTarget, getBlindsideChannelRunContext,
  getBlindsideChannelRunTarget, getBoxOccupationTarget, getCornerDeliveryTarget,
  getCurvedRecoveryWaypoint, getDefendingDirectionSign, getDefensiveAngledPressTarget,
  getDefensiveAutoV2FrameDt, getDefensiveAutoV2Intent, getDefensiveAutopilotFocusPoint,
  getDefensiveAutopilotGroupsForTeam, getDefensiveAutopilotLineKey, getDefensiveAutopilotProfile,
  getDefensiveBackLineHandoverContext, getDefensiveBoxDeliveryChainContext, getDefensiveBoxDeliveryChainTarget,
  getDefensiveCarryContainmentContext, getDefensiveCarryContainmentTarget, getDefensiveCentralAccessGateContext,
  getDefensiveCentralAccessGateTarget, getDefensiveChanceDenialContext, getDefensiveChanceDenialTarget,
  getDefensiveCompactLineIntegritySettings, getDefensiveCornerContext, getDefensiveCornerTarget,
  getDefensiveDribblePressTarget, getDefensiveEmergencyCoverContext, getDefensiveEmergencyCoverTarget,
  getDefensiveFreeKickContext, getDefensiveFreeKickTarget, getDefensiveGameSpaceResponseContext,
  getDefensiveGameSpaceResponseTarget, getDefensiveGoalkeeperShotSetContext, getDefensiveGoalkeeperShotSetTarget,
  getDefensiveGoalkeeperSweeperContext, getDefensiveGoalkeeperTarget, getDefensiveLineActionAdjustment,
  getDefensiveLineActionLabels, getDefensiveLineBreakAdvantageContext, getDefensiveLineBreakAdvantageTarget,
  getDefensiveLineCenterY, getDefensiveLineDistanceFromOwnGoal, getDefensiveLineWidth,
  getDefensiveLineX, getDefensiveLocalOverloadContext, getDefensiveLocalOverloadTarget,
  getDefensiveLooseBallRecoveryTrapContext, getDefensiveLooseBallRecoveryTrapTarget, getDefensiveOffsideLineControlContext,
  getDefensiveOpenPlayTriggerContext, getDefensiveOpenPlayTriggerTarget, getDefensivePassLaneDenialContext,
  getDefensivePassLaneDenialTarget, getDefensivePenaltyContext, getDefensivePenaltyTarget,
  getDefensivePhaseKey, getDefensivePostRecoveryOutletOptions, getDefensivePostRecoveryResponseContext,
  getDefensivePostRecoveryResponseTarget, getDefensivePressChainSupportContext, getDefensivePressChainSupportTarget,
  getDefensivePressTarget, getDefensivePressureCoverContext, getDefensivePressureCoverTarget,
  getDefensivePrioritySpacePoint, getDefensiveReceiveContinuationContext, getDefensiveReceiveContinuationNextPoint,
  getDefensiveReceiveContinuationTarget, getDefensiveReceptionTrapContext, getDefensiveReceptionTrapTarget,
  getDefensiveRouteAnticipationContext, getDefensiveRouteAnticipationTarget, getDefensiveRunnerThreats,
  getDefensiveRunnerTrackingTarget, getDefensiveSecondBallAnticipationTarget, getDefensiveSwitchLandingLockContext,
  getDefensiveSwitchLandingLockTarget, getDefensiveSwitchRecoveryContext, getDefensiveSwitchRecoveryTarget,
  getDefensiveThreatResponse, getDefensiveThrowInContext, getDefensiveThrowInTarget,
  getDefensiveUnitGap, getDepthPoint, getDepthX,
  getDistanceFromOwnGoal, getDribblePressureReference, getEditableRadius,
  getFinalThirdCombinationVariants, getFiveLaneOccupationCandidates, getFiveLaneOccupationSlotTarget,
  getFormationIdentityTarget, getFreeKickDeliveryTarget, getFreeKickWallTarget,
  getGameSpaceOffBallTarget, getGoalkeeperBuildOutPressContext, getGoalkeeperBuildOutPressTarget,
  getGoalkeeperBuildOutSupportTarget, getGoalkeeperDirectReleaseTarget, getGoalkeeperDistributionPressure,
  getHighValueAttackTarget, getKickoffOpeningCandidateFit, getLaneCenterY,
  getLaneForSideSign, getLastAutoPrincipleSet, getLastKickoffOpeningProfile,
  getLastSwitchLandingActionContext, getLiveDefensiveDribblePressTarget, getLocalSuperioritySupportTarget,
  getLooseBallRecoverySupportTarget, getMovableAutopilotPlayerByRoles, getMovableAutopilotPlayerByRolesOnSide,
  getMovementPathPoint, getNegativeTransitionContext, getNegativeTransitionOutletOptions,
  getNegativeTransitionTarget, getNextSupportSlotRoleFit, getOffBallCounterMovementWaypoint,
  getOffensiveActionPrinciple, getOffensiveAutoV2Intent, getOffensiveAutopilotFocusPoint,
  getOffensiveAutopilotProfile, getOffensiveAutopilotTarget, getOffensiveLaneY,
  getOffensiveOnsideLineContext, getOffensivePassingGeometryContext, getOffensivePassingGeometryTarget,
  getOffensivePhaseKey, getOffensiveRestDefenceNetContext, getOffensiveRestDefenceNetTarget,
  getOffensiveRoleKey, getOffensiveSecondBallAnticipationTarget, getOffensiveStructureBalanceTarget,
  getOpenGrassCarrySupportTarget, getOpponentBlockOccupationTarget, getOpponentBlockReadProfile,
  getOtherTeamId, getPasserContinuationTarget, getPitchLaneIndex,
  getPitchLaneKey, getPlannedPossessionTeamId, getPlayerRoleModel,
  getPositionalPlayOccupationTarget, getPossessionRhythmContext, getPossessionRouteOccupationTarget,
  getPostRecoveryAttackSupportContext, getPostRecoveryAttackSupportTarget, getPressEscapeContinuationTarget,
  getPressResistanceEscapeTarget, getPressedRegainExitVector, getReceiverAvailabilityProfile,
  getRecentAutoPilotPlanMemory, getRecentLaneRepeatCount, getRecentPossessionSteps,
  getReceptionSupportTarget, getRecordedStepActorIds, getRecordedStepDuration,
  getRecordedStepEndSnapshot, getRecordedStepPattern, getRecordedStepPossessionTeamId,
  getRequestedActionMode, getRestartActionMeta, getSameSideWideBacks,
  getSecondBallAnticipationContext, getSecurePossessionSnapshotForTeam, getShotReboundGeometryContext,
  getShotReboundTarget, getSideLaneKeys, getSnapshotPlayerMap,
  getSpaceTwoContinuationContext, getSpaceTwoContinuationTarget, getSpaceTwoForwardFacingTarget,
  getStepReceiverRoleKey, getStructureBalanceCandidates, getSupportUnderBallTarget,
  getSwitchLandingAttackContext, getSwitchLandingAttackTarget, getTargetLocalSuperiorityProfile,
  getTeamSupportCountAroundPoint, getThirdManRunnerTarget, getTimedBoxArrivalContext,
  getTimedBoxArrivalTarget, getTransitionAttackTarget, getUniversalFootballDecisionAdjustment,
  getWideEntryPrincipleContext, getWideOverlapPrincipleFit, getWideOverlapRunTarget,
  getWideSideSign, invalidateAutoPilotPossessionPlan, isDefensiveAutopilotPlayer,
  isDefensiveDribblePresser, isFrontLineRole, isLastStepKickoffResetForTeam,
  isOffensiveAutopilotPlayer, isSupportRole, isTransitionAttackStyle,
  isWidePrincipleZone, mergeIntentionWeights, moveDefensiveAutoV2Player,
  moveOffensiveAutoV2Player, pickDefensiveAutopilotPlayer, pickDefensiveProtectionPlayer,
  pickOffensiveAutoV2Player, principleSetIncludes, rememberAutoPilotPossessionPlan,
  resolveOpeningVariationLanes, resolvePossessionRouteLanes, scanAutoV2DecisionTriggers,
  scoreAutoPilotCandidateByIntentions, setAutopilotPrincipleTarget, setReachableDefensiveAutoV2Target,
  setReachableOffensiveAutoV2Target, shouldSkipOffensiveAutopilotPlayer, shouldUseCurvedRecoveryRun,
  shouldUseOffBallCounterMovementRun, snapshotsMatch, uniquePrincipleLabels,
  weightOffensiveAutoV2Intent,
} = createGameSimulatorAutopilotRuntime({
  addPointNoise,
  angleBetween,
  angleDifference,
  ballRadiusMeters,
  buildAutoPilotReceiveContinuationCandidate,
  buildPlayerIntelligenceProfile,
  chooseScoredCandidateWithVariation,
  chooseWeightedOption,
  clamp,
  clampToPitch,
  cloneRestartPhase,
  cloneVector,
  computePassLaneClarity,
  defensiveAutopilotProfiles,
  defensivePhaseProfiles,
  distance,
  gameRoleProfiles,
  getActionInitiator,
  getActionOrigin,
  getActionSpaceValue,
  getActionThreatGain,
  getAttackDirectionSign,
  getAttackStyleRhythmProfile,
  getAttackingDepth,
  getAttackingGameSpaceProfile,
  getAutoPilotFirstActionAfterReceiveAdjustment,
  getAutoPilotGameSpaceAdjustment,
  getAutoPilotPossessionPlayer: (...args) => getAutoPilotPossessionPlayer(...args),
  getAutoPilotReceiveFlowAdjustment,
  getAutoPilotReceiveMomentumAdjustment,
  getAutoPilotRoleStrength: (...args) => getAutoPilotRoleStrength(...args),
  getAutoPilotSpaceDominanceAdjustment,
  getAutoPilotSpaceTwoAdvantageAdjustment,
  getAutoPilotSpatialDecisionAdjustment,
  getBallTravelProgress,
  getBreakawayCarryTarget,
  getCarryLaneOpenSpaceScore,
  getCarryRunwayProfile,
  getCornerKickSpot,
  getCoverShadowInfluence,
  getCurrentActionDuration,
  getFootUsageScore,
  getFormationPositions,
  getForwardFacingSpaceTwoContext,
  getForwardProgressionWindow,
  getGoalMouthTarget,
  getGoalkeeperTargetOpenness,
  getKickoffDefensivePhaseKey,
  getKickoffSupportId,
  getNearestOpponentGap,
  getNearestOpponentGapInCarryLane,
  getNearestOpponentGapToPoint,
  getOpenGrassCarryContext,
  getOpponentDensityAtPoint,
  getOpponentGoalCenter,
  getOpponentLineDepthsForAttackingTeam,
  getOpponentPenaltySpot,
  getOpponentPressureAtPoint,
  getOrientationMovementProfile,
  getOrientationTurnDelay,
  getOwnGoalCenter,
  getPassLaneRiskProfile,
  getPitchSpaceProfile,
  getPitchSurfacePreset,
  getPitchThreatProfile,
  getPlayerBallControlPoint,
  getPlayerById,
  getPlayerDecisionContext,
  getPlayerFacingAngle,
  getPlayerMagnetLabel,
  getPlayerPressureLoad,
  getPlayerTendency,
  getPotentialPassReceiverAtTarget,
  getProjectedActionDuration,
  getReceiveFootUsageScore,
  getReceiveOrientationScore,
  getRunwayCarryTarget,
  getSecondLastOpponentLineX,
  getShotAngleQuality,
  getShotWindowProfile,
  getState,
  getTeamAttackAngle,
  getTeamAttackStyleKey,
  getTeamAttackStyleProfile,
  getTeamDefenseStyleKey,
  getTeamDefenseStyleProfile,
  getTeamDensityAtPoint,
  getWeatherPreset,
  hasBallAction,
  isAerialFlightStyle,
  isBylineZone,
  isGoalkeeper,
  isInsideOpponentBox,
  isInsideOwnBox,
  isPassReceiverOffside,
  isPlayerFacingForward,
  isWideChannel,
  kickoffOpeningProfiles,
  lerp,
  logEvent,
  materializeBallProfile,
  moveTowards,
  normalize,
  normalizeAngle,
  offensiveAutopilotProfiles,
  offensivePhaseProfiles,
  pitch,
  playerRadiusMeters,
  possessionRhythmDefaults,
  projectPointOnSegmentWithRatio,
  randomBetween,
  randomSign,
  resolveBallActionProfile,
  resolveBallCurveDirection,
  resolveShotTarget,
  rotatePlayerBodyAlongMovement,
  rotatePlayerBodyToward,
  teamRosterOrder,
  teams,
  updateActionPlayers: (...args) => updateActionPlayers(...args),
  vec,
  win,
});

const {
  getAutoPilotRoleStrength,
  getAutoPilotPossessionPlayer,
  getLooseBallRecoveryTarget,
  getSecondBallReactionAdjustment,
  getLooseBallRecoveryStructureAdjustment,
  getLooseBallNearestOpponent,
  getLooseBallCollectControlTouch,
  applyLooseBallCollectControlTouch,
  chooseAutoPilotLooseBallRecovery,
  issueLooseBallRecoveryCommand,
  describeAutoPilotChoice,
  planAutoPilotNextAction,
  cancelAutoPilotContinuation,
  pauseAutoPilotPlay,
  getAutoPilotContinuationContext,
  getAutoPilotContinuationDelay,
  scheduleAutoPilotContinuation,
  refreshPlannedBallActionProfile,
  clearBallAction,
  setBallOwner,
  issuePassLikeCommand,
  issuePassCommand,
  issueShotCommand,
  issueDribbleCommand,
  issueBallCommand,
  detectShotGoal,
  detectShotOutOfPlay,
  detectTouchlineOutOfPlay,
  getGoalkeeperForTeam,
  getPreferredParrySafetyPlayer,
  getGoalkeeperParryProfile,
  resolveGoalkeeperSave,
  registerGoalFlash,
  completeGoalkeeperSave,
  completeShotGoal,
  completeShotOutOfPlay,
  completeTouchlineOutOfPlay,
  updateBall,
  updateDribble,
  updateLooseBallRecovery,
  updateActionPlayers,
  updateSequenceActionPlayers,
  updateLiveActionPlayers,
  updateSequenceTransition,
  stepSimulation,
  getBallStatus,
  getActionTypeLabel,
  describeStep,
  getSequenceStartSnapshot,
  getSequenceFrameSnapshot,
  persistCurrentFrameSnapshot,
  finalizeCurrentActionStep,
} = createGameSimulatorCommandRuntime({
  angleBetween, applyAutopilotsForCurrentAction, applyBallExecutionProfile,
  applyBestReceiveBodyAngle, applyCommittedSnapshot, applyCornerSetup,
  applyFreeKickSetup, applyGoalKickSetup, applyKickoffSetup,
  applyPenaltySetup, applyResolvedBallProfile, applySnapshot,
  applyThrowInSetup, ballRadiusMeters, buildMovementPath,
  canEditScenario, captureSnapshot, chooseAutoPilotNextAction,
  clamp, clampToPitch, clearAutoPilotReceiveMomentum,
  clearKeyboardActionGrace, clearSecurePossession, cloneAutoV2DecisionTriggers,
  cloneDefensiveAutopilotIntents, cloneGoalEvent, cloneOffensiveAutopilotIntents,
  cloneRestartPhase, cloneShotPlacement, cloneSnapshot,
  cloneVector, completeLiveActionPlayersBeforeCommit, computeReachDistance,
  computeTimeToCoverDistance, configureBallTravelProfile, connectBallToPlayerForNextAction,
  createCommittedSnapshotFromCurrentState, createLooseBallSpill, defaultKickoffTeamId,
  distance, executePlannedAction, finishSequencePlayback,
  formatSpeed, formatTime, getActionInitiator,
  getActionOrigin, getActionSpeed, getAttackDirectionSign,
  getAttackingDepth, getAutoPilotFlowContext, getAutoPilotReceiveMomentum,
  getBallOwner, getBallFlightControlFactor, getBallTravelPoint,
  getDefensiveAutoV2Intent, getDefensiveAutopilotFocusPoint, getDribbleCarryPathPoint,
  getFirstTouchModeLabel, getGoalDirectionSign, getGoalLineX,
  getGoalNetDisplayPoint, getLiveDefensiveDribblePressTarget, getLiveDribbleSpeed,
  getMovementPathPoint, getOffensiveAutoV2Intent, getOffensiveAutopilotFocusPoint,
  getOffensiveAutopilotProfile, getOffensiveRoleKey, getOffsideInfo,
  getOpponentGoalCenter, getOpponentGoalSide, getOpponentPenaltySpot,
  getOpponentPressureAtPoint, getOtherTeamId, getPitchThreatProfile,
  getPlannedPossessionTeamId, getPlayerById, getPlayerBallControlPoint,
  getPlayerDecisionContext, getPlayerMagnetLabel, getPlayerPositionForControlPoint,
  getPlayerPressureLoad, getPlayerRoleModel, getPlayerTendency,
  getRecordedStepEndSnapshot, getRequestedActionMode, getSelectedPlayer,
  getTeamAttackAngle, getTeamSupportCountAroundPoint, hasBallAction,
  isBetweenGoalPosts, isDefensiveAutopilotPlayer, isDefensiveDribblePresser,
  isGoalkeeper, isInsideOpponentBox, isInsideOwnBox,
  isOffensiveAutopilotPlayer, isWideChannel, keepSecurePossessionOnlyForOwner,
  lerp, logEvent, markSequenceDirty,
  moveDefensiveAutoV2Player, moveOffensiveAutoV2Player, moveTowards,
  normalize, pauseLiveSimulation, pitch,
  queueNextSequenceStep, randomBetween, render,
  resetPlayerMovementProgress, resolveBallActionProfile, resolveDribbleDefensiveChallenge,
  resolveLooseBallClaim, resolvePassTransitInterception, resolveShotBlockCommitment,
  resolveShotTarget, rotatePlayerBodyAlongMovement, rotatePlayerBodyToward,
  rotatePlayerBodyTowardAngle, setDribbleCarryPathForBall, setPiecePhaseProfiles,
  setSecurePossessionAfterControlledTouch, setSelectedPlayers, settleBallForNextAction,
  shouldTriggerLandingBounce, startLandingBounceSkid, startRecordedAction,
  teams, ui, updateBallFlightHeight,
  updateSequenceButtons, win, getState,
});
return {
  addPointNoise, alignArrivedDefensiveAutopilotPlayers, angleBetween,
  angleDifference, applyAttackingBoxOccupationChainTargets, applyAutopilotTargetVariation,
  applyAutopilotsForCurrentAction, applyBallExecutionProfile, applyBallNearSupportTriangleTargets,
  applyBallWinEscapeTouch, applyBestReceiveBodyAngle, applyBetweenLinesPrincipleTargets,
  applyBlindsideChannelRunTargets, applyBoxOccupationPrincipleTargets, applyControlledFirstTouch,
  applyCornerDeliveryPrincipleTargets, applyCornerSetup, applyDefensiveAutoV2AntiMagnetRelationships,
  applyDefensiveAutoV2BackLineRelationship, applyDefensiveAutoV2MidfieldPressCover, applyDefensiveAutoV2PressTether,
  applyDefensiveAutoV2RelationshipLayer, applyDefensiveAutopilotForCurrentAction, applyDefensiveBackLineHandoverTargets,
  applyDefensiveBoxDeliveryChainTargets, applyDefensiveCarryContainmentTargets, applyDefensiveCentralAccessGateTargets,
  applyDefensiveChanceDenialTargets, applyDefensiveCornerSetPieceTargets, applyDefensiveEmergencyCoverTargets,
  applyDefensiveFreeKickSetPieceTargets, applyDefensiveGameSpaceResponseTargets, applyDefensiveGoalkeeperShotSetTarget,
  applyDefensiveGoalkeeperSweeperTarget, applyDefensiveLineBreakAdvantageCollapseTargets, applyDefensiveLocalOverloadResponseTargets,
  applyDefensiveLooseBallRecoveryTrapTargets, applyDefensiveOpenPlayTriggerTargets, applyDefensivePassLaneDenialTargets,
  applyDefensivePenaltySetPieceTargets, applyDefensivePostRecoveryResponseTargets, applyDefensivePressChainSupportTargets,
  applyDefensivePresserAngleTarget, applyDefensivePressureCoverBalanceTargets, applyDefensivePrioritySpaceProtectionTargets,
  applyDefensiveReceiveContinuationTargets, applyDefensiveReceptionTrapTargets, applyDefensiveRouteAnticipationTargets,
  applyDefensiveRunnerTrackingTargets, applyDefensiveSecondBallAnticipationTargets, applyDefensiveSwitchLandingLockTargets,
  applyDefensiveSwitchRecoveryTargets, applyDefensiveThrowInSetPieceTargets, applyFormationIdentityPrincipleTargets,
  applyFreeKickSetup, applyGameSpaceOffBallPrincipleTargets, applyGenerativePrincipleSupportTargets,
  applyGoalKickSetup, applyGoalkeeperBuildOutPressTargets, applyGoalkeeperBuildOutPrincipleTargets,
  applyHighValueSpacePrincipleTargets, applyKickoffSetup, applyLocalSuperioritySupportTargets,
  applyLooseBallCollectControlTouch, applyLooseBallRecoverySupportTargets, applyNearbyBallOrientation,
  applyNegativeTransitionDefensiveTargets, applyOffensiveAutoV2RelationshipLayer, applyOffensiveAutopilotForCurrentAction,
  applyOffensivePassingGeometryTargets, applyOffensiveRestDefenceNetTargets, applyOffensiveSecondBallAnticipationTargets,
  applyOpenGrassCarrySupportTargets, applyOpponentBlockResponsiveTargets, applyPasserContinuationTargets,
  applyPenaltySetup, applyPhysicalProfileToPlayers, applyPositionalPlayOccupationTargets,
  applyPossessionRoutePrincipleTargets, applyPostRecoveryAttackSupportTargets, applyPressEscapeContinuationTargets,
  applyPressResistanceEscapeSupportTargets, applyReachableDefensiveLineCohesion, applyReceptionSupportPrincipleTargets,
  applyResolvedBallProfile, applyShotReboundControlTouch, applyShotReboundPrincipleTargets,
  applySpaceTwoContinuationTargets, applySpaceTwoForwardFacingTargets, applySwitchLandingAttackTargets,
  applyThirdManChainSupportTargets, applyThrowInSetup, applyTimedFinalThirdBoxArrivals,
  applyTransitionAttackPrincipleTargets, blendAngles, buildAutoPilotBetweenLinesCandidate,
  buildAutoPilotBoxDeliveryCandidate, buildAutoPilotCornerCandidate, buildAutoPilotDangerZoneEscapeCandidate,
  buildAutoPilotDribbleCandidate, buildAutoPilotFinalThirdCombinationCandidate, buildAutoPilotFreeKickCandidate,
  buildAutoPilotGoalkeeperDistributionCandidate, buildAutoPilotKickoffCandidate, buildAutoPilotPassCandidates,
  buildAutoPilotPenaltyCandidate, buildAutoPilotPostKickoffResetCandidate, buildAutoPilotPressedRegainExitCandidate,
  buildAutoPilotPressureTrapEscapeCandidate, buildAutoPilotReceiveContinuationCandidate, buildAutoPilotRegainReleaseCandidate,
  buildAutoPilotShotCandidate, buildAutoPilotSwitchLandingContinuationCandidate, buildAutoPilotThroughBallCandidate,
  buildAutoPilotThrowInCandidate, buildAutoPilotWideOverlapCandidate, buildDefensiveAutoV2Intents,
  buildDefensiveAutopilotTargets, buildDribbleCarryPath, buildMovementPath,
  buildOffensiveAutoV2Intents, buildOffensiveAutopilotTargets, buildPlayerIntelligenceProfile,
  buildPlayerSprintProfile, buildPlayerTendencyProfile, buildSampledCurvePath,
  cancelAutoPilotContinuation, chooseAutoPilotLooseBallRecovery, chooseAutoPilotNextAction,
  chooseBlindsideChannelRunner, chooseCornerDeliveryRunner, chooseDefensiveAutopilotPresser,
  chooseDefensiveDribblePresser, chooseFreeKickShortReceiver, chooseOffensiveAutopilotRunner,
  chooseScoredCandidateWithVariation, chooseTimedBoxArrivalPlayer, chooseWeightedOption,
  chooseWideOverlapRunner, clamp, clampToCircle,
  clampToPitch, clearAutoPilotReceiveMomentum, clearBallAction,
  clearSecurePossession, cloneAutoV2DecisionTriggers, cloneDefensiveAutopilotIntents,
  cloneGoalEvent, cloneOffensiveAutopilotIntents, cloneSecurePossession,
  cloneShotPlacement, cloneVector, completeDribbleFoulRestart,
  completeGoalkeeperSave, completeLiveActionPlayersBeforeCommit, completeShotGoal,
  completeShotOutOfPlay, completeTouchlineOutOfPlay, computePassLaneClarity,
  computeReachDistance, computeShotLaneClarity, computeTimeToCoverDistance,
  configureBallTravelProfile, connectBallToPlayerForNextAction, createAutoPilotOpeningVariation,
  createAutoPilotPossessionPlan, createAutoPilotPossessionRoute, createLooseBallSpill,
  createPlayer, createTransitionPlan, describeAutoPilotChoice,
  describeStep, detectShotGoal, detectShotOutOfPlay,
  detectTouchlineOutOfPlay, distance, enforceDefensiveBlockGeometryLock,
  enforceDefensiveCollectiveShiftCohesion, enforceDefensiveCompactLineIntegrity, enforceDefensiveLineChainSpacing,
  enforceDefensiveLineStaggering, enforceDefensiveMeasuredBlockEnvelope, enforceDefensiveOffsideLineControl,
  enforceDefensiveUnitCompactness, enforceDefensiveVerticalBlockConnections, enforceOffensiveFiveLaneOccupation,
  enforceOffensiveOccupationZones, enforceOffensiveOnsideLineAwareness, enforceOffensiveStructureBalance,
  enforceOffensiveTargetSpacing, estimateAutoPilotCandidateDuration, finalizeCurrentActionStep,
  formatMeters, formatSpeed, formatTime,
  getActionDistance, getActionInitiator, getActionOrigin,
  getActionSpaceValue, getActionSpeed, getActionThreatGain,
  getActionTypeLabel, getActiveMovementTarget, getActualLocalSuperiorityProfile,
  getAerialAttackingKnockdownAngle, getAerialContestScore, getAerialControlScore,
  getAerialDefensiveClearanceAngle, getAerialFirstContactContext, getAerialFirstContactScore,
  getAerialPresence, getAttackDirectionSign, getAttackingBoxOccupationChainContext,
  getAttackingBoxOccupationChainTarget, getAttackingDepth, getAttackingGameSpaceProfile,
  getAttackingThirdKey, getAutoPilotAdvantageLifecycleAdjustment, getAutoPilotAdvantageLifecycleContext,
  getAutoPilotAdvantageRetentionAdjustment, getAutoPilotAdvantageRetentionContext, getAutoPilotBoxTarget,
  getAutoPilotCandidatePattern, getAutoPilotCandidatePrincipleMetrics, getAutoPilotCandidateReceiver,
  getAutoPilotCarryEndProductAdjustment, getAutoPilotCarryEndProductContext, getAutoPilotChanceHierarchyAdjustment,
  getAutoPilotChanceHierarchyContext, getAutoPilotCombinationChainAdjustment, getAutoPilotCombinationChainContext,
  getAutoPilotContinuationContext, getAutoPilotContinuationDelay, getAutoPilotCorridorTempoReleaseAdjustment,
  getAutoPilotCounterPressEscapeAdjustment, getAutoPilotDecisionPersonalityWeight, getAutoPilotDribbleTarget,
  getAutoPilotEndProductUrgencyAdjustment, getAutoPilotEndProductUrgencyContext, getAutoPilotFirstActionAfterReceiveAdjustment,
  getAutoPilotFlowAdjustment, getAutoPilotFlowContext, getAutoPilotGameSpaceAdjustment,
  getAutoPilotIntentionModel, getAutoPilotLaneRealityAdjustment, getAutoPilotLineBreakAdvantageAdjustment,
  getAutoPilotLocalSuperiorityAdjustment, getAutoPilotLocalSuperiorityProfile, getAutoPilotNextSupportNetworkAdjustment,
  getAutoPilotNextSupportNetworkProfile, getAutoPilotOpeningVariationAdjustment, getAutoPilotOpponentBlockReadAdjustment,
  getAutoPilotPassLaneDenialAdjustment, getAutoPilotPatternDiversityAdjustment, getAutoPilotPlanRepeatPenalty,
  getAutoPilotPossessionIntentAdjustment, getAutoPilotPossessionIntentContext, getAutoPilotPossessionIntentFit,
  getAutoPilotPossessionLoopAdjustment, getAutoPilotPossessionPlan, getAutoPilotPossessionPlayer,
  getAutoPilotPossessionRouteStage, getAutoPilotPossessionStartIndex, getAutoPilotPostRecoveryPhaseAdjustment,
  getAutoPilotPostRecoveryPhaseContext, getAutoPilotPressureEscapeAdjustment, getAutoPilotPressureEscapeContext,
  getAutoPilotPrincipleAdjustment, getAutoPilotReceiveFlowAdjustment, getAutoPilotReceiveFlowContext,
  getAutoPilotReceiveMomentum, getAutoPilotReceiveMomentumAdjustment, getAutoPilotReceivePressureTrapAdjustment,
  getAutoPilotReceiverAvailabilityAdjustment, getAutoPilotRecoveryFirstActionAdjustment, getAutoPilotRecoveryFirstActionContext,
  getAutoPilotRegainContext, getAutoPilotRepetitionPenalty, getAutoPilotRhythmGovernorAdjustment,
  getAutoPilotRoleResponsibilityAdjustment, getAutoPilotRoleStrength, getAutoPilotShotTarget,
  getAutoPilotSpaceDominanceAdjustment, getAutoPilotSpaceLadderAdjustment, getAutoPilotSpaceLadderContext,
  getAutoPilotSpaceTwoAdvantageAdjustment, getAutoPilotSpacingBonus, getAutoPilotSpatialDecisionAdjustment,
  getAutoPilotStyleIntentSequence, getAutoPilotStylePrincipleWeights, getAutoPilotTempoPhaseAdjustment,
  getAutoPilotTempoPhaseContext, getAutoPilotTransitionNumbersAdjustment, getAutoPilotTransitionNumbersContext,
  getAutoPilotVisionScanAdjustment, getAutopilotTargetVariationRadius, getBallAwareBodyAngle,
  getBallContestControlScore, getBallControlOffsetMeters, getBallDuelScore,
  getBallFlightControlFactor, getBallNearSupportTriangleTarget, getBallProfileDistanceRatio,
  getBallProfileLabel, getBallStatus, getBallTravelPoint,
  getBallTravelProgress, getBallWinEscapeTouch, getBestReceiveBodyAngle,
  getBlindsideChannelRunContext, getBlindsideChannelRunTarget, getBoxOccupationTarget,
  getBreakawayCarryTarget, getCarryLaneOpenSpaceScore, getCarryRunwayProfile,
  getCarryRunwayRoleCap, getCompetitionPhysicalLabel, getCompetitionPhysicalProfile,
  getCornerDeliveryTarget, getCornerKickSpot, getCoverShadowInfluence,
  getCurrentActionDuration, getCurvedRecoveryWaypoint, getDefendingDirectionSign,
  getDefensiveAggressionPreset, getDefensiveAngledPressTarget, getDefensiveAutoV2FrameDt,
  getDefensiveAutoV2Intent, getDefensiveAutopilotFocusPoint, getDefensiveAutopilotGroupsForTeam,
  getDefensiveAutopilotLineKey, getDefensiveAutopilotProfile, getDefensiveBackLineHandoverContext,
  getDefensiveBoxDeliveryChainContext, getDefensiveBoxDeliveryChainTarget, getDefensiveCarryContainmentContext,
  getDefensiveCarryContainmentTarget, getDefensiveCentralAccessGateContext, getDefensiveCentralAccessGateTarget,
  getDefensiveChanceDenialContext, getDefensiveChanceDenialTarget, getDefensiveCompactLineIntegritySettings,
  getDefensiveCornerContext, getDefensiveCornerTarget, getDefensiveDribblePressTarget,
  getDefensiveEmergencyCoverContext, getDefensiveEmergencyCoverTarget, getDefensiveFreeKickContext,
  getDefensiveFreeKickTarget, getDefensiveGameSpaceResponseContext, getDefensiveGameSpaceResponseTarget,
  getDefensiveGoalkeeperShotSetContext, getDefensiveGoalkeeperShotSetTarget, getDefensiveGoalkeeperSweeperContext,
  getDefensiveGoalkeeperTarget, getDefensiveLineActionAdjustment, getDefensiveLineActionLabels,
  getDefensiveLineBreakAdvantageContext, getDefensiveLineBreakAdvantageTarget, getDefensiveLineCenterY,
  getDefensiveLineDistanceFromOwnGoal, getDefensiveLineWidth, getDefensiveLineX,
  getDefensiveLocalOverloadContext, getDefensiveLocalOverloadTarget, getDefensiveLooseBallRecoveryTrapContext,
  getDefensiveLooseBallRecoveryTrapTarget, getDefensiveOffsideLineControlContext, getDefensiveOpenPlayTriggerContext,
  getDefensiveOpenPlayTriggerTarget, getDefensivePassLaneDenialContext, getDefensivePassLaneDenialTarget,
  getDefensivePenaltyContext, getDefensivePenaltyTarget, getDefensivePhaseKey,
  getDefensivePostRecoveryOutletOptions, getDefensivePostRecoveryResponseContext, getDefensivePostRecoveryResponseTarget,
  getDefensivePressChainSupportContext, getDefensivePressChainSupportTarget, getDefensivePressTarget,
  getDefensivePressureCoverContext, getDefensivePressureCoverTarget, getDefensivePrioritySpacePoint,
  getDefensiveReceiveContinuationContext, getDefensiveReceiveContinuationNextPoint, getDefensiveReceiveContinuationTarget,
  getDefensiveReceptionTrapContext, getDefensiveReceptionTrapTarget, getDefensiveRouteAnticipationContext,
  getDefensiveRouteAnticipationTarget, getDefensiveRunnerThreats, getDefensiveRunnerTrackingTarget,
  getDefensiveSecondBallAnticipationTarget, getDefensiveSwitchLandingLockContext, getDefensiveSwitchLandingLockTarget,
  getDefensiveSwitchRecoveryContext, getDefensiveSwitchRecoveryTarget, getDefensiveThreatResponse,
  getDefensiveThrowInContext, getDefensiveThrowInTarget, getDefensiveUnitGap,
  getDepthPoint, getDepthQuantile, getDepthX,
  getDepthZoneKey, getDepthZoneLabel, getDeterministicShotNoise,
  getDisplayedBallSpeed, getDistanceFromOwnGoal, getDribbleCarryPathPoint,
  getDribbleFoulCandidate, getDribblePressureReference, getDribbleRoleFamily,
  getDribbleTackleCandidate, getEditableRadius, getFinalThirdCombinationVariants,
  getFirstTouchDirectionAngle, getFirstTouchDistance, getFirstTouchModeLabel,
  getFiveLaneOccupationCandidates, getFiveLaneOccupationSlotTarget, getFlightStyleLabel,
  getFootUsageScore, getFootballSpacePriority, getFormationIdentityTarget,
  getFormationPositions, getForwardFacingSpaceTwoContext, getForwardProgressionWindow,
  getFreeKickDeliveryTarget, getFreeKickWallTarget, getGameSpaceOffBallTarget,
  getGoalDirectionSign, getGoalLineX, getGoalMouthTarget,
  getGoalNetDisplayPoint, getGoalkeeperBuildOutPressContext, getGoalkeeperBuildOutPressTarget,
  getGoalkeeperBuildOutSupportTarget, getGoalkeeperDirectReleaseTarget, getGoalkeeperDistributionPressure,
  getGoalkeeperForTeam, getGoalkeeperParryProfile, getGoalkeeperTargetOpenness,
  getGoldenZoneScore, getHighValueAttackTarget, getIntelligenceArchetype,
  getKickoffDefensivePhaseKey, getKickoffOpeningCandidateFit, getKickoffSpot,
  getKickoffSupportId, getKickoffTakerId, getLaneCenterY,
  getLaneForSideSign, getLaneLabel, getLastAutoPrincipleSet,
  getLastKickoffOpeningProfile, getLastSwitchLandingActionContext, getLiveBallFocusPoint,
  getLiveDefensiveDribblePressTarget, getLiveDribbleSpeed, getLocalSuperioritySupportTarget,
  getLooseBallClaimScore, getLooseBallCollectControlTouch, getLooseBallNearestOpponent,
  getLooseBallRecoveryStructureAdjustment, getLooseBallRecoverySupportTarget, getLooseBallRecoveryTarget,
  getManualBallProfile, getMedianNumber, getMovableAutopilotPlayerByRoles,
  getMovableAutopilotPlayerByRolesOnSide, getMovementPathPoint, getNaturalDecisionDiversityWeight,
  getNearestOpponentGapInCarryLane, getNearestOpponentGapToPoint, getNegativeTransitionContext,
  getNegativeTransitionOutletOptions, getNegativeTransitionTarget, getNextSupportSlotRoleFit,
  getOffBallCounterMovementWaypoint, getOffensiveActionPrinciple, getOffensiveAutoV2Intent,
  getOffensiveAutopilotFocusPoint, getOffensiveAutopilotProfile, getOffensiveAutopilotTarget,
  getOffensiveLaneY, getOffensiveOnsideLineContext, getOffensivePassingGeometryContext,
  getOffensivePassingGeometryTarget, getOffensivePhaseKey, getOffensiveRestDefenceNetContext,
  getOffensiveRestDefenceNetTarget, getOffensiveRoleKey, getOffensiveSecondBallAnticipationTarget,
  getOffensiveStructureBalanceTarget, getOffsideInfo, getOpenGrassCarryContext,
  getOpenGrassCarrySupportTarget, getOpponentBlockOccupationTarget, getOpponentBlockReadProfile,
  getOpponentDensityAtPoint, getOpponentGoalCenter, getOpponentGoalSide,
  getOpponentLineDepthsForAttackingTeam, getOpponentPenaltySpot, getOpponentPressureAtPoint,
  getOpponentsBypassedByAction, getOrientationMovementProfile, getOrientationTurnDelay,
  getOtherTeamId, getOwnGoalCenter, getPassLaneRiskProfile,
  getPasserContinuationTarget, getPitchLaneIndex, getPitchLaneKey,
  getPitchSpaceProfile, getPitchSurfacePreset, getPitchThreatProfile,
  getPlannedPossessionTeamId, getPlayerBallControlPoint, getPlayerFacingAngle,
  getPlayerMagnetLabel, getPlayerOrientationFocus, getPlayerPositionForControlPoint,
  getPlayerRoleModel, getPlayerTeamId, getPlayerTendency,
  getPositionalPlayOccupationTarget, getPossessionRhythmContext, getPossessionRouteOccupationTarget,
  getPossessionShieldOpponents, getPostRecoveryAttackSupportContext, getPostRecoveryAttackSupportTarget,
  getPotentialPassReceiverAtTarget, getPreferredFootOffsetAngle, getPreferredParrySafetyPlayer,
  getPressEscapeContinuationTarget, getPressResistanceEscapeTarget, getPressedRegainExitVector,
  getProjectedActionDuration, getQuadraticPoint, getReceiveContinuationCarryTarget,
  getReceiveFootUsageScore, getReceiveOrientationScore, getReceiverAvailabilityProfile,
  getRecentAutoPilotPlanMemory, getRecentLaneRepeatCount, getRecentPossessionSteps,
  getReceptionSupportTarget, getRecordedStepActorIds, getRecordedStepDuration,
  getRecordedStepEndSnapshot, getRecordedStepPattern, getRecordedStepPossessionTeamId,
  getRemainingBallDistance, getRemainingBallTravelTime, getRequestedActionMode,
  getRestartActionMeta, getRunwayCarryTarget, getSameSideWideBacks,
  getSampledPathPoint, getSecondBallAnticipationContext, getSecondBallReactionAdjustment,
  getSecondLastOpponentLineX, getSecurePossessionContext, getSecurePossessionSnapshotForTeam,
  getSequenceFrameSnapshot, getSequenceStartSnapshot, getShotAngleQuality,
  getShotBlockRisk, getShotReboundClaimAdjustment, getShotReboundClaimContext,
  getShotReboundGeometryContext, getShotReboundTarget, getShotWindowProfile,
  getSideLaneKeys, getSnapshotPlayerMap, getSpaceDominanceProfile,
  getSpacePassTargetPoint, getSpaceTwoContinuationContext, getSpaceTwoContinuationTarget,
  getSpaceTwoForwardFacingTarget, getSprintArchetype, getStepReceiverRoleKey,
  getStructureBalanceCandidates, getSupportUnderBallTarget, getSwitchLandingAttackContext,
  getSwitchLandingAttackTarget, getTargetLocalSuperiorityProfile, getTeamAttackAngle,
  getTeamDensityAtPoint, getTeamSupportCountAroundPoint, getThirdManRunnerTarget,
  getTimedBoxArrivalContext, getTimedBoxArrivalTarget, getTransitionAttackTarget,
  getUniversalFootballDecisionAdjustment, getWeatherPreset, getWideEntryPrincipleContext,
  getWideOverlapPrincipleFit, getWideOverlapRunTarget, getWideSideSign,
  hasBallAction, invalidateAutoPilotPossessionPlan, isAerialFlightStyle,
  isBetweenGoalPosts, isBylineZone, isCutbackTarget,
  isDefensiveAutopilotPlayer, isDefensiveDribblePresser, isFrontLineRole,
  isGoalkeeper, isGoldenZone, isInsideOpponentBox,
  isInsideOwnBox, isLastStepKickoffResetForTeam, isOffensiveAutopilotPlayer,
  isPassReceiverOffside, isPlayerFacingForward, isPlayerReservedForReceiveShape,
  isSupportRole, isTransitionAttackStyle, isWideChannel,
  isWidePrincipleZone, issueBallCommand, issueDribbleCommand,
  issueLooseBallRecoveryCommand, issuePassCommand, issuePassLikeCommand,
  issueShotCommand, keepBallPlayableForNextAction, keepSecurePossessionOnlyForOwner,
  kickoffOpeningProfiles, lerp, materializeBallProfile,
  mergeIntentionWeights, moveDefensiveAutoV2Player, moveOffensiveAutoV2Player,
  moveTowards, normalize, normalizeAngle,
  pauseAutoPilotPlay, persistCurrentFrameSnapshot, pickDefensiveAutopilotPlayer,
  pickDefensiveProtectionPlayer, pickOffensiveAutoV2Player, placePlayerWithControlPoint,
  planAutoPilotNextAction, principleSetIncludes, projectPointOnSegment,
  projectPointOnSegmentWithRatio, randomBetween, randomSign,
  refreshPlannedBallActionProfile, registerGoalFlash, rememberAutoPilotPossessionPlan,
  resetPlayerMovementProgress, resolveAerialArrivalContest, resolveAutoBallProfile,
  resolveAutoDribbleProfile, resolveBallActionProfile, resolveBallCurveDirection,
  resolveDribbleDefensiveChallenge, resolveExecutedShotTarget, resolveFirstTouchMode,
  resolveGoalkeeperSave, resolveLooseBallClaim, resolveOpeningVariationLanes,
  resolvePassTransitInterception, resolvePossessionRouteLanes, resolveRecordedStepProfile,
  resolveShotBlockCommitment, resolveShotTarget, rotatePlayerBodyAlongMovement,
  rotatePlayerBodyToward, rotatePlayerBodyTowardAngle, scanAutoV2DecisionTriggers,
  scheduleAutoPilotContinuation, scoreAutoPilotCandidateByIntentions, setAutoPilotReceiveMomentum,
  setAutopilotPrincipleTarget, setBallOwner, setDribbleCarryPathForBall,
  setReachableDefensiveAutoV2Target, setReachableOffensiveAutoV2Target, setSecurePossessionAfterBallWin,
  setSecurePossessionAfterControlledTouch, setTeamFormationOnPlayers, settleBallForNextAction,
  shouldSkipOffensiveAutopilotPlayer, shouldTriggerLandingBounce, shouldUseAutoPilotActiveFirstTouch,
  shouldUseCurvedRecoveryRun, shouldUseOffBallCounterMovementRun, snapshotsMatch,
  startLandingBounceSkid, stepSimulation, subtract,
  uniquePrincipleLabels, updateActionPlayers, updateBall,
  updateBallFlightHeight, updateDribble, updateLiveActionPlayers,
  updateLooseBallRecovery, updateSequenceActionPlayers, updateSequenceTransition,
  vec, weightOffensiveAutoV2Intent
};
}
