export function createGameSimulatorInitialStateFactory(deps = {}) {
  const {
    applyKickoffSetup,
    cloneVector,
    createPlayer,
    defaultFormations,
    defaultKickoffTeamId,
    defaultPhysicalProfileKey,
    defaultScenarioInfo,
    getKickoffSpot,
    getKickoffTakerId,
    readSavedSequenceLibrary,
    resetTeamIdentities,
    setPiecePhaseProfiles,
    setTeamFormationOnPlayers,
    squadBlueprints,
    teams,
  } = deps;

  return function createInitialState() {
    teams.home.formation = defaultFormations.home;
    teams.away.formation = defaultFormations.away;
    resetTeamIdentities();
    const physicalProfile = defaultPhysicalProfileKey;
    const players = squadBlueprints.map((blueprint) => createPlayer(blueprint, physicalProfile));
    setTeamFormationOnPlayers(players, "home", teams.home.formation);
    setTeamFormationOnPlayers(players, "away", teams.away.formation);
    const kickoffSpot = getKickoffSpot();
    const initialState = {
      time: 0,
      dt: 0.05,
      physicalProfile,
      playbackSpeed: 1,
      surfacePreset: "hybrid-grass",
      weatherPreset: "damp",
      firstTouchMode: "auto",
      defensiveAggressionPreset: "balanced",
      goalFlash: null,
      actionMode: null,
      ballSpeedMode: "auto",
      dribbleSpeedMode: "auto",
      defensiveAutopilot: false,
      offensiveAutopilot: false,
      autoV2Debug: false,
      autoPilotPlay: {
        active: false,
        nextActionTimeoutId: null,
        possessionPlan: null,
        receiveMomentum: null,
      },
      dribbleSpeed: 4.5,
      isRunning: false,
      drag: null,
      keyboardActionMode: null,
      keyboardActionGraceMode: null,
      keyboardActionGraceUntil: 0,
      matchPhase: "setPieces",
      restartPhase: {
        type: "kickoff",
        teamId: defaultKickoffTeamId,
        label: setPiecePhaseProfiles.kickoff.label,
      },
      selectedPlayerId: getKickoffTakerId(defaultKickoffTeamId),
      selectedPlayerIds: [getKickoffTakerId(defaultKickoffTeamId)],
      eventLog: [
        "Kick-off loaded: Blue Team starts from the centre mark.",
        "Sandbox loaded: drag players, the ball, or box-select players while the simulation is paused.",
        "Press P, D or S, or arm a mode button, then click the pitch to set the target. Press Enter or Start to play it. With offensive autopilot on, Space starts or pauses auto play.",
      ],
      scenario: { ...defaultScenarioInfo },
      example: null,
      simulatorDirty: false,
      savedSequences: readSavedSequenceLibrary(),
      draftStep: null,
      activeActionTargets: null,
      sequence: {
        isPlaying: false,
        playbackIndex: -1,
        currentFrameIndex: -1,
        playbackTimeoutId: null,
        phase: null,
        transition: null,
        actionTargets: null,
        initialSnapshot: null,
        dirty: false,
        steps: [],
      },
      ball: {
        position: cloneVector(kickoffSpot),
        startPosition: cloneVector(kickoffSpot),
        target: cloneVector(kickoffSpot),
        speed: 12,
        manualSpeed: 12,
        currentSpeed: 0,
        launchSpeed: 0,
        finalSpeed: 0,
        deceleration: 0,
        profileKey: null,
        profileLabel: null,
        profileMode: "auto",
        targetKind: null,
        firstTouchMode: "auto",
        flightStyle: "ground",
        peakHeight: 0,
        height: 0,
        controlHeightThreshold: 0.12,
        landingPhaseStart: 0.58,
        curveAmount: 0,
        curveDirection: 1,
        spinRate: 0,
        spinAngle: 0,
        trackDistanceTotal: 0,
        trackDistanceCovered: 0,
        dribblePath: null,
        bounceCount: 0,
        inTransit: false,
        elapsedTravelTime: 0,
        actionType: null,
        ownerPlayerId: getKickoffTakerId(defaultKickoffTeamId),
        initiatorPlayerId: null,
        laneClarity: 0.84,
        executionQuality: 0.84,
        claimRadius: 2.2,
        controlRadius: 1.4,
        carrierPlayerId: null,
        receiverPlayerId: null,
        securePossession: null,
        recoveryDuration: 0,
        secondBallContext: null,
      },
      players,
    };
    applyKickoffSetup(initialState, {
      teamId: defaultKickoffTeamId,
      resetFormations: false,
    });
    return initialState;
  };
}
