export const pitch = {
  length: 105,
  width: 68,
  inset: 2,
};
export const teams = {
  home: {
    id: "home",
    name: "Blue Team",
    formation: "4-3-3",
    color: "#0d355d",
    accent: "#81b8ff",
    identity: {
      attackStyle: "control-possession",
      defenseStyle: "mid-block",
    },
  },
  away: {
    id: "away",
    name: "Red Team",
    formation: "3-4-3",
    color: "#a63333",
    accent: "#ff9b9b",
    identity: {
      attackStyle: "vertical-play",
      defenseStyle: "mid-block",
    },
  },
};
export const defaultTeamIdentities = {
  home: {
    attackStyle: "control-possession",
    defenseStyle: "mid-block",
  },
  away: {
    attackStyle: "vertical-play",
    defenseStyle: "mid-block",
  },
};
export const defaultPhysicalProfileKey = "elite-women";
export const competitionPhysicalProfiles = {
  "elite-women": {
    key: "elite-women",
    label: "Elite Women",
    maxSpeedMultiplier: 0.94,
    accelerationMultiplier: 0.96,
    reactionTimeMultiplier: 1.02,
    dribbleSpeedMultiplier: 0.95,
    ballPowerMultiplier: 0.96,
    roleMultipliers: {
      goalkeeper: { maxSpeedMultiplier: 0.96, accelerationMultiplier: 0.96, dribbleSpeedMultiplier: 0.92 },
      "center-back": { maxSpeedMultiplier: 0.97, accelerationMultiplier: 0.97, dribbleSpeedMultiplier: 0.94 },
      "full-back": { maxSpeedMultiplier: 0.98, accelerationMultiplier: 0.99, dribbleSpeedMultiplier: 0.97 },
      "wing-back": { maxSpeedMultiplier: 0.99, accelerationMultiplier: 1, dribbleSpeedMultiplier: 0.98 },
      winger: { maxSpeedMultiplier: 1.01, accelerationMultiplier: 1.01, dribbleSpeedMultiplier: 1 },
      striker: { maxSpeedMultiplier: 1, accelerationMultiplier: 1.01, dribbleSpeedMultiplier: 0.98 },
    },
  },
  "elite-men": {
    key: "elite-men",
    label: "Elite Men",
    maxSpeedMultiplier: 1,
    accelerationMultiplier: 1,
    reactionTimeMultiplier: 1,
    dribbleSpeedMultiplier: 1,
    ballPowerMultiplier: 1,
  },
  "academy-women": {
    key: "academy-women",
    label: "Academy Women",
    maxSpeedMultiplier: 0.88,
    accelerationMultiplier: 0.9,
    reactionTimeMultiplier: 1.08,
    dribbleSpeedMultiplier: 0.9,
    ballPowerMultiplier: 0.9,
    roleMultipliers: {
      winger: { maxSpeedMultiplier: 1.02, accelerationMultiplier: 1.02, dribbleSpeedMultiplier: 1.01 },
      striker: { maxSpeedMultiplier: 1.01, accelerationMultiplier: 1.02, dribbleSpeedMultiplier: 0.99 },
      "wing-back": { maxSpeedMultiplier: 1.01, accelerationMultiplier: 1.01, dribbleSpeedMultiplier: 1 },
    },
  },
  "academy-men": {
    key: "academy-men",
    label: "Academy Men",
    maxSpeedMultiplier: 0.94,
    accelerationMultiplier: 0.95,
    reactionTimeMultiplier: 1.04,
    dribbleSpeedMultiplier: 0.94,
    ballPowerMultiplier: 0.94,
    roleMultipliers: {
      winger: { maxSpeedMultiplier: 1.01, accelerationMultiplier: 1.01, dribbleSpeedMultiplier: 1 },
      striker: { maxSpeedMultiplier: 1.01, accelerationMultiplier: 1.01, dribbleSpeedMultiplier: 0.98 },
    },
  },
};
export const defaultKickoffTeamId = "home";
export const defaultFormations = {
  home: "4-3-3",
  away: "3-4-3",
};
export const teamRosterOrder = {
  home: ["H1", "H2", "H3", "H4", "H5", "H6", "H8", "H10", "H11", "H9", "H7"],
  away: ["A1", "A2", "A3", "A4", "A5", "A6", "A8", "A7", "A11", "A9", "A10"],
};
export const formationLayouts = {
  "4-3-3": [
    [7.5, 34],
    [20, 11],
    [18, 25],
    [18, 43],
    [20, 57],
    [33, 34],
    [40, 23],
    [40, 45],
    [55, 11],
    [60, 34],
    [55, 57],
  ],
  "4-1-4-1": [
    [7.5, 34],
    [20, 11],
    [18, 25],
    [18, 43],
    [20, 57],
    [31, 34],
    [39, 26],
    [39, 42],
    [42, 14],
    [49, 34],
    [42, 54],
  ],
  "3-4-3": [
    [7.5, 34],
    [18, 18],
    [18, 34],
    [18, 50],
    [34, 11],
    [34, 25],
    [34, 43],
    [34, 57],
    [56, 14],
    [60, 34],
    [56, 54],
  ],
  "4-4-2": [
    [7.5, 34],
    [20, 10],
    [18, 24],
    [18, 44],
    [20, 58],
    [36, 12],
    [34, 28],
    [34, 40],
    [36, 56],
    [55, 26],
    [55, 42],
  ],
  "4-2-3-1": [
    [7.5, 34],
    [20, 10],
    [18, 24],
    [18, 44],
    [20, 58],
    [31, 28],
    [31, 40],
    [46, 12],
    [47, 34],
    [46, 56],
    [60, 34],
  ],
  "3-5-2": [
    [7.5, 34],
    [18, 18],
    [18, 34],
    [18, 50],
    [34, 10],
    [34, 24],
    [36, 34],
    [34, 44],
    [34, 58],
    [58, 28],
    [58, 40],
  ],
};
export const playerRadiusMeters = 1.2;
export const ballRadiusMeters = 0.58;
export const sequenceStorageKey = "football-simulator-sequence-v1";
export const sequenceLibraryStorageKey = "football-simulator-sequence-library-v2";
export const defaultScenarioInfo = {
  title: "Scenario",
  text:
    "The starting point is a full-pitch setup with two formations. You can build your own tactical scenario by arranging the players, choosing where the ball travels next, and then reading how many metres each player can cover during the ball action.",
  meta:
    "Every pass, dribble or shot is saved automatically as a step that you can adjust, jump between and replay from the current position.",
};

export const squadBlueprints = [
  { team: "home", id: "H1", shortLabel: "GK", role: "Goalkeeper", position: [7.5, 34], maxSpeed: 5.4, acceleration: 1.9, reactionTime: 0.38 },
  { team: "home", id: "H2", shortLabel: "LB", role: "Left Back", position: [20, 11], maxSpeed: 8.1, acceleration: 2.8, reactionTime: 0.24 },
  { team: "home", id: "H3", shortLabel: "LCB", role: "Left Center Back", position: [18, 25], maxSpeed: 7.2, acceleration: 2.4, reactionTime: 0.26 },
  { team: "home", id: "H4", shortLabel: "RCB", role: "Right Center Back", position: [18, 43], maxSpeed: 7.2, acceleration: 2.4, reactionTime: 0.26 },
  { team: "home", id: "H5", shortLabel: "RB", role: "Right Back", position: [20, 57], maxSpeed: 8.2, acceleration: 2.9, reactionTime: 0.24 },
  { team: "home", id: "H6", shortLabel: "6", role: "Holding Midfielder", position: [33, 34], maxSpeed: 7.7, acceleration: 2.7, reactionTime: 0.2 },
  { team: "home", id: "H8", shortLabel: "8", role: "Right No. 8", position: [40, 45], maxSpeed: 7.9, acceleration: 2.8, reactionTime: 0.18 },
  { team: "home", id: "H10", shortLabel: "10", role: "Left No. 8", position: [40, 23], maxSpeed: 7.9, acceleration: 2.8, reactionTime: 0.18 },
  { team: "home", id: "H11", shortLabel: "LW", role: "Left Winger", position: [55, 11], maxSpeed: 8.9, acceleration: 3.2, reactionTime: 0.16 },
  { team: "home", id: "H9", shortLabel: "ST", role: "Striker", position: [60, 34], maxSpeed: 8.8, acceleration: 3.2, reactionTime: 0.16 },
  { team: "home", id: "H7", shortLabel: "RW", role: "Right Winger", position: [55, 57], maxSpeed: 9, acceleration: 3.3, reactionTime: 0.16 },
  { team: "away", id: "A1", shortLabel: "GK", role: "Goalkeeper", position: [97.5, 34], maxSpeed: 5.3, acceleration: 1.9, reactionTime: 0.38 },
  { team: "away", id: "A2", shortLabel: "LCB", role: "Left Center Back", position: [86, 18], maxSpeed: 7.2, acceleration: 2.4, reactionTime: 0.26 },
  { team: "away", id: "A3", shortLabel: "CB", role: "Center Back", position: [88, 34], maxSpeed: 7.1, acceleration: 2.3, reactionTime: 0.27 },
  { team: "away", id: "A4", shortLabel: "RCB", role: "Right Center Back", position: [86, 50], maxSpeed: 7.2, acceleration: 2.4, reactionTime: 0.26 },
  { team: "away", id: "A5", shortLabel: "LM", role: "Left Wing-Back", position: [70, 11], maxSpeed: 8.5, acceleration: 3, reactionTime: 0.22 },
  { team: "away", id: "A6", shortLabel: "8", role: "Left Central Midfielder", position: [68, 24], maxSpeed: 7.8, acceleration: 2.8, reactionTime: 0.2 },
  { team: "away", id: "A8", shortLabel: "6", role: "Right Central Midfielder", position: [68, 44], maxSpeed: 7.8, acceleration: 2.8, reactionTime: 0.2 },
  { team: "away", id: "A7", shortLabel: "RM", role: "Right Wing-Back", position: [70, 57], maxSpeed: 8.5, acceleration: 3, reactionTime: 0.22 },
  { team: "away", id: "A11", shortLabel: "LW", role: "Left Forward", position: [56, 14], maxSpeed: 8.8, acceleration: 3.1, reactionTime: 0.18 },
  { team: "away", id: "A9", shortLabel: "ST", role: "Centre Forward", position: [54, 34], maxSpeed: 8.8, acceleration: 3.1, reactionTime: 0.18 },
  { team: "away", id: "A10", shortLabel: "RW", role: "Right Forward", position: [56, 54], maxSpeed: 8.8, acceleration: 3.1, reactionTime: 0.18 },
];
export const intelligenceRoleArchetypes = [
  {
    key: "goalkeeper",
    test: (role) => /goalkeeper/i.test(role),
    baseIntelligence: 72,
    weights: {
      perception: 0.96,
      decisionSpeed: 0.82,
      decisionQuality: 0.92,
      tacticalDiscipline: 0.95,
      technicalSecurity: 0.76,
      pressResistance: 0.74,
      composure: 0.92,
    },
  },
  {
    key: "holding-midfielder",
    test: (role, shortLabel) => /holding midfielder/i.test(role) || shortLabel === "6",
    baseIntelligence: 84,
    weights: {
      perception: 1,
      decisionSpeed: 0.96,
      decisionQuality: 0.98,
      tacticalDiscipline: 0.96,
      technicalSecurity: 0.86,
      pressResistance: 0.88,
      composure: 0.9,
    },
  },
  {
    key: "number-eight",
    test: (role, shortLabel) =>
      /no\. 8/i.test(role) || /central midfielder/i.test(role) || shortLabel === "8" || shortLabel === "10",
    baseIntelligence: 80,
    weights: {
      perception: 0.9,
      decisionSpeed: 0.9,
      decisionQuality: 0.9,
      tacticalDiscipline: 0.82,
      technicalSecurity: 0.84,
      pressResistance: 0.82,
      composure: 0.84,
    },
  },
  {
    key: "center-back",
    test: (role) => /center back/i.test(role),
    baseIntelligence: 78,
    weights: {
      perception: 0.94,
      decisionSpeed: 0.84,
      decisionQuality: 0.9,
      tacticalDiscipline: 1,
      technicalSecurity: 0.72,
      pressResistance: 0.8,
      composure: 0.86,
    },
  },
  {
    key: "fullback",
    test: (role) => /back/i.test(role) || /wing-back/i.test(role),
    baseIntelligence: 75,
    weights: {
      perception: 0.82,
      decisionSpeed: 0.86,
      decisionQuality: 0.78,
      tacticalDiscipline: 0.82,
      technicalSecurity: 0.78,
      pressResistance: 0.74,
      composure: 0.76,
    },
  },
  {
    key: "striker",
    test: (role) => /striker/i.test(role) || /centre forward/i.test(role),
    baseIntelligence: 77,
    weights: {
      perception: 0.84,
      decisionSpeed: 0.9,
      decisionQuality: 0.84,
      tacticalDiscipline: 0.72,
      technicalSecurity: 0.82,
      pressResistance: 0.8,
      composure: 0.78,
    },
  },
  {
    key: "wide-forward",
    test: (role) => /winger/i.test(role) || /forward/i.test(role),
    baseIntelligence: 76,
    weights: {
      perception: 0.78,
      decisionSpeed: 0.86,
      decisionQuality: 0.76,
      tacticalDiscipline: 0.66,
      technicalSecurity: 0.84,
      pressResistance: 0.78,
      composure: 0.74,
    },
  },
  {
    key: "default",
    test: () => true,
    baseIntelligence: 75,
    weights: {
      perception: 0.82,
      decisionSpeed: 0.82,
      decisionQuality: 0.82,
      tacticalDiscipline: 0.82,
      technicalSecurity: 0.78,
      pressResistance: 0.76,
      composure: 0.78,
    },
  },
];
export const sprintRoleArchetypes = [
  {
    key: "goalkeeper",
    test: (role) => /goalkeeper/i.test(role),
    accelerationFactor: 0.88,
    maxSpeedFactor: 0.86,
    burstDistance: 2.6,
    shortBurstBoost: 0.02,
  },
  {
    key: "center-back",
    test: (role, shortLabel) => /center back/i.test(role) || /^(LCB|RCB|CB)$/i.test(shortLabel),
    accelerationFactor: 0.95,
    maxSpeedFactor: 0.94,
    burstDistance: 3.7,
    shortBurstBoost: 0.045,
  },
  {
    key: "full-back",
    test: (role, shortLabel) => /back/i.test(role) && !/wing-back/i.test(role) || /^(LB|RB)$/i.test(shortLabel),
    accelerationFactor: 1.01,
    maxSpeedFactor: 1.01,
    burstDistance: 4.6,
    shortBurstBoost: 0.09,
  },
  {
    key: "wing-back",
    test: (role, shortLabel) => /wing-back/i.test(role) || /^(LM|RM|WB)$/i.test(shortLabel),
    accelerationFactor: 1.03,
    maxSpeedFactor: 1.03,
    burstDistance: 5,
    shortBurstBoost: 0.11,
  },
  {
    key: "holding-midfielder",
    test: (role, shortLabel) => /holding midfielder/i.test(role) || shortLabel === "6",
    accelerationFactor: 0.98,
    maxSpeedFactor: 0.98,
    burstDistance: 4,
    shortBurstBoost: 0.06,
  },
  {
    key: "number-eight",
    test: (role, shortLabel) => /no\. 8/i.test(role) || /central midfielder/i.test(role) || shortLabel === "8",
    accelerationFactor: 1,
    maxSpeedFactor: 1,
    burstDistance: 4.4,
    shortBurstBoost: 0.075,
  },
  {
    key: "attacking-midfielder",
    test: (role, shortLabel) => /attacking midfielder/i.test(role) || shortLabel === "10",
    accelerationFactor: 1.01,
    maxSpeedFactor: 1,
    burstDistance: 4.7,
    shortBurstBoost: 0.09,
  },
  {
    key: "striker",
    test: (role, shortLabel) => /striker|centre forward/i.test(role) || /^(ST|9)$/i.test(shortLabel),
    accelerationFactor: 1.04,
    maxSpeedFactor: 1.02,
    burstDistance: 5,
    shortBurstBoost: 0.12,
  },
  {
    key: "winger",
    test: (role, shortLabel) => /winger|forward/i.test(role) || /^(LW|RW|W)$/i.test(shortLabel),
    accelerationFactor: 1.05,
    maxSpeedFactor: 1.04,
    burstDistance: 5.2,
    shortBurstBoost: 0.125,
  },
  {
    key: "default",
    test: () => true,
    accelerationFactor: 1,
    maxSpeedFactor: 1,
    burstDistance: 4.2,
    shortBurstBoost: 0.07,
  },
];
export const playerTendencyTemplates = {
  balanced: {
    label: "Balanced Profile",
    dribble: 0.5,
    passAndMove: 0.5,
    earlyCross: 0.45,
    overlap: 0.45,
    lineBreakPass: 0.5,
    retain: 0.5,
    boxRun: 0.48,
    switchPlay: 0.45,
  },
  "ball-retainer": {
    label: "Ball Retainer",
    dribble: 0.32,
    passAndMove: 0.68,
    earlyCross: 0.2,
    overlap: 0.24,
    lineBreakPass: 0.62,
    retain: 0.9,
    boxRun: 0.22,
    switchPlay: 0.64,
  },
  "pass-and-move": {
    label: "Pass & Move",
    dribble: 0.48,
    passAndMove: 0.9,
    earlyCross: 0.32,
    overlap: 0.44,
    lineBreakPass: 0.72,
    retain: 0.62,
    boxRun: 0.52,
    switchPlay: 0.48,
  },
  dribbler: {
    label: "1v1 Dribbler",
    dribble: 0.92,
    passAndMove: 0.54,
    earlyCross: 0.54,
    overlap: 0.42,
    lineBreakPass: 0.48,
    retain: 0.42,
    boxRun: 0.58,
    switchPlay: 0.34,
  },
  "early-crosser": {
    label: "Early Crosser",
    dribble: 0.5,
    passAndMove: 0.46,
    earlyCross: 0.92,
    overlap: 0.58,
    lineBreakPass: 0.42,
    retain: 0.36,
    boxRun: 0.34,
    switchPlay: 0.7,
  },
  "overlap-runner": {
    label: "Overlap Runner",
    dribble: 0.56,
    passAndMove: 0.56,
    earlyCross: 0.62,
    overlap: 0.92,
    lineBreakPass: 0.48,
    retain: 0.42,
    boxRun: 0.46,
    switchPlay: 0.5,
  },
  "line-breaker": {
    label: "Line Breaker",
    dribble: 0.52,
    passAndMove: 0.66,
    earlyCross: 0.28,
    overlap: 0.36,
    lineBreakPass: 0.92,
    retain: 0.5,
    boxRun: 0.56,
    switchPlay: 0.58,
  },
  "box-runner": {
    label: "Box Runner",
    dribble: 0.5,
    passAndMove: 0.58,
    earlyCross: 0.22,
    overlap: 0.24,
    lineBreakPass: 0.44,
    retain: 0.34,
    boxRun: 0.92,
    switchPlay: 0.26,
  },
};
export const gameRoleProfiles = {
  gk: {
    label: "Sweeper Keeper",
    strengths: { creator: 0.02, switcher: 0.04, receiver: -0.06, runner: -0.22, dribbler: -0.14, finisher: -0.32 },
  },
  rest: {
    label: "Ball-Playing Defender",
    strengths: { creator: 0.08, switcher: 0.08, receiver: 0.02, runner: -0.1, dribbler: -0.05, finisher: -0.16 },
  },
  wideBack: {
    label: "Wing-Back",
    strengths: { creator: 0.05, crosser: 0.1, runner: 0.1, receiver: 0.04, dribbler: 0.04, finisher: -0.06 },
  },
  pivot: {
    label: "Deep-Lying Playmaker",
    strengths: { creator: 0.1, switcher: 0.1, receiver: 0.06, runner: -0.04, dribbler: -0.02, finisher: -0.06 },
  },
  connector: {
    label: "Box-to-Box Midfielder",
    strengths: { creator: 0.08, receiver: 0.08, runner: 0.06, dribbler: 0.04, finisher: 0.04, switcher: 0.04 },
  },
  wideForward: {
    label: "Winger / Inside Forward",
    strengths: { dribbler: 0.12, runner: 0.12, crosser: 0.08, receiver: 0.06, finisher: 0.08, creator: 0.02 },
  },
  striker: {
    label: "Advanced Forward",
    strengths: { finisher: 0.14, runner: 0.1, receiver: 0.08, dribbler: 0.02, creator: -0.02, crosser: -0.06 },
  },
  secondStriker: {
    label: "Second Striker",
    strengths: { creator: 0.08, receiver: 0.1, runner: 0.08, finisher: 0.1, dribbler: 0.05, switcher: -0.02 },
  },
};
export const intelligenceLabelBoosts = {
  "6": 2,
  "8": 1,
  "10": 2,
  CB: 1,
  ST: 1,
};
export const formationMagnetLabels = {
  "4-3-3": ["GK", "LB", "CB", "CB", "RB", "6", "8", "10", "W", "9", "W"],
  "4-1-4-1": ["GK", "LB", "CB", "CB", "RB", "6", "8", "8", "W", "9", "W"],
  "3-4-3": ["GK", "CB", "CB", "CB", "WB", "6", "8", "WB", "W", "9", "W"],
  "4-4-2": ["GK", "LB", "CB", "CB", "RB", "W", "6", "8", "W", "9", "10"],
  "4-2-3-1": ["GK", "LB", "CB", "CB", "RB", "6", "8", "W", "10", "W", "9"],
  "3-5-2": ["GK", "CB", "CB", "CB", "WB", "8", "6", "8", "WB", "9", "9"],
};
export const defensiveAutopilotProfiles = {
  "4-3-3": {
    blockWidth: 40,
    ballSideShift: 0.46,
    wideCompression: 0.86,
    backToBall: 18,
    backToMidfield: 10.5,
    midfieldToForward: 10.5,
    pressOffset: 1.8,
    maxBackLineFromOwnGoal: 47,
  },
  "4-1-4-1": {
    blockWidth: 38,
    ballSideShift: 0.5,
    wideCompression: 0.84,
    backToBall: 17,
    backToMidfield: 9.5,
    midfieldToForward: 9.5,
    pressOffset: 1.7,
    maxBackLineFromOwnGoal: 45,
  },
  "3-4-3": {
    blockWidth: 42,
    ballSideShift: 0.44,
    wideCompression: 0.88,
    backToBall: 19,
    backToMidfield: 11,
    midfieldToForward: 11,
    pressOffset: 1.9,
    maxBackLineFromOwnGoal: 49,
  },
  "4-4-2": {
    blockWidth: 38,
    ballSideShift: 0.48,
    wideCompression: 0.84,
    backToBall: 17,
    backToMidfield: 10,
    midfieldToForward: 9,
    pressOffset: 1.75,
    maxBackLineFromOwnGoal: 45,
  },
  "4-2-3-1": {
    blockWidth: 39,
    ballSideShift: 0.47,
    wideCompression: 0.85,
    backToBall: 18,
    backToMidfield: 10,
    midfieldToForward: 10,
    pressOffset: 1.8,
    maxBackLineFromOwnGoal: 46,
  },
  "3-5-2": {
    blockWidth: 42,
    ballSideShift: 0.44,
    wideCompression: 0.88,
    backToBall: 19,
    backToMidfield: 10.5,
    midfieldToForward: 10.5,
    pressOffset: 1.9,
    maxBackLineFromOwnGoal: 49,
  },
};
export const offensiveAutopilotProfiles = {
  "4-3-3": {
    principleLabel: "triangles, high front three and overlapping width",
    width: 58,
    restBehind: 24,
    pivotBehind: 9,
    connectorAhead: 7,
    frontAhead: 14,
    wideDepthBoost: 7,
    runnerBoost: 6,
    wideBackAdvance: 1.05,
    wideForwardNarrowing: 0.24,
    connectorAdvance: 1.1,
    centralOverload: 0.48,
    pivotDrop: 1.4,
    strikerPairSupport: 0,
    runnerPreferences: {
      wideForward: 2.4,
      striker: 1.7,
      connector: 0.8,
      wideBack: 0.8,
    },
  },
  "4-1-4-1": {
    principleLabel: "4-3-3 conversion with wide midfielders released high",
    width: 54,
    restBehind: 23,
    pivotBehind: 9,
    connectorAhead: 6,
    frontAhead: 12,
    wideDepthBoost: 6,
    runnerBoost: 5,
    wideBackAdvance: 0.82,
    wideForwardNarrowing: 0.22,
    connectorAdvance: 1.8,
    centralOverload: 0.5,
    pivotDrop: 2.2,
    strikerPairSupport: 0,
    runnerPreferences: {
      wideForward: 2,
      connector: 1.4,
      striker: 1.2,
      wideBack: 0.4,
    },
  },
  "3-4-3": {
    principleLabel: "wing-backs high, double-pivot protection and front-three pinning",
    width: 62,
    restBehind: 25,
    pivotBehind: 10,
    connectorAhead: 7,
    frontAhead: 14,
    wideDepthBoost: 8,
    runnerBoost: 6.5,
    wideBackAdvance: 1.42,
    wideForwardNarrowing: 0.38,
    connectorAdvance: 0.55,
    centralOverload: 0.34,
    pivotDrop: 2.8,
    strikerPairSupport: 0,
    runnerPreferences: {
      wideBack: 2.4,
      wideForward: 2,
      striker: 1.5,
      connector: 0.4,
    },
  },
  "4-4-2": {
    principleLabel: "front-two occupation, wide counters and paired support",
    width: 52,
    restBehind: 24,
    pivotBehind: 8,
    connectorAhead: 6,
    frontAhead: 13,
    wideDepthBoost: 5,
    runnerBoost: 5.5,
    wideBackAdvance: 0.62,
    wideForwardNarrowing: 0.08,
    connectorAdvance: 0.3,
    centralOverload: 0.2,
    pivotDrop: 0.5,
    strikerPairSupport: 1,
    runnerPreferences: {
      secondStriker: 2.3,
      striker: 2,
      wideForward: 1.4,
      connector: 0.2,
    },
  },
  "4-2-3-1": {
    principleLabel: "double-pivot security with a 10 between lines",
    width: 56,
    restBehind: 24,
    pivotBehind: 9,
    connectorAhead: 7,
    frontAhead: 13,
    wideDepthBoost: 6.5,
    runnerBoost: 6,
    wideBackAdvance: 0.86,
    wideForwardNarrowing: 0.26,
    connectorAdvance: 1.55,
    centralOverload: 0.58,
    pivotDrop: 2.7,
    strikerPairSupport: 0,
    runnerPreferences: {
      connector: 2.1,
      wideForward: 1.8,
      striker: 1.3,
      wideBack: 0.8,
    },
  },
  "3-5-2": {
    principleLabel: "central overload, wing-back width and two-striker combinations",
    width: 60,
    restBehind: 25,
    pivotBehind: 9,
    connectorAhead: 7,
    frontAhead: 13,
    wideDepthBoost: 7,
    runnerBoost: 5.5,
    wideBackAdvance: 1.34,
    wideForwardNarrowing: 0.1,
    connectorAdvance: 0.95,
    centralOverload: 0.64,
    pivotDrop: 1.7,
    strikerPairSupport: 1,
    runnerPreferences: {
      wideBack: 2.2,
      striker: 2,
      connector: 1.1,
    },
  },
};
export const offensivePhaseProfiles = {
  setPiece: {
    label: "Set Piece",
    widthMultiplier: 0.96,
    restBehindOffset: 3,
    supportCompactness: 0.1,
    depthStretch: -1,
    finalThirdPin: 0,
  },
  buildUp: {
    label: "Build-Up",
    widthMultiplier: 1.02,
    restBehindOffset: 2,
    supportCompactness: 0.18,
    depthStretch: -2,
    finalThirdPin: 0,
  },
  progression: {
    label: "Progression",
    widthMultiplier: 1,
    restBehindOffset: 0,
    supportCompactness: 0.12,
    depthStretch: 0,
    finalThirdPin: 1.5,
  },
  finalThird: {
    label: "Final Third",
    widthMultiplier: 0.9,
    restBehindOffset: 4,
    supportCompactness: 0.08,
    depthStretch: 2.5,
    finalThirdPin: 4,
  },
};
export const matchPhaseModel = {
  inPossession: {
    label: "In Possession",
    description: "How the team creates structure and progresses while it owns the ball.",
  },
  outOfPossession: {
    label: "Out of Possession",
    description: "How the team defends space, presses and protects priority zones.",
  },
  transitionToAttack: {
    label: "Transition to Attack",
    description: "The first actions after winning the ball: secure, counter or release runners.",
  },
  transitionToDefend: {
    label: "Transition to Defend",
    description: "The first actions after losing the ball: counter-press, delay or recover shape.",
  },
  setPieces: {
    label: "Set Pieces",
    description: "Restarts such as kick-off, corners, free-kicks, throw-ins, goal-kicks and penalties.",
  },
};
export const setPiecePhaseProfiles = {
  kickoff: {
    label: "Kick-Off",
    principleLabel: "secure the first pass, open support angles and prepare the next attacking pattern",
    restartTeam: defaultKickoffTeamId,
  },
  corner: {
    label: "Corner",
    principleLabel: "attack priority zones, protect the second ball and secure rest defence",
  },
  freeKick: {
    label: "Free-Kick",
    principleLabel: "choose between direct threat, delivery, disguise or short restart",
  },
  throwIn: {
    label: "Throw-In",
    principleLabel: "create a safe first touch, third-player option and pressure escape",
  },
  goalKick: {
    label: "Goal-Kick",
    principleLabel: "build first line, invite or bypass pressure and keep rest defence connected",
  },
  penalty: {
    label: "Penalty",
    principleLabel: "isolate the execution moment and prepare rebound positions",
  },
};
export const attackStylePresets = {
  balanced: {
    label: "Balanced",
    principleLabel: "balanced support, controlled progression and shared final-third responsibility",
    widthMultiplier: 1,
    restBehindOffset: 0,
    frontAheadOffset: 0,
    supportCompactnessMultiplier: 1,
    directness: 0.5,
    shortSupport: 0.55,
    lineBreakBias: 0.5,
    switchBias: 0.48,
    crossBias: 0.46,
    overlapBias: 0.48,
    dribbleBias: 0.48,
    shootBias: 0.48,
    tempo: 0.5,
    risk: 0.48,
    firstTouchForwardBias: 0.5,
  },
  "control-possession": {
    label: "Control Possession",
    principleLabel: "patience, close support, third-player angles and fewer low-value long balls",
    widthMultiplier: 1.03,
    restBehindOffset: 2.2,
    frontAheadOffset: -1.2,
    supportCompactnessMultiplier: 1.12,
    directness: 0.28,
    shortSupport: 0.92,
    lineBreakBias: 0.42,
    switchBias: 0.5,
    crossBias: 0.22,
    overlapBias: 0.56,
    dribbleBias: 0.38,
    shootBias: 0.36,
    tempo: 0.38,
    risk: 0.32,
    firstTouchForwardBias: 0.52,
    carryBias: 0.48,
  },
  "tiki-taka": {
    label: "Tiki-Taka",
    principleLabel: "very short support, constant rotations and high-volume passing to move the block",
    widthMultiplier: 1,
    restBehindOffset: 2.6,
    frontAheadOffset: -1.8,
    supportCompactnessMultiplier: 1.24,
    directness: 0.22,
    shortSupport: 0.97,
    lineBreakBias: 0.48,
    switchBias: 0.34,
    crossBias: 0.18,
    overlapBias: 0.58,
    dribbleBias: 0.32,
    shootBias: 0.34,
    tempo: 0.7,
    risk: 0.34,
    firstTouchForwardBias: 0.58,
    passBias: 0.9,
    carryBias: 0.4,
    deliveryBias: 0.18,
    routeOneBias: 0.02,
  },
  "fluid-combinations": {
    label: "Fluid Combinations",
    principleLabel: "pass-and-move, wall passes, rotations and receiving on the move",
    widthMultiplier: 0.98,
    restBehindOffset: 1,
    frontAheadOffset: 0,
    supportCompactnessMultiplier: 1.18,
    directness: 0.4,
    shortSupport: 0.86,
    lineBreakBias: 0.58,
    switchBias: 0.36,
    crossBias: 0.3,
    overlapBias: 0.6,
    dribbleBias: 0.5,
    shootBias: 0.42,
    tempo: 0.68,
    risk: 0.42,
    firstTouchForwardBias: 0.74,
  },
  "vertical-tiki-taka": {
    label: "Vertical Tiki-Taka",
    principleLabel: "short combinations with a stronger forward punch through the next line",
    widthMultiplier: 0.96,
    restBehindOffset: 1.6,
    frontAheadOffset: 1.2,
    supportCompactnessMultiplier: 1.2,
    directness: 0.58,
    shortSupport: 0.82,
    lineBreakBias: 0.84,
    switchBias: 0.4,
    crossBias: 0.28,
    overlapBias: 0.56,
    dribbleBias: 0.45,
    shootBias: 0.44,
    tempo: 0.82,
    risk: 0.5,
    firstTouchForwardBias: 0.84,
    passBias: 0.82,
    carryBias: 0.44,
    deliveryBias: 0.28,
    routeOneBias: 0.08,
  },
  "vertical-play": {
    label: "Vertical Play",
    principleLabel: "early forward support, line-breaking passes and fast receiving angles",
    widthMultiplier: 1,
    restBehindOffset: 0.5,
    frontAheadOffset: 2.2,
    supportCompactnessMultiplier: 0.92,
    directness: 0.68,
    shortSupport: 0.54,
    lineBreakBias: 0.9,
    switchBias: 0.5,
    crossBias: 0.38,
    overlapBias: 0.42,
    dribbleBias: 0.48,
    shootBias: 0.48,
    tempo: 0.76,
    risk: 0.58,
    firstTouchForwardBias: 0.82,
  },
  gegenpress: {
    label: "Gegenpress",
    principleLabel: "win it back, attack quickly before the opponent can reset and keep runners close",
    widthMultiplier: 0.98,
    restBehindOffset: 1.4,
    frontAheadOffset: 2,
    supportCompactnessMultiplier: 1.05,
    directness: 0.7,
    shortSupport: 0.62,
    lineBreakBias: 0.78,
    switchBias: 0.42,
    crossBias: 0.42,
    overlapBias: 0.5,
    dribbleBias: 0.56,
    shootBias: 0.58,
    tempo: 0.92,
    risk: 0.64,
    firstTouchForwardBias: 0.88,
    passBias: 0.66,
    carryBias: 0.58,
    deliveryBias: 0.42,
    routeOneBias: 0.12,
  },
  "wing-play": {
    label: "Wing Play",
    principleLabel: "wide isolation, switches, early deliveries and aggressive far-post runs",
    widthMultiplier: 1.08,
    restBehindOffset: 0.5,
    frontAheadOffset: 0.8,
    supportCompactnessMultiplier: 0.86,
    directness: 0.54,
    shortSupport: 0.46,
    lineBreakBias: 0.48,
    switchBias: 0.82,
    crossBias: 0.88,
    overlapBias: 0.68,
    dribbleBias: 0.6,
    shootBias: 0.4,
    tempo: 0.62,
    risk: 0.54,
    firstTouchForwardBias: 0.62,
  },
  "overlap-wide": {
    label: "Overlap Wide",
    principleLabel: "wide overloads, full-back or wing-back runs and cut-backs before hopeful crosses",
    widthMultiplier: 1.06,
    restBehindOffset: 0.5,
    frontAheadOffset: 0.4,
    supportCompactnessMultiplier: 0.94,
    directness: 0.48,
    shortSupport: 0.58,
    lineBreakBias: 0.52,
    switchBias: 0.62,
    crossBias: 0.68,
    overlapBias: 0.94,
    dribbleBias: 0.54,
    shootBias: 0.38,
    tempo: 0.6,
    risk: 0.48,
    firstTouchForwardBias: 0.66,
  },
  "direct-transition": {
    label: "Direct Transition",
    principleLabel: "fast forward play, early runners and fewer recycle passes after regains",
    widthMultiplier: 1.02,
    restBehindOffset: -1.2,
    frontAheadOffset: 3.4,
    supportCompactnessMultiplier: 0.78,
    directness: 0.9,
    shortSupport: 0.28,
    lineBreakBias: 0.88,
    switchBias: 0.44,
    crossBias: 0.54,
    overlapBias: 0.34,
    dribbleBias: 0.52,
    shootBias: 0.58,
    tempo: 0.88,
    risk: 0.74,
    firstTouchForwardBias: 0.9,
  },
  "fluid-counter-attack": {
    label: "Fluid Counter-Attack",
    principleLabel: "secure the regain, release runners with support underneath and attack open space",
    widthMultiplier: 1.02,
    restBehindOffset: 0.4,
    frontAheadOffset: 2.2,
    supportCompactnessMultiplier: 0.9,
    directness: 0.68,
    shortSupport: 0.5,
    lineBreakBias: 0.78,
    switchBias: 0.6,
    crossBias: 0.48,
    overlapBias: 0.44,
    dribbleBias: 0.66,
    shootBias: 0.52,
    tempo: 0.78,
    risk: 0.54,
    firstTouchForwardBias: 0.84,
    passBias: 0.56,
    carryBias: 0.68,
    deliveryBias: 0.48,
    routeOneBias: 0.18,
  },
  "counter-attack": {
    label: "Counter Attack",
    principleLabel: "protect first pass, release runners, attack open space and avoid slow circulation",
    widthMultiplier: 1.04,
    restBehindOffset: -0.5,
    frontAheadOffset: 2.8,
    supportCompactnessMultiplier: 0.82,
    directness: 0.78,
    shortSupport: 0.36,
    lineBreakBias: 0.8,
    switchBias: 0.56,
    crossBias: 0.56,
    overlapBias: 0.36,
    dribbleBias: 0.68,
    shootBias: 0.54,
    tempo: 0.84,
    risk: 0.62,
    firstTouchForwardBias: 0.86,
  },
  "route-one": {
    label: "Route One",
    principleLabel: "play early into the forward line, win the first or second ball and attack territory",
    widthMultiplier: 1,
    restBehindOffset: -1.4,
    frontAheadOffset: 4.2,
    supportCompactnessMultiplier: 0.7,
    directness: 0.97,
    shortSupport: 0.18,
    lineBreakBias: 0.62,
    switchBias: 0.42,
    crossBias: 0.78,
    overlapBias: 0.26,
    dribbleBias: 0.28,
    shootBias: 0.56,
    tempo: 0.72,
    risk: 0.78,
    firstTouchForwardBias: 0.9,
    passBias: 0.42,
    carryBias: 0.22,
    deliveryBias: 0.72,
    routeOneBias: 0.95,
  },
};
export const possessionRhythmDefaults = {
  targetSeconds: 8.8,
  progressionUrgency: 0.5,
  sidewaysTolerance: 0.42,
  recycleWindow: 0.5,
};
export const possessionRhythmByAttackStyle = {
  balanced: {
    targetSeconds: 8.8,
    progressionUrgency: 0.52,
    sidewaysTolerance: 0.42,
    recycleWindow: 0.5,
  },
  "control-possession": {
    targetSeconds: 12.2,
    progressionUrgency: 0.34,
    sidewaysTolerance: 0.68,
    recycleWindow: 0.76,
  },
  "tiki-taka": {
    targetSeconds: 12,
    progressionUrgency: 0.42,
    sidewaysTolerance: 0.62,
    recycleWindow: 0.8,
  },
  "fluid-combinations": {
    targetSeconds: 10.5,
    progressionUrgency: 0.54,
    sidewaysTolerance: 0.5,
    recycleWindow: 0.62,
  },
  "vertical-tiki-taka": {
    targetSeconds: 9.2,
    progressionUrgency: 0.66,
    sidewaysTolerance: 0.38,
    recycleWindow: 0.54,
  },
  "vertical-play": {
    targetSeconds: 7.8,
    progressionUrgency: 0.78,
    sidewaysTolerance: 0.3,
    recycleWindow: 0.38,
  },
  gegenpress: {
    targetSeconds: 6.8,
    progressionUrgency: 0.84,
    sidewaysTolerance: 0.26,
    recycleWindow: 0.36,
  },
  "wing-play": {
    targetSeconds: 8.6,
    progressionUrgency: 0.58,
    sidewaysTolerance: 0.44,
    recycleWindow: 0.42,
  },
  "overlap-wide": {
    targetSeconds: 9.2,
    progressionUrgency: 0.54,
    sidewaysTolerance: 0.48,
    recycleWindow: 0.46,
  },
  "direct-transition": {
    targetSeconds: 6.2,
    progressionUrgency: 0.9,
    sidewaysTolerance: 0.18,
    recycleWindow: 0.22,
  },
  "fluid-counter-attack": {
    targetSeconds: 7.4,
    progressionUrgency: 0.78,
    sidewaysTolerance: 0.28,
    recycleWindow: 0.34,
  },
  "counter-attack": {
    targetSeconds: 6.7,
    progressionUrgency: 0.84,
    sidewaysTolerance: 0.22,
    recycleWindow: 0.28,
  },
  "route-one": {
    targetSeconds: 5.4,
    progressionUrgency: 0.94,
    sidewaysTolerance: 0.12,
    recycleWindow: 0.16,
  },
};
export function getAttackStyleRhythmProfile(styleKey = "balanced") {
  return {
    ...possessionRhythmDefaults,
    ...(possessionRhythmByAttackStyle[styleKey] ?? possessionRhythmByAttackStyle.balanced),
  };
}
export const defenseStylePresets = {
  "balanced-block": {
    label: "Balanced Block",
    principleLabel: "compact first, press when the cue is clear",
    preferredPhase: "balanced",
    blockWidthMultiplier: 1,
    ballSideShiftOffset: 0,
    backToBallOffset: 0,
    lineGapOffset: 0,
    lineHeightOffset: 0,
    pressOffsetMultiplier: 1,
    pressingIntensity: 0.5,
    tackleIntent: 0.48,
  },
  "high-press": {
    label: "High Press",
    principleLabel: "front-foot pressure, short distances and immediate access to the ball",
    preferredPhase: "highPress",
    blockWidthMultiplier: 0.96,
    ballSideShiftOffset: 0.06,
    backToBallOffset: 2.8,
    lineGapOffset: -1.1,
    lineHeightOffset: 7,
    pressOffsetMultiplier: 0.72,
    pressingIntensity: 0.88,
    tackleIntent: 0.72,
  },
  gegenpress: {
    label: "Gegenpress",
    principleLabel: "counter-press after loss, squeeze the first pass and keep the block high",
    preferredPhase: "highPress",
    blockWidthMultiplier: 0.9,
    ballSideShiftOffset: 0.1,
    backToBallOffset: 4.2,
    lineGapOffset: -1.7,
    lineHeightOffset: 7.5,
    pressOffsetMultiplier: 0.62,
    pressingIntensity: 0.98,
    tackleIntent: 0.82,
  },
  "mid-block": {
    label: "Mid Block",
    principleLabel: "protect central space, shift together and jump on predictable passes",
    preferredPhase: "midBlock",
    blockWidthMultiplier: 0.95,
    ballSideShiftOffset: 0.03,
    backToBallOffset: 0.4,
    lineGapOffset: -0.5,
    lineHeightOffset: 0,
    pressOffsetMultiplier: 0.92,
    pressingIntensity: 0.56,
    tackleIntent: 0.54,
  },
  "low-block": {
    label: "Low Block",
    principleLabel: "deny central entries, keep the box protected and press only recoverable balls",
    preferredPhase: "lowBlock",
    blockWidthMultiplier: 0.88,
    ballSideShiftOffset: 0.02,
    backToBallOffset: -4.2,
    lineGapOffset: -1.7,
    lineHeightOffset: -8,
    pressOffsetMultiplier: 1.16,
    pressingIntensity: 0.34,
    tackleIntent: 0.42,
  },
  "counter-press": {
    label: "Counter Press",
    principleLabel: "react immediately after losing the ball, crowd the first pass and secure rest defence",
    preferredPhase: "highPress",
    blockWidthMultiplier: 0.92,
    ballSideShiftOffset: 0.08,
    backToBallOffset: 3.4,
    lineGapOffset: -1.4,
    lineHeightOffset: 5,
    pressOffsetMultiplier: 0.68,
    pressingIntensity: 0.95,
    tackleIntent: 0.78,
  },
  "press-trap-wide": {
    label: "Wide Press Trap",
    principleLabel: "show outside, compress the touchline and attack the pass into wide feet",
    preferredPhase: "midBlock",
    blockWidthMultiplier: 0.9,
    ballSideShiftOffset: 0.1,
    backToBallOffset: 1.4,
    lineGapOffset: -0.9,
    lineHeightOffset: 1.5,
    pressOffsetMultiplier: 0.84,
    pressingIntensity: 0.72,
    tackleIntent: 0.66,
  },
  "protect-box": {
    label: "Protect Box",
    principleLabel: "keep defenders goal-side, protect the penalty spot and attack crosses late",
    preferredPhase: "boxDefending",
    blockWidthMultiplier: 0.82,
    ballSideShiftOffset: -0.01,
    backToBallOffset: -6,
    lineGapOffset: -2.1,
    lineHeightOffset: -10,
    pressOffsetMultiplier: 1.25,
    pressingIntensity: 0.28,
    tackleIntent: 0.38,
  },
  catenaccio: {
    label: "Catenaccio",
    principleLabel: "protect the central lane, stay goal-side and break from secure regains",
    preferredPhase: "lowBlock",
    blockWidthMultiplier: 0.8,
    ballSideShiftOffset: -0.02,
    backToBallOffset: -5.6,
    lineGapOffset: -2.3,
    lineHeightOffset: -11,
    pressOffsetMultiplier: 1.28,
    pressingIntensity: 0.26,
    tackleIntent: 0.46,
  },
  "park-the-bus": {
    label: "Park The Bus",
    principleLabel: "defend the box first, stay extremely compact and allow only low-value shots",
    preferredPhase: "boxDefending",
    blockWidthMultiplier: 0.72,
    ballSideShiftOffset: -0.04,
    backToBallOffset: -7.4,
    lineGapOffset: -2.8,
    lineHeightOffset: -13,
    pressOffsetMultiplier: 1.42,
    pressingIntensity: 0.18,
    tackleIntent: 0.34,
  },
};
export const defensivePhaseProfiles = {
  setPiece: {
    label: "Set Piece",
    blockWidth: 41,
    minBlockWidth: 36,
    maxBlockWidth: 45,
    ballSideShift: 0.48,
    wideCompression: 0.84,
    backToBall: 18,
    backToMidfield: 9,
    midfieldToForward: 8,
    minBackLineFromOwnGoal: 12,
    maxBackLineFromOwnGoal: 52,
    midfieldAheadOfBall: 2.5,
    forwardAheadOfBall: 6,
    pressOffset: 1.45,
    pressInsideBias: 0.18,
    formationWidthWeight: 0.5,
    formationGapWeight: 0.4,
    gkDepthMin: 6,
    gkDepthMax: 12,
    gkSweepStart: 34,
    gkSweepFactor: 0.08,
    lineWidthRatio: {
      back: 0.96,
      midfield: 0.88,
      forward: 0.64,
    },
    playerGap: {
      back: { min: 7.5, max: 12 },
      midfield: { min: 7, max: 11 },
      forward: { min: 7, max: 14 },
    },
  },
  highPress: {
    label: "High Press",
    blockWidth: 43,
    minBlockWidth: 38,
    maxBlockWidth: 47,
    ballSideShift: 0.58,
    wideCompression: 0.8,
    backToBall: 25.5,
    backToMidfield: 9.5,
    midfieldToForward: 8.5,
    minBackLineFromOwnGoal: 33,
    maxBackLineFromOwnGoal: 66,
    midfieldAheadOfBall: 3,
    forwardAheadOfBall: 7,
    pressOffset: 1.15,
    pressInsideBias: 0.12,
    formationWidthWeight: 0.55,
    formationGapWeight: 0.35,
    gkDepthMin: 10.5,
    gkDepthMax: 19,
    gkSweepStart: 36,
    gkSweepFactor: 0.15,
    lineWidthRatio: {
      back: 0.92,
      midfield: 0.86,
      forward: 0.72,
    },
    playerGap: {
      back: { min: 8.5, max: 13 },
      midfield: { min: 7.5, max: 12 },
      forward: { min: 6.5, max: 14 },
    },
  },
  midBlock: {
    label: "Mid Block",
    blockWidth: 40.1,
    minBlockWidth: 36,
    maxBlockWidth: 44,
    ballSideShift: 0.5,
    wideCompression: 0.84,
    backToBall: 18,
    backToMidfield: 10,
    midfieldToForward: 9.5,
    minBackLineFromOwnGoal: 13,
    maxBackLineFromOwnGoal: 48,
    midfieldAheadOfBall: 3,
    forwardAheadOfBall: 8,
    pressOffset: 1.65,
    pressInsideBias: 0.18,
    formationWidthWeight: 0.58,
    formationGapWeight: 0.5,
    gkDepthMin: 6.5,
    gkDepthMax: 11,
    gkSweepStart: 35,
    gkSweepFactor: 0.08,
    lineWidthRatio: {
      back: 1,
      midfield: 0.92,
      forward: 0.68,
    },
    playerGap: {
      back: { min: 8, max: 13 },
      midfield: { min: 7.5, max: 11.5 },
      forward: { min: 8, max: 16 },
    },
  },
  lowBlock: {
    label: "Low Block",
    blockWidth: 32,
    minBlockWidth: 24,
    maxBlockWidth: 36,
    ballSideShift: 0.62,
    wideCompression: 0.78,
    backToBall: 14.5,
    backToMidfield: 10.5,
    midfieldToForward: 15.5,
    targetBlockHeight: 26,
    targetBackToMidfield: 10.5,
    unitPlayerGap: 8,
    unitCompactnessWeight: 0.78,
    minBackLineFromOwnGoal: 7,
    maxBackLineFromOwnGoal: 34,
    midfieldAheadOfBall: 2.2,
    forwardAheadOfBall: 12,
    pressOffset: 1.25,
    pressInsideBias: 0.24,
    formationWidthWeight: 0.42,
    formationGapWeight: 0.38,
    gkDepthMin: 4.5,
    gkDepthMax: 8.5,
    gkSweepStart: 24,
    gkSweepFactor: 0.06,
    lineWidthRatio: {
      back: 0.95,
      midfield: 0.9,
      forward: 0.58,
    },
    playerGap: {
      back: { min: 7.6, max: 8.4 },
      midfield: { min: 7.6, max: 8.4 },
      forward: { min: 7.6, max: 8.8 },
    },
  },
  boxDefending: {
    label: "Box Defending",
    blockWidth: 32,
    minBlockWidth: 24,
    maxBlockWidth: 38,
    ballSideShift: 0.7,
    wideCompression: 0.74,
    backToBall: 8.5,
    backToMidfield: 6.5,
    midfieldToForward: 7,
    targetBlockHeight: 17,
    targetBackToMidfield: 7.2,
    unitPlayerGap: 7.5,
    unitCompactnessWeight: 0.82,
    minBackLineFromOwnGoal: 5.5,
    maxBackLineFromOwnGoal: 17,
    midfieldAheadOfBall: 1.5,
    forwardAheadOfBall: 4,
    pressOffset: 0.9,
    pressInsideBias: 0.32,
    formationWidthWeight: 0.3,
    formationGapWeight: 0.25,
    gkDepthMin: 2,
    gkDepthMax: 5.5,
    gkSweepStart: 12,
    gkSweepFactor: 0.05,
    lineWidthRatio: {
      back: 0.88,
      midfield: 0.82,
      forward: 0.48,
    },
    playerGap: {
      back: { min: 4.8, max: 8.5 },
      midfield: { min: 5, max: 9 },
      forward: { min: 6, max: 12 },
    },
  },
};
export const defensiveAggressionPresets = {
  conservative: {
    label: "Conservative",
    reachMultiplier: 0.84,
    contactWindow: 0.8,
    laneBehindWindow: 0.035,
    laneAheadWindow: 0.11,
    etaTolerance: 0.4,
    laneScoreThreshold: 0.72,
    marginThreshold: 0.09,
    contestedMargin: 0.015,
    scoreBonus: -0.06,
  },
  balanced: {
    label: "Balanced",
    reachMultiplier: 0.93,
    contactWindow: 0.9,
    laneBehindWindow: 0.045,
    laneAheadWindow: 0.16,
    etaTolerance: 0.5,
    laneScoreThreshold: 0.6,
    marginThreshold: 0.06,
    contestedMargin: -0.005,
    scoreBonus: -0.015,
  },
  aggressive: {
    label: "Aggressive",
    reachMultiplier: 1.05,
    contactWindow: 1.06,
    laneBehindWindow: 0.065,
    laneAheadWindow: 0.23,
    etaTolerance: 0.64,
    laneScoreThreshold: 0.5,
    marginThreshold: 0.03,
    contestedMargin: -0.045,
    scoreBonus: 0.025,
  },
};
export const pitchSurfacePresets = {
  "natural-grass": {
    key: "natural-grass",
    label: "Natural Grass",
    groundRollFactor: 0.94,
    airCarryFactor: 0.99,
    dribbleCarryFactor: 0.985,
  },
  "hybrid-grass": {
    key: "hybrid-grass",
    label: "Hybrid Grass",
    groundRollFactor: 1,
    airCarryFactor: 1,
    dribbleCarryFactor: 1,
  },
  "football-turf": {
    key: "football-turf",
    label: "Football Turf",
    groundRollFactor: 1.07,
    airCarryFactor: 1.015,
    dribbleCarryFactor: 1.015,
  },
};
export const weatherPresets = {
  dry: {
    key: "dry",
    label: "Dry",
    dribbleTractionFactor: 1.02,
    dribbleControlFactor: 1,
    ballRollFactor: 0.98,
    ballSkidFactor: 0.96,
  },
  damp: {
    key: "damp",
    label: "Damp",
    dribbleTractionFactor: 0.98,
    dribbleControlFactor: 0.98,
    ballRollFactor: 1,
    ballSkidFactor: 1,
  },
  wet: {
    key: "wet",
    label: "Wet",
    dribbleTractionFactor: 0.93,
    dribbleControlFactor: 0.94,
    ballRollFactor: 1.04,
    ballSkidFactor: 1.08,
  },
};
export const firstTouchModes = {
  auto: "Auto",
  kill: "Kill",
  forward: "Forward",
  inside: "Inside",
  outside: "Outside",
  back: "Back",
  across: "Across Body",
};
export function resolvePreferredFoot(blueprint) {
  const role = blueprint?.role?.toLowerCase() ?? "";
  const shortLabel = blueprint?.shortLabel?.toUpperCase() ?? "";
  if (/\bleft\b/.test(role) || shortLabel.startsWith("L")) {
    return "left";
  }
  if (/\bright\b/.test(role) || shortLabel.startsWith("R")) {
    return "right";
  }
  if (/goalkeeper|center back|holding midfielder/.test(role)) {
    return "right";
  }
  if (/attacking midfielder|winger|forward|striker|centre forward/.test(role)) {
    return blueprint.team === "away" && /10|11/.test(blueprint.id) ? "left" : "right";
  }
  return "right";
}
export function resolveWeakFootQuality(blueprint) {
  const role = blueprint?.role?.toLowerCase() ?? "";
  const shortLabel = blueprint?.shortLabel?.toUpperCase() ?? "";
  if (/goalkeeper/.test(role)) {
    return 0.58;
  }
  if (/center back/.test(role) || /^(LCB|RCB|CB)$/.test(shortLabel)) {
    return 0.62;
  }
  if (/winger|forward|striker|centre forward|attacking midfielder/.test(role)) {
    return 0.78;
  }
  if (/holding midfielder|central midfielder|no\. 8/.test(role) || /^(6|8|10)$/.test(shortLabel)) {
    return 0.74;
  }
  if (/back|wing-back/.test(role) || /^(LB|RB|LM|RM)$/.test(shortLabel)) {
    return 0.7;
  }
  return 0.68;
}
export const autoBallProfiles = {
  "gk-short-build": {
    key: "gk-short-build",
    label: "GK Short Build-Up",
    minDistance: 4,
    maxDistance: 18,
    averageSpeedRange: [7.2, 9.4],
    launchMultiplierRange: [1.08, 1.16],
    rollFloorRange: [1.0, 1.8],
    flightStyle: "ground",
    peakHeightRange: [0, 0],
    controlHeightRange: [0.12, 0.12],
    landingPhaseRange: [0.58, 0.58],
  },
  "short-feet": {
    key: "short-feet",
    label: "Short To Feet",
    minDistance: 2,
    maxDistance: 10,
    averageSpeedRange: [7.8, 9.4],
    launchMultiplierRange: [1.1, 1.16],
    rollFloorRange: [1.1, 1.8],
    flightStyle: "ground",
    peakHeightRange: [0, 0],
    controlHeightRange: [0.12, 0.12],
    landingPhaseRange: [0.58, 0.58],
  },
  "firm-feet": {
    key: "firm-feet",
    label: "Firm To Feet",
    minDistance: 8,
    maxDistance: 18,
    averageSpeedRange: [9.2, 11.2],
    launchMultiplierRange: [1.13, 1.2],
    rollFloorRange: [1.2, 2.0],
    flightStyle: "ground",
    peakHeightRange: [0, 0],
    controlHeightRange: [0.12, 0.12],
    landingPhaseRange: [0.58, 0.58],
  },
  "line-break": {
    key: "line-break",
    label: "Line-Breaking Pass",
    minDistance: 10,
    maxDistance: 24,
    averageSpeedRange: [10.3, 12.8],
    launchMultiplierRange: [1.15, 1.24],
    rollFloorRange: [1.4, 2.2],
    flightStyle: "ground",
    peakHeightRange: [0, 0],
    controlHeightRange: [0.12, 0.12],
    landingPhaseRange: [0.58, 0.58],
  },
  "driven-feet": {
    key: "driven-feet",
    label: "Driven To Feet",
    minDistance: 16,
    maxDistance: 30,
    averageSpeedRange: [11.4, 13.8],
    launchMultiplierRange: [1.17, 1.28],
    rollFloorRange: [1.6, 2.6],
    flightStyle: "ground",
    peakHeightRange: [0, 0],
    controlHeightRange: [0.12, 0.12],
    landingPhaseRange: [0.58, 0.58],
  },
  "onto-9": {
    key: "onto-9",
    label: "Pass Onto 9",
    minDistance: 16,
    maxDistance: 32,
    averageSpeedRange: [11.6, 14.4],
    launchMultiplierRange: [1.18, 1.3],
    rollFloorRange: [1.7, 2.9],
    flightStyle: "clipped",
    peakHeightRange: [0.8, 2.1],
    controlHeightRange: [0.32, 0.42],
    landingPhaseRange: [0.72, 0.82],
    curveRange: [0.25, 0.85],
    spinRateRange: [1.8, 3.2],
  },
  "lead-space": {
    key: "lead-space",
    label: "Lead Pass",
    minDistance: 4,
    maxDistance: 14,
    averageSpeedRange: [8.8, 10.7],
    launchMultiplierRange: [1.13, 1.22],
    rollFloorRange: [1.2, 2.1],
    flightStyle: "ground",
    peakHeightRange: [0, 0],
    controlHeightRange: [0.12, 0.12],
    landingPhaseRange: [0.58, 0.58],
  },
  "throw-in": {
    key: "throw-in",
    label: "Throw-In",
    minDistance: 3,
    maxDistance: 18,
    averageSpeedRange: [6.2, 8.8],
    launchMultiplierRange: [1.04, 1.16],
    rollFloorRange: [0.8, 1.4],
    flightStyle: "clipped",
    peakHeightRange: [0.9, 2.2],
    controlHeightRange: [0.32, 0.46],
    landingPhaseRange: [0.68, 0.82],
    curveRange: [0, 0.16],
    spinRateRange: [0.8, 1.6],
  },
  "into-space": {
    key: "into-space",
    label: "Pass Into Space",
    minDistance: 8,
    maxDistance: 28,
    averageSpeedRange: [10.4, 13.7],
    launchMultiplierRange: [1.18, 1.28],
    rollFloorRange: [1.5, 2.8],
    flightStyle: "ground",
    peakHeightRange: [0, 0],
    controlHeightRange: [0.12, 0.12],
    landingPhaseRange: [0.58, 0.58],
  },
  cutback: {
    key: "cutback",
    label: "Cutback",
    minDistance: 6,
    maxDistance: 18,
    averageSpeedRange: [9.4, 11.8],
    launchMultiplierRange: [1.14, 1.24],
    rollFloorRange: [1.2, 2.2],
    flightStyle: "ground",
    peakHeightRange: [0, 0],
    controlHeightRange: [0.12, 0.12],
    landingPhaseRange: [0.58, 0.58],
    curveRange: [0.08, 0.28],
    spinRateRange: [1.4, 2.2],
  },
  cross: {
    key: "cross",
    label: "Cross",
    minDistance: 12,
    maxDistance: 30,
    averageSpeedRange: [11.2, 15.4],
    launchMultiplierRange: [1.18, 1.3],
    rollFloorRange: [0.8, 1.5],
    flightStyle: "lofted",
    peakHeightRange: [3.4, 6.8],
    controlHeightRange: [0.48, 0.68],
    landingPhaseRange: [0.76, 0.88],
    curveRange: [0.75, 2.1],
    spinRateRange: [2.6, 4.8],
  },
  switch: {
    key: "switch",
    label: "Switch Of Play",
    minDistance: 24,
    maxDistance: 52,
    averageSpeedRange: [13.2, 17.4],
    launchMultiplierRange: [1.2, 1.34],
    rollFloorRange: [1.0, 1.8],
    flightStyle: "lofted",
    peakHeightRange: [2.8, 5.5],
    controlHeightRange: [0.42, 0.58],
    landingPhaseRange: [0.74, 0.86],
    curveRange: [0.85, 2.4],
    spinRateRange: [2.2, 4.2],
  },
  shot: {
    key: "shot",
    label: "Shot",
    minDistance: 6,
    maxDistance: 35,
    averageSpeedRange: [15, 24],
    launchMultiplierRange: [1.22, 1.4],
    rollFloorRange: [2.2, 5.2],
    flightStyle: "driven",
    peakHeightRange: [0.2, 1.2],
    controlHeightRange: [0.24, 0.38],
    landingPhaseRange: [0.68, 0.82],
  },
  "box-shot": {
    key: "box-shot",
    label: "Box Finish",
    minDistance: 4,
    maxDistance: 14,
    averageSpeedRange: [14.5, 20.5],
    launchMultiplierRange: [1.18, 1.3],
    rollFloorRange: [2.2, 4.0],
    flightStyle: "driven",
    peakHeightRange: [0.18, 0.65],
    controlHeightRange: [0.22, 0.34],
    landingPhaseRange: [0.7, 0.82],
  },
  "edge-shot": {
    key: "edge-shot",
    label: "Edge-Box Shot",
    minDistance: 12,
    maxDistance: 24,
    averageSpeedRange: [17.2, 22.8],
    launchMultiplierRange: [1.24, 1.36],
    rollFloorRange: [3.0, 5.0],
    flightStyle: "driven",
    peakHeightRange: [0.35, 1.15],
    controlHeightRange: [0.24, 0.36],
    landingPhaseRange: [0.68, 0.8],
    curveRange: [0.12, 0.42],
    spinRateRange: [3.2, 5.2],
  },
  "long-shot": {
    key: "long-shot",
    label: "Long Shot",
    minDistance: 20,
    maxDistance: 35,
    averageSpeedRange: [19.2, 24.8],
    launchMultiplierRange: [1.28, 1.42],
    rollFloorRange: [3.6, 5.8],
    flightStyle: "driven",
    peakHeightRange: [0.55, 1.8],
    controlHeightRange: [0.26, 0.42],
    landingPhaseRange: [0.66, 0.78],
    curveRange: [0.18, 0.65],
    spinRateRange: [3.4, 5.8],
  },
};
export const autoDribbleProfiles = {
  "gk-carry": {
    key: "gk-carry",
    label: "GK Carry",
    tightSpeed: 1.85,
    openSpeed: 3.25,
    distanceBoost: [0, 0.18],
    pressurePenalty: 0.2,
    lanePressurePenalty: 0.14,
    minSpeed: 1.75,
    maxSpeed: 3.65,
  },
  "centre-back-carry": {
    key: "centre-back-carry",
    label: "Centre-Back Carry",
    tightSpeed: 2.05,
    openSpeed: 3.7,
    distanceBoost: [0, 0.24],
    pressurePenalty: 0.22,
    lanePressurePenalty: 0.17,
    minSpeed: 1.9,
    maxSpeed: 4.2,
  },
  "six-carry": {
    key: "six-carry",
    label: "No. 6 Carry",
    tightSpeed: 2.25,
    openSpeed: 4.0,
    distanceBoost: [0, 0.28],
    pressurePenalty: 0.21,
    lanePressurePenalty: 0.16,
    minSpeed: 2.0,
    maxSpeed: 4.55,
  },
  "eight-carry": {
    key: "eight-carry",
    label: "No. 8 Carry",
    tightSpeed: 2.5,
    openSpeed: 4.4,
    distanceBoost: [0.03, 0.36],
    pressurePenalty: 0.2,
    lanePressurePenalty: 0.18,
    minSpeed: 2.1,
    maxSpeed: 4.95,
  },
  "ten-carry": {
    key: "ten-carry",
    label: "No. 10 Carry",
    tightSpeed: 2.65,
    openSpeed: 4.5,
    distanceBoost: [0.02, 0.34],
    pressurePenalty: 0.19,
    lanePressurePenalty: 0.18,
    minSpeed: 2.15,
    maxSpeed: 5.05,
  },
  "fullback-carry": {
    key: "fullback-carry",
    label: "Fullback Carry",
    tightSpeed: 2.45,
    openSpeed: 4.7,
    distanceBoost: [0.04, 0.42],
    pressurePenalty: 0.2,
    lanePressurePenalty: 0.2,
    minSpeed: 2.1,
    maxSpeed: 5.25,
  },
  "wingback-carry": {
    key: "wingback-carry",
    label: "Wing-Back Carry",
    tightSpeed: 2.58,
    openSpeed: 4.9,
    distanceBoost: [0.05, 0.46],
    pressurePenalty: 0.2,
    lanePressurePenalty: 0.2,
    minSpeed: 2.15,
    maxSpeed: 5.45,
  },
  "winger-carry": {
    key: "winger-carry",
    label: "Winger Carry",
    tightSpeed: 2.82,
    openSpeed: 5.18,
    distanceBoost: [0.06, 0.52],
    pressurePenalty: 0.18,
    lanePressurePenalty: 0.21,
    minSpeed: 2.2,
    maxSpeed: 5.85,
  },
  "striker-carry": {
    key: "striker-carry",
    label: "Striker Carry",
    tightSpeed: 2.55,
    openSpeed: 4.75,
    distanceBoost: [0.04, 0.44],
    pressurePenalty: 0.21,
    lanePressurePenalty: 0.2,
    minSpeed: 2.1,
    maxSpeed: 5.35,
  },
};
