import { expect, test } from "@playwright/test";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createGameSimulatorEngineBundle } from "../src/modules/game-simulator/index.mjs";

const root = resolve(fileURLToPath(new URL("..", import.meta.url)));

function readProjectFile(path) {
  return readFileSync(resolve(root, path), "utf8");
}

test("game simulator engine wiring is isolated from app.js", () => {
  const app = readProjectFile("app-runtime.js");
  const engineWiring = readProjectFile("src/modules/game-simulator/engine-wiring.mjs");
  const engineActionSpaceWiring = readProjectFile("src/modules/game-simulator/engine-action-space-wiring.mjs");
  const engineAutopilotWiring = readProjectFile("src/modules/game-simulator/engine-autopilot-wiring.mjs");
  const engineAutopilotCandidatesWiring = readProjectFile("src/modules/game-simulator/engine-autopilot-candidates-wiring.mjs");
  const engineAutopilotDefensiveWiring = readProjectFile("src/modules/game-simulator/engine-autopilot-defensive-wiring.mjs");
  const engineAutopilotDecisionWiring = readProjectFile("src/modules/game-simulator/engine-autopilot-decision-wiring.mjs");
  const engineAutopilotLiveWiring = readProjectFile("src/modules/game-simulator/engine-autopilot-live-wiring.mjs");
  const engineAutopilotOffballWiring = readProjectFile("src/modules/game-simulator/engine-autopilot-offball-wiring.mjs");
  const engineAutopilotTargetsWiring = readProjectFile("src/modules/game-simulator/engine-autopilot-targets-wiring.mjs");
  const engineBallResolutionWiring = readProjectFile("src/modules/game-simulator/engine-ball-resolution-wiring.mjs");
  const engineCommandWiring = readProjectFile("src/modules/game-simulator/engine-command-wiring.mjs");
  const runtimeEntry = readProjectFile("src/modules/game-simulator/runtime-entry.mjs");
  const index = readProjectFile("src/modules/game-simulator/index.mjs");

  expect(typeof createGameSimulatorEngineBundle).toBe("function");
  expect(app).not.toContain("createGameSimulatorEngineBundle({");
  expect(runtimeEntry).toContain("createGameSimulatorEngineBundle({");
  expect(app).not.toContain("createGameSimulatorSetupEngine({");
  expect(app).not.toContain("createGameSimulatorCommandEngine({");
  expect(engineWiring).toContain("createGameSimulatorSetupEngine({");
  expect(engineWiring).toContain('from "./engine-action-space-wiring.mjs"');
  expect(engineWiring).toContain("createGameSimulatorActionSpaceRuntime({");
  expect(engineWiring).not.toContain("createGameSimulatorActionSpaceMetrics({");
  expect(engineActionSpaceWiring).toContain('from "./action-space-metrics.mjs"');
  expect(engineActionSpaceWiring).toContain("createGameSimulatorActionSpaceRuntime");
  expect(engineActionSpaceWiring).toContain("getAutoPilotFlowContext");
  expect(engineActionSpaceWiring).toContain("getGoalkeeperForTeam");
  expect(engineActionSpaceWiring).toContain("getPlannedPossessionTeamId");
  expect(engineWiring).toContain('from "./engine-autopilot-wiring.mjs"');
  expect(engineWiring).toContain("createGameSimulatorAutopilotRuntime({");
  expect(engineWiring).not.toContain("createGameSimulatorAutopilotLiveEngine({");
  expect(engineWiring).not.toContain("createGameSimulatorAutopilotTargets({");
  expect(engineAutopilotWiring).toContain('from "./engine-autopilot-live-wiring.mjs"');
  expect(engineAutopilotWiring).toContain('from "./engine-autopilot-decision-wiring.mjs"');
  expect(engineAutopilotWiring).toContain('from "./engine-autopilot-candidates-wiring.mjs"');
  expect(engineAutopilotWiring).toContain('from "./engine-autopilot-defensive-wiring.mjs"');
  expect(engineAutopilotWiring).toContain('from "./engine-autopilot-offball-wiring.mjs"');
  expect(engineAutopilotWiring).toContain('from "./engine-autopilot-targets-wiring.mjs"');
  expect(engineAutopilotWiring).toContain("createGameSimulatorAutopilotLiveRuntime({");
  expect(engineAutopilotWiring).toContain("createGameSimulatorAutopilotDecisionRuntime({");
  expect(engineAutopilotWiring).toContain("createGameSimulatorAutopilotCandidatesRuntime({");
  expect(engineAutopilotWiring).toContain("createGameSimulatorAutopilotDefensiveRuntime({");
  expect(engineAutopilotWiring).toContain("createGameSimulatorAutopilotOffballRuntime({");
  expect(engineAutopilotWiring).toContain("createGameSimulatorAutopilotTargetsRuntime({");
  expect(engineAutopilotWiring).not.toContain('from "./autopilot-live-engine.mjs"');
  expect(engineAutopilotWiring).not.toContain('from "./autopilot-decision-engine.mjs"');
  expect(engineAutopilotWiring).not.toContain('from "./autopilot-candidates.mjs"');
  expect(engineAutopilotWiring).not.toContain('from "./autopilot-defensive-targets.mjs"');
  expect(engineAutopilotWiring).not.toContain('from "./autopilot-offball-targets.mjs"');
  expect(engineAutopilotWiring).not.toContain('from "./autopilot-targets.mjs"');
  expect(engineAutopilotWiring).not.toContain("createGameSimulatorAutopilotLiveEngine({");
  expect(engineAutopilotWiring).not.toContain("createGameSimulatorAutopilotDecisionEngine({");
  expect(engineAutopilotWiring).not.toContain("createGameSimulatorAutopilotCandidates({");
  expect(engineAutopilotWiring).not.toContain("createGameSimulatorAutopilotDefensiveTargets({");
  expect(engineAutopilotWiring).not.toContain("createGameSimulatorAutopilotOffballTargets({");
  expect(engineAutopilotWiring).not.toContain("createGameSimulatorAutopilotTargets({");
  expect(engineAutopilotWiring).toContain("createGameSimulatorAutopilotRuntime");
  expect(engineAutopilotCandidatesWiring).toContain('from "./autopilot-candidates.mjs"');
  expect(engineAutopilotCandidatesWiring).toContain("createGameSimulatorAutopilotCandidatesRuntime");
  expect(engineAutopilotCandidatesWiring).toContain("createGameSimulatorAutopilotCandidates(context)");
  expect(engineAutopilotDefensiveWiring).toContain('from "./autopilot-defensive-targets.mjs"');
  expect(engineAutopilotDefensiveWiring).toContain("createGameSimulatorAutopilotDefensiveRuntime");
  expect(engineAutopilotDefensiveWiring).toContain("createGameSimulatorAutopilotDefensiveTargets(context)");
  expect(engineAutopilotDecisionWiring).toContain('from "./autopilot-decision-engine.mjs"');
  expect(engineAutopilotDecisionWiring).toContain("createGameSimulatorAutopilotDecisionRuntime");
  expect(engineAutopilotDecisionWiring).toContain("createGameSimulatorAutopilotDecisionEngine(context)");
  expect(engineAutopilotLiveWiring).toContain('from "./autopilot-live-engine.mjs"');
  expect(engineAutopilotLiveWiring).toContain("createGameSimulatorAutopilotLiveRuntime");
  expect(engineAutopilotLiveWiring).toContain("createGameSimulatorAutopilotLiveEngine(context)");
  expect(engineAutopilotOffballWiring).toContain('from "./autopilot-offball-targets.mjs"');
  expect(engineAutopilotOffballWiring).toContain("createGameSimulatorAutopilotOffballRuntime");
  expect(engineAutopilotOffballWiring).toContain("createGameSimulatorAutopilotOffballTargets(context)");
  expect(engineAutopilotTargetsWiring).toContain('from "./autopilot-targets.mjs"');
  expect(engineAutopilotTargetsWiring).toContain("createGameSimulatorAutopilotTargetsRuntime");
  expect(engineAutopilotTargetsWiring).toContain("createGameSimulatorAutopilotTargets(context)");
  expect(engineWiring).toContain('from "./engine-ball-resolution-wiring.mjs"');
  expect(engineWiring).toContain("createGameSimulatorBallResolutionRuntime({");
  expect(engineWiring).not.toContain("createGameSimulatorBallResolutionEngine({");
  expect(engineBallResolutionWiring).toContain('from "./ball-resolution-engine.mjs"');
  expect(engineBallResolutionWiring).toContain("createGameSimulatorBallResolutionRuntime");
  expect(engineBallResolutionWiring).toContain("formatTime");
  expect(engineBallResolutionWiring).toContain("getOpponentGoalCenter");
  expect(engineBallResolutionWiring).toContain("getPlannedPossessionTeamId");
  expect(engineWiring).toContain('from "./engine-command-wiring.mjs"');
  expect(engineWiring).toContain("createGameSimulatorCommandRuntime({");
  expect(engineWiring).not.toContain("createGameSimulatorCommandEngine({");
  expect(engineCommandWiring).toContain('from "./command-engine.mjs"');
  expect(engineCommandWiring).toContain("createGameSimulatorCommandRuntime");
  expect(engineCommandWiring).toContain("formatTime");
  expect(engineCommandWiring).toContain("getFirstTouchModeLabel");
  expect(engineCommandWiring).toContain("getOpponentGoalCenter");
  expect(engineCommandWiring).toContain("getPlayerTendency");
  expect(engineCommandWiring).toContain("isWideChannel");
  expect(engineWiring).toContain("getState");
  expect(engineWiring).not.toContain("() => state");
  expect(index).toContain('export { createGameSimulatorEngineBundle } from "./engine-wiring.mjs";');
});
