import { expect, test } from "@playwright/test";
import { createGameSimulatorCommandAutoplay } from "../src/modules/game-simulator/command-autoplay.mjs";

function createCommandAutoplay(overrides = {}) {
  const events = [];
  const state = overrides.state || {
    actionMode: "pass",
    offensiveAutopilot: true,
    isRunning: false,
    draftStep: null,
    ball: {
      actionType: null,
      firstTouchMode: "auto",
      position: { x: 42, y: 34 },
    },
    autoPilotPlay: { active: true, nextActionTimeoutId: null },
    sequence: { isPlaying: false },
  };
  const carrier = { id: "H8", team: "home", role: "CM", position: { x: 42, y: 34 } };
  let timeoutCallback = null;

  const autoplay = createGameSimulatorCommandAutoplay({
    applyAutopilotsForCurrentAction: (options) => events.push(["autopilots", options]),
    chooseAutoPilotLooseBallRecovery: () => null,
    chooseAutoPilotNextAction: () => ({
      actionType: "pass",
      firstTouchMode: "forward",
      formation: "4-3-3",
      label: "line-breaking pass",
      phaseLabel: "Build up",
      principleLabels: ["third man"],
      principleRunnerPlayerId: "H9",
      reason: "support angle is open",
      receiverPlayerId: "H9",
      styleLabel: "control",
      target: { x: 56, y: 32 },
      teamId: "home",
    }),
    clamp: (value, min, max) => Math.max(min, Math.min(max, value)),
    clearKeyboardActionGrace: () => events.push(["keyboardGrace"]),
    cloneVector: (point) => ({ ...point }),
    defaultKickoffTeamId: "home",
    executePlannedAction: () => events.push(["execute"]),
    getAttackingDepth: () => 58,
    getAutoPilotFlowContext: () => ({ carrierJustReceived: false }),
    getAutoPilotPossessionPlayer: () => carrier,
    getAutoPilotReceiveMomentum: () => null,
    getOffensiveAutopilotProfile: () => ({ directness: 0.45, shortSupport: 0.62, tempo: 0.58, styleKey: "control-possession" }),
    getPitchThreatProfile: () => ({ box: 0.1, centralPocket: 0.2 }),
    getPlayerBallControlPoint: (player) => player.position,
    getPlayerById: (playerId) => ({ id: playerId, role: "ST", shortLabel: "9" }),
    getPlayerMagnetLabel: (player) => player.shortLabel,
    getPlayerPressureLoad: () => 0.32,
    hasBallAction: () => Boolean(state.ball.actionType),
    issueDribbleCommand: () => events.push(["dribble"]),
    issueLooseBallRecoveryCommand: () => false,
    issuePassCommand: (target, receiverPlayerId) => {
      state.draftStep = { actionType: "pass", target, receiverPlayerId };
      events.push(["pass", target, receiverPlayerId]);
    },
    issueShotCommand: () => events.push(["shot"]),
    logEvent: (message) => events.push(["log", message]),
    pauseLiveSimulation: (message) => events.push(["pauseLive", message]),
    randomBetween: () => 0,
    render: () => events.push(["render"]),
    state,
    teams: { home: { name: "Home" } },
    updateSequenceButtons: () => events.push(["buttons"]),
    win: {
      clearTimeout: (id) => events.push(["clearTimeout", id]),
      setTimeout: (callback, delay) => {
        timeoutCallback = callback;
        events.push(["setTimeout", delay]);
        return 77;
      },
    },
    ...overrides,
  });

  return {
    autoplay,
    carrier,
    events,
    getTimeoutCallback: () => timeoutCallback,
    state,
  };
}

test("game simulator command autoplay plans and labels an attacking action", () => {
  const { autoplay, events, state } = createCommandAutoplay();

  expect(autoplay.planAutoPilotNextAction({ startImmediately: false })).toBe(true);

  expect(state.actionMode).toBeNull();
  expect(state.ball.firstTouchMode).toBe("forward");
  expect(state.draftStep).toMatchObject({
    actionType: "pass",
    autoGenerated: true,
    autoReason: "support angle is open",
    firstTouchMode: "forward",
    principleRunnerPlayerId: "H9",
    receiverPlayerId: "H9",
  });
  expect(state.draftStep.autoPrinciples).toEqual(["third man"]);
  expect(events).toContainEqual(["keyboardGrace"]);
  expect(events).toContainEqual(["autopilots", { silent: true }]);
  expect(events.find((event) => event[0] === "log")?.[1]).toContain("line-breaking pass");
});

test("game simulator command autoplay schedules the next continuation", () => {
  const { autoplay, events, getTimeoutCallback, state } = createCommandAutoplay();

  autoplay.scheduleAutoPilotContinuation(210, "pass");

  expect(events).toContainEqual(["setTimeout", 210]);
  expect(state.autoPilotPlay.nextActionTimeoutId).toBe(77);

  getTimeoutCallback()();

  expect(state.autoPilotPlay.nextActionTimeoutId).toBeNull();
  expect(state.draftStep).toMatchObject({ actionType: "pass", autoGenerated: true });
});
