import { expect, test } from "@playwright/test";
import { createGameSimulatorCommandSequenceRecorder } from "../src/modules/game-simulator/command-sequence-recorder.mjs";

function cloneValue(value) {
  return value ? JSON.parse(JSON.stringify(value)) : value;
}

function createSequenceRecorder(overrides = {}) {
  const events = [];
  const state = overrides.state || {
    ball: {
      firstTouchMode: "auto",
      position: { x: 20, y: 34 },
      profileKey: "balanced",
      profileLabel: "Balanced",
      profileMode: "match",
      recoveryDuration: 0,
      targetKind: "receiver",
    },
    ballSpeedMode: "medium",
    draftStep: null,
    matchPhase: "restart",
    restartPhase: { teamId: "home", type: "corner" },
    sequence: { currentFrameIndex: -1, dirty: false, initialSnapshot: null, isPlaying: false, steps: [] },
  };

  const recorder = createGameSimulatorCommandSequenceRecorder({
    applyCommittedSnapshot: (snapshot) => events.push(["committed", snapshot]),
    applyCornerSetup: (snapshot, setup) => {
      snapshot.cornerSetup = setup;
      events.push(["corner", setup]);
    },
    applyFreeKickSetup: (snapshot, setup) => events.push(["freeKick", setup]),
    applyGoalKickSetup: (snapshot, setup) => events.push(["goalKick", setup]),
    applyKickoffSetup: (snapshot, setup) => events.push(["kickoff", setup]),
    applyPenaltySetup: (snapshot, setup) => events.push(["penalty", setup]),
    applyThrowInSetup: (snapshot, setup) => events.push(["throwIn", setup]),
    captureSnapshot: () => ({ captured: true }),
    clearBallAction: () => {
      state.ball.actionType = null;
      state.draftStep = null;
      events.push(["clear"]);
    },
    cloneAutoV2DecisionTriggers: cloneValue,
    cloneDefensiveAutopilotIntents: cloneValue,
    cloneGoalEvent: cloneValue,
    cloneOffensiveAutopilotIntents: cloneValue,
    cloneRestartPhase: cloneValue,
    cloneShotPlacement: cloneValue,
    cloneSnapshot: cloneValue,
    cloneVector: cloneValue,
    createCommittedSnapshotFromCurrentState: () => ({ matchPhase: state.matchPhase }),
    describeStep: (step, index) => ({ title: `Step ${index + 1}: ${step.actionType}` }),
    getRecordedStepEndSnapshot: (step) => step.afterSnapshot,
    logEvent: (message) => events.push(["log", message]),
    markSequenceDirty: () => {
      state.sequence.dirty = true;
      events.push(["dirty"]);
    },
    state,
    ...overrides,
  });

  return { events, recorder, state };
}

test("game simulator command sequence recorder owns frame snapshot persistence", () => {
  const { recorder, state } = createSequenceRecorder({
    state: {
      ball: { position: { x: 20, y: 34 } },
      draftStep: null,
      sequence: {
        currentFrameIndex: 0,
        dirty: false,
        initialSnapshot: null,
        isPlaying: false,
        steps: [
          { afterSnapshot: { frame: 0 }, beforeSnapshot: { frame: "start" } },
          { beforeSnapshot: { frame: 1 } },
        ],
      },
    },
  });

  recorder.persistCurrentFrameSnapshot({ frame: "saved" });

  expect(state.sequence.dirty).toBe(true);
  expect(state.sequence.steps[0].afterSnapshot).toEqual({ frame: "saved" });
  expect(state.sequence.steps[1].beforeSnapshot).toEqual({ frame: "saved" });
  expect(recorder.getSequenceFrameSnapshot(0)).toEqual({ frame: "saved" });
  expect(recorder.getSequenceStartSnapshot()).toEqual({ frame: "start" });
});

test("game simulator command sequence recorder finalizes draft steps and restart snapshots", () => {
  const { events, recorder, state } = createSequenceRecorder();
  state.draftStep = {
    actionType: "pass",
    autoGenerated: true,
    autoPrinciples: ["support-triangle"],
    beforeSnapshot: { frame: "before" },
    defensiveAutopilot: {
      ballFocusPoint: { x: 20, y: 34 },
      behaviorVersion: "v2",
      intents: { H5: "cover-lane" },
      phaseKey: "mid-block",
      phaseLabel: "Mid Block",
      presserPlayerId: "A7",
      teamId: "away",
    },
    firstTouchMode: "forward",
    nextRestartPhase: { sideY: 68, teamId: "home", type: "corner" },
    offensiveAutopilot: {
      ballFocusPoint: { x: 20, y: 34 },
      behaviorVersion: "v2",
      intents: { H8: "offer-angle" },
      phaseKey: "build-up",
      phaseLabel: "Build Up",
      principleKey: "triangle",
      principleLabel: "Triangle",
      runnerPlayerId: "H11",
      teamId: "home",
      triggers: { pressure: 0.3 },
    },
    profileKey: "driven",
    profileLabel: "Driven",
    receiverPlayerId: "H9",
    speed: 18,
    target: { x: 44, y: 28 },
  };

  recorder.finalizeCurrentActionStep();

  expect(state.sequence.steps).toHaveLength(1);
  expect(state.sequence.steps[0]).toMatchObject({
    actionType: "pass",
    autoGenerated: true,
    autoPrinciples: ["support-triangle"],
    firstTouchMode: "forward",
    nextRestartPhase: { sideY: 68, teamId: "home", type: "corner" },
    profileKey: "driven",
    receiverPlayerId: "H9",
  });
  expect(state.sequence.steps[0].afterSnapshot.cornerSetup).toEqual({
    resetFormations: false,
    sideY: 68,
    teamId: "home",
  });
  expect(state.sequence.currentFrameIndex).toBe(0);
  expect(state.sequence.dirty).toBe(true);
  expect(state.draftStep).toBeNull();
  expect(events).toContainEqual(["log", "Step 1: pass was saved automatically."]);
});
